// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc
// * docs/getting-started-guide/master.adoc

:_content-type: CONCEPT
[id="about-rules_{context}"]
= The {ProductShortName} rules

The {ProductFullName} contains rule-based migration tools (analyzers) that you can use to analyze the application user interfaces (APIs), technologies, and architectures used by the applications you plan to migrate.

An analyzer rule is a set of instructions used to analyze source code and detect issues that are problematic for migration.

The analyzer parses user-provided rules, applies them to applications' source code, and generates issues for matched rules.

A collection of one or more rules forms a ruleset. Creating rulesets provides a way of organizing multiple rules that achieve a common goal.

The analyzer CLI takes rulesets as input arguments.

You can use the {ProductShortName} rules internally to perform the following tasks:

* Extract files from archives.
* Decompile files.
* Scan and classify file types.
* Analyze XML and other file content.
* Analyze the application code.
* Build the reports.

{ProductShortName} builds a data model based on the analysis results and stores component data and relationships in a graph database. This database can then be queried and updated as required by the migration rules and for reporting purposes.


[NOTE]
====
You can create your own custom analyzer rules. You can use custom rules to identify the use of custom libraries or other components that might not be covered by the provided standard migration rules.

ifndef::rules-development-guide[]
For instructions on how to write custom rules, see [_{RulesDevBookName}_].
endif::rules-development-guide[]
====
