// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="create-first-yaml-rule_{context}"]
= Creating a YAML rule

[role="_abstract"]
You can create a YAML-based rule to discover instances where an application defines a `jboss-web.xml` file containing a `<class-loading>` element and to provide a link to the documentation that describes how to migrate the code. 


.Prerequisites

* You installed {ProductShortName}. See Installing and running the CLI.

.Procedure
. Create a YAML file for the rule. In the following example, the rule is available in the `$HOME` directory.
+
[options="nowrap",subs="attributes+"]
----
$ mkdir /home/<USER>/rule.yaml
----

. Create a `data` directory:
+
[options="nowrap",subs="attributes+"]
----
mkdir /home/<USER>/data/
----

. Create a `jboss-web.xml` file in the `data` directory:
+
[options="nowrap",subs="attributes+"]
----
touch /home/<USER>/data/jboss-web.xml
----

. Create a `pom.xml` file in the `data` directory:
+
[options="nowrap",subs="attributes+"]
----
touch /home/<USER>/data/pom.xml
----

. In the `jboss-web.xml` file you created, paste the following content:
+
[options="nowrap",subs="attributes+"]
----
<!DOCTYPE jboss-web PUBLIC "-//JBoss//DTD Web Application 4.2//EN" "http://www.jboss.org/j2ee/dtd/jboss-web_4_2.dtd">
<jboss-web>
    <class-loading java2ClassLoadingCompliance="false">
        <loader-repository>
            seam.jboss.org:loader=@projectName@
            <loader-repository-config>java2ParentDelegation=false</loader-repository-config>
        </loader-repository>
    </class-loading>
</jboss-web>
----

. In the `pom.xml` file you created, paste the following content:
+
[options="nowrap",subs="attributes+"]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>

  <groupId>test</groupId>
  <artifactId>test</artifactId>
  <version>1.1.0-SNAPSHOT</version>

  <properties>
	<maven.compiler.source>1.7</maven.compiler.source>
	<maven.compiler.target>1.7</maven.compiler.target>
  </properties>

  <dependencies>
  </dependencies>
</project>
----

. In the `rule.yaml` file you created, paste the following contents:
+
[options="nowrap",subs="attributes+"]
----
- ruleID: jboss5-web-class-loading
  description: Find class loading element in JBoss XML file.
  when:
    builtin.xml:
      xpath: /jboss-web/class-loading
  message: The class-loading element is no longer valid in the jboss-web.xml file.
  effort: 3
  links:
  - url: https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.4/html-single/Migration_Guide/index.html#Create_or_Modify_Files_That_Control_Class_Loading_in_JBoss_Enterprise_Application_Platform_6
    title: Create or Modify Files That Control Class Loading in JBoss EAP 6
----
+
where:

  `ruleID` :: Unique ID for your rule. For example, `jboss5-web-class-loading`.
  `description` :: Text description of the rule.
  `when` :: Complete the `when` block specifying one or more conditions:
  .. Use the `builtin` provider's XML capability because this rule checks for a match in an XML file.
+
[options="nowrap",subs="attributes+"]
----
when:
  builtin.xml:
    xpath: /jboss-web/class-loading
----
+

`message` :: Helpful message explaining the migration issue. {ProductShortName} includes the message in the report when the rule matches. For example:
+

[source, yaml]
----
message: The class-loading element is no longer valid in the jboss-web.xml file.
----

  `labels` :: List of string labels for the rule.
  `effort` :: Number of expected story points to resolve this issue.
  `links` :: One or more hyperlinks pointing to documentation around the migration issues that you find.
+

[options="nowrap",subs="attributes+"]
----
  links:
    - url: https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.4/html-single/Migration_Guide/index.html#Create_or_Modify_Files_That_Control_Class_Loading_in_JBoss_Enterprise_Application_Platform_6
  title: Create or Modify Files That Control Class Loading in JBoss EAP 6
----
+

The rule is now complete.


.Verification

To verify that the rule works:

. Point the CLI to the rule file you created:
+
[options="nowrap",subs="attributes+"]
----
–rules /home/<USER>/rules.yaml
----

. Pass the rule by using the rules option in MTA CLI:
+
[options="nowrap",subs="attributes+"]
----
mta-cli analyze --input /home/<USER>/data/ --output /home/<USER>/output/ --rules /home/<USER>/rules.yaml
----

. Open `/home/<USER_NAME>/output/static-report/index.html` in a web browser.
+
[options="nowrap",subs="attributes+"]
----
INFO[0066] Static report created. Access it at this URL:  URL="file:/home/<USER>/output/static-report/index.html"
----
+
. Navigate to the *Issues* tab in the left menu.
. In the *Issues* table, type `JBoss XML` in the search bar.
. Verify that the issue with the title `Find class loading element in JBoss XML file` is present in the table.
. Click the *jboss-web.xml* link to open the affected file.

[role="_additional-resources"]
.Additional resources
* link:{ProductDocUserGuideURL}/index#installing_and_running_the_cli[Installing and running the CLI]






