// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="create-python-custom-rule_{context}"]
= Creating custom Python rules

[role="_abstract"]
You must create custom rules to analyze `Python` applications by using {ProductShortName}. A `Python` rule contains the `python.referenced` capability with the supported fields. 

The following example uses two custom rules: 

* The first rule checks if `bad_method` is specified 
* The second rule checks if `hello_world` is specified in `file_a.py` in your project.

.Procedure
. Create the directory `test-python`.
+
[source, terminal]
----
$ mkdir -p ~/test-python
----

. Create a `python-rule-001.yml` file in the directory and add the following rule:
+
[source, yaml]
----
- category: mandatory
  ruleID: python-rule-001
  effort: 1
  description: "Bad method"
  when:
    python.referenced:
      pattern: "bad_method"
----

. Create a `python-rule-002.yml` file in the directory and add the following rule:
+
[source, yaml]
----
  - category: mandatory
    ruleID: python-rule-002
    effort: 1
    message: "Found a python"
    when:
      python.referenced:
        pattern: "hello_world"
----

. Save the following `Python` code as `file_b.py`.
+

[source, python]
----
import deprecated
def hello_world():
          return "Hello, world!"
@deprecated.deprecated("This method is bad!")
def bad_method():
         return "I'm a bad method!"
----

. Save the following code as a second file, `file_a.py`.
+
[source, python]
----
import file_b
print(file_b.hello_world())
print(file_b.bad_method())
----

. Run the following command in the {ProductShortName} CLI:
+
[source, terminal]
----
$ ./mta-cli analyze -i ~/test-python/ -o \
~/test-python/report --run-local=false \
--rules ~/test-python/python-rule-001. \
--rules ~/test-python/python-rule-002.yml
----
+

[NOTE]
====
Add the `--overwrite` option if you want to use the same directory for the report when you run subsequent tests. {ProductShortName} overwrites the current report with the result of the latest analysis that you run.
====

. Open the static report at `~/test-python/report/static-report/index.html` in your browser.

. Click the _<application_name>_ to open the Dashboard.

. Review the incidents in the *Issues* tab.

