// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="create-go-custom-rule_{context}"]
= Creating a custom Go rule

[role="_abstract"]
You can create custom rules for Golang (Go) applications based on the following example.

Use the following custom rule to check if the custom resource definition exposed to the Kubernetes API server has a valid format in the source code.

. Create a `yaml` file with the name of the rule in your `Home` directory. For example, `go-01.yaml`.

. Copy the following rule in the `yaml` file:
+

[source, yaml]
----
  ruleID: go-lang-ref-001
  description: 
  effort: 1
  category: mandatory
  when:
    go.referenced:
        pattern: "v1beta1.CustomResourceDefinition"
  message: 'golang apiextensions/v1/customresourcedefinitions found {{file}}:{{lineNumber}}'
----

. Create a test `go` file named *example.go* in your `Home` directory.

. Paste the following code in the *example.go* file:
+

[source, go]
----
package main

import (
	"fmt"

	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
)

func main() {
	fmt.Println(v1beta1.CustomResourceDefinition{})

}
----

. Run the following command in the {ProductShortName} CLI:
+

[source, terminal]
----
$ mta-cli analyze --input /home/<USER>/example.go --output /home/<USER>/output/ --rules /home/<USER>/go-01.yaml
----

. Open the static report in the path `/home/<USER>/output/static-report/` in your browser.

. Navigate to the issues to verify the `golang apiextensions/v1/customresourcedefinitions found {{file}}:{{lineNumber}}` issue.

