// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: CONCEPT
[id="yaml-dotnet-provider_{context}"]
= C# provider

[role="_abstract"]
The `C#` provider can analyze `.NET` and `C#` application source code by using the `referenced` capability. The `C#` provider uses a gRPC interface to perform a semantic analysis of an application source code in the `source-only` mode. 

The provider parses the source code by using tree-sitter and uses stack graph for the analysis to find references to types, methods, classes, and fields. Based on the custom rule definition, the analyzer identifies violations in the source code that Migrators must resolve before the application migration. 

`referenced`::

The `C#` provider supports the `referenced` capability in rules to define fields such as `pattern` and `location`. The provider uses these patterns to search the source code for violations. 

[source,yaml]
----
when:
  csharp.referenced:
    pattern: "<pattern>" 
    location: CLASS 
----
where:

* `pattern` is a regular expression pattern to match the required reference, for example, `HttpNotFound`.
* `namespace` is a namespace to search within, for example, `System.Web.Mvc`.
