// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: CONCEPT

[id="yaml-rule-metadata-structure_{context}"]
= Rule metadata structure

[role="_abstract"]
Rule metadata contains a unique rule ID, labels, effort, and category so that the analyzer can select the rules for an analysis and compute the total effort to resolve the issues detected in the source code.

You can use rule metadata to:

* Estimate the total migration effort. 
* Prioritize issues for resolution based on the effort.
* Evaluate if a resolution is mandatory through rule category before migrating the applications to the target technologies or platforms.
* Define labels that {ProductShortName} uses to filter rules for an analysis.

[source,yaml, subs="+quotes"]
----
ruleID: "_<unique_id>_" 
labels: 
  # key=value pair
  - "label1=_<val1>_"
  # valid label with value omitted
  - "label2"
  # valid label with empty value
  - "label3="
  # subdomain prefixed key
  - "konveyor.io/label1=_<val1>_"
effort: 1 
category: mandatory 
----

where:

* `ruleID` is a unique ID for the rule. It must be unique within the ruleset.
* `labels` is a list of string labels associated with the rule.
* `effort` is an integer value that indicates the level of effort needed to resolve this issue.
* `category` is the severity of the issue for migration. Values can be one of `mandatory`, `potential` or `optional`.


[role="_additional-resources"]
.Additional resources
* xref:yaml-rule-labels_rule-yaml-metadata[Rule labels]
* xref:yaml-rule-categories_rule-yaml-metadata[Rule categories]