// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: REFERENCE
[id="yaml-dotnet-provider_{context}"]
= C# provider

[role="_abstract"]
The `C#` provider is an external provider used to analyze `.NET Core` and `C#` source code. Currently, the provider supports the `referenced` capability.

The `C#` provider uses a gRPC interface to perform a semantic analysis of an application source code in the `source-only` mode. The provider parses the source code by using tree-sitter and uses stack graph for the analysis to find references to types, methods, classes, and fields. Based on the `C#` custom rule definition, the analyzer identifies violations in your code that you must resolve before the application migration. 

`referenced`::

The `C#` provider supports `referenced` capability in rules to define fields such as `pattern` and `location` based on which the provider searches the code for violations. 
+
[source,yaml]
----
when:
  csharp.referenced:
    pattern: "<pattern>" 
    location: CLASS 
----
+
where:

* `pattern` is a regular expression pattern to match the required reference. For example, `HttpNotFound`.
* `namespace` specifies the namespace to search within, for example, `System.Web.Mvc`.
