// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: CONCEPT
[id="yaml-rule-structure-syntax_{context}"]
= YAML rule structure and syntax

[role="_abstract"]
Rules instruct the analyzer to take the specified actions when the given conditions match. In {ProductShortName}, a rule file contains one or more rules.

You can write rules in YAML. They consist of:

* metadata
* conditions
* actions

{ProductShortName} analyzer rules have the following pattern:

[source, yaml, subs="+quotes"]
----
ruleID: _<Rule_id>_
category: mandatory
effort: _<Effort_number>_
description:
   _<Description title>_
   _<Description text>_
labels:
  - konveyor.io/source=_<Source_tech>_
  - konveyor.io/target=_<Target_tech>_
links:
 - url: _<Hyperlink>_
   title: _<Hyperlink_title>_
when:
 <condition(s)>
message: "message"
tag: 
 - _<tag_1>_, _<tag_2>_, _<tag_3>_
 - key_1="_<value_1>_, _<value_2>_"
----
where:

`ruleID` :: A unique id for the rule within the ruleset
`category` :: Severity level of an issue that the rule triggers can be `severe`, `mandatory`, or `optional`. 
`effort` :: An integer value that represents the level of effort needed to fix the issue.
`description` :: A short sentence or a title that summarizes the issue.
`labels` :: A key-value pair of source and target technology. You can also add filter in the label to always include or exclude this rule during an analysis.
