// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: REFERENCE
[id="yaml-chaining-condition-variables_{context}"]
= Chaining Condition Variables

[role="_abstract"]
You can use the output of one condition as the input for filtering another one in the `and` and `or` conditions. This is called *condition chaining*.


.Example

[source,yaml]
----
when:
 or:
  - builtin.xml:
      xpath: "//dependencies/dependency"
      filepaths: "{{poms.filepaths}}"
    from: poms
  - builtin.file:
      pattern: pom.xml
    as: poms
    ignore: true
----

In the above example, the output of the `builtin.file` condition is saved as `poms`:

+
[source,yaml]
----
[...]
      as: poms
[...]
----

The variables of `builtin.file` can then be used in the `builtin.xml` condition, by writing `from` and then using link:https://mustache.github.io/mustache.5.html[mustache templates] in the `provider_ condition` block.

This is how this particular condition knows how to use the variable set to the name `poms`.

+
[source,yaml]
----
[...]
    from: poms
[...]
----

Then you can use the variables by setting them as mustached templates in
any of the inputs to the _provider_ condition.

+
[source,yaml]
----
[...]
      filepaths: "{{poms.filepaths}}"
[...]
----

[NOTE]
====
If you only want to use the values of a condition as a chain, you can set `ignore: true`.

This will tell the engine not to use this condition to determine whether the rule has been violated or not:
+
[source,yaml]
----
[...]
    ignore: true
[...]
----
====
