// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: REFERENCE
[id="yaml-condition-patterns_{context}"]
= Condition patterns

[role="_abstract"]
In the `pattern` field of a `java.referenced` condition, the analyzer can search through application code by using the Java Development Kit (JDK) utilities. You can use a wildcard or a specific string to locate classes and methods to refine what the analyzer searches for in the source code.

For more details on the JDK utilities, see Class SearchPattern documentation, which  contains all the information for building these patterns for `createPattern(String, int, int, int)`.

Review the following examples of condition patterns:

* Search for any class under the `javax.xml` package, occurring in any
location:
+
[source,yaml]
----
java.referenced:
  pattern: javax.xml.*
----

* Search for method declarations that return `java.lang.String`:
+
[source,yaml]
----
java.referenced:
  location: METHOD
  pattern: '* java.lang.String'
----

* Search for a method named "`method`" declared on `org.konveyor.MyClass`
that returns a `List` of a type that extends `java.lang.String`:
+
[source,yaml]
----
java.referenced:
  location: METHOD
  pattern: 'org.konveyor.Myclass.method(*) java.util.List<? extends java.lang.String>'
----

* Search for a class that implements `java.util.List`:
+
[source,yaml]
----
java.referenced:
  location: IMPLEMENTS_TYPE
  pattern: java.util.List
----

.Additional resources

* link:https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fsearch%2FSearchPattern.html&anchor=createPattern[Class SearchPattern]