// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: CONCEPT
[id="yaml-java-provider_{context}"]
= Java provider

[role="_abstract"]
The `java` provider offers `referenced` and `dependency` capabilities to analyze Java source code. 

`referenced`::
The `referenced` capability takes three input parameters: `pattern`, `location`, and `annotated`:
+
[source,terminal]
----
when:
  java.referenced:
    pattern: "<pattern>" 
    location: "<location>" 
    annotated: "<annotated>" 
----
+
where:

* `pattern` is a regular expression pattern to match.
* `location` is the exact source code location where {ProductShortName} matches the pattern, for example, `IMPORT`.
* `annotated` checks for specific annotations and their elements, such as name and value, in the Java code by using a query. For example, the following query matches the `Bean` (URL = “http://www.example.com”) annotation in the method.
+
[source,yaml]
----
 annotated:
      pattern: org.framework.Bean
      elements:
      - name: url
        value: "http://www.example.com"
----

`dependency`::
The Java provider has `dependency` capability. The `dependency` capability enables the provider to generate a list of dependencies for a given application.
+
You can use a `dependency` condition to query this list and check whether a certain dependency, with a version range, exists for the application. The dependency can be internal and external or open source.
For example, to check if a Java application has a certain dependency, you create a `java.dependency` condition:
+
[source, yaml]
----
when:
  java.dependency:
    name: junit.junit
    upperbound: 4.12.2
    lowerbound: 4.4.0
----
+
You can use the `dependency` capability to check if a Java application has Fabric8 Kubernetes client of version 5.0.100 or lower:
+
[source, yaml]
----
- java.dependency:
    name: io.fabric8.kubernetes-client
    lowerbound: 5.0.100
----
+
[NOTE]
====
When you use the `java` provider for an analysis, the analysis results have lower precision for projects that cannot be built. For example, when {ProductShortName} is unable to build a `Maven` project, it falls back to parsing the `pom` file to get the list of dependencies.
====

[role="_additional-resources"]
.Additional resources
* xref:java-conditions-capabilities_rules-development-guide[Java condition and capabilities]