// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: CONCEPT

[id="yaml-rule-metadata-structure_{context}"]
= Rule metadata structure

[role="_abstract"]
Rule metadata contains a unique rule ID, labels, effort, and category.

[source,yaml]
----
ruleID: "unique_id" 
labels: 
  # key=value pair
  - "label1=val1"
  # valid label with value omitted
  - "label2"
  # valid label with empty value
  - "label3="
  # subdomain prefixed key
  - "konveyor.io/label1=val1"
effort: 1 
category: mandatory 
----

where:

* `ruleID` is a unique ID for the rule. It must be unique within the ruleset.
* `labels` is a list of string labels associated with the rule.
* `effort` is an integer value that indicates the level of effort needed to resolve this issue.
* `category` is the severity of the issue for migration. Values can be one of `mandatory`, `potential` or `optional`.


[role="_additional-resources"]
.Additional resources
////
Optional. Delete if not used.
Provide a bulleted list of links and display text relevant to the assembly. These links can include `link:` and `xref:` macros. Do not include additional text.
////
* xref:yaml-rule-labels_rule-yaml-metadata[Rule labels]
* xref:yaml-rule-categories_rule-yaml-metadata[Rule categories]