// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: REFERENCE
[id="yaml-condition-patterns_{context}"]
= Condition patterns

The Language Server used by the Java provider is Eclipse’s JDTLS. Internally, the JDTLS uses the Eclipse Java Development Toolkit, which includes utilities for searching code in projects.

In the `pattern` element of a `java.referenced` condition, you can search through application code by using these utilities. For more details, see link:https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fsearch%2FSearchPattern.html&anchor=createPattern[Class SearchPattern], which  contains all the information for building these patterns for `createPattern(String, int, int, int)`.

.Examples

* Search for any class under the `javax.xml` package, occurring in any
location:
+
[source,yaml]
----
java.referenced:
  pattern: javax.xml*
----
+
[WARNING]
====
When matching against packages, as in the previous example, the asterisk must not be after a dot. For example:
* `pattern: javax.xml*`
and not:
* `pattern: javax.xml.*`

====

* Search for method declarations that return `java.lang.String`:
+
[source,yaml]
----
java.referenced:
  location: METHOD
  pattern: '* java.lang.String'
----

* Search for a method named "`method`" declared on `org.konveyor.MyClass`
that returns a `List` of a type that extends `java.lang.String`:
+
[source,yaml]
----
java.referenced:
  location: METHOD
  pattern: 'org.konveyor.Myclass.method(*) java.util.List<? extends java.lang.String>'
----

* Search for a class that implements `java.util.List`:
+
[source,yaml]
----
java.referenced:
  location: IMPLEMENTS_TYPE
  pattern: java.util.List
----
