// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: CONCEPT
[id="yaml-chaining-condition-variables_{context}"]
= Chaining condition variables

[role="_abstract"]
You can use condition chaining, where the pattern of one condition becomes the template variable for filtering in another condition. Use condition chaining to scope down the search query to look for a pattern in a subset of files. 

For example, you can search for one or more `pom.xml` files and find dependencies in those subset of `pom` files and not any other file in your project. You can use logical `and` and `or` for chaining conditions. 

[source,yaml]
----
when:
 or:
  - builtin.xml:
      xpath: "//dependencies/dependency"
      filepaths: "{{poms.filepaths}}"
    from: poms
  - builtin.file:
      pattern: pom.xml
    as: poms
    ignore: true
----

In the earlier example, {ProductShortName} saves the output of the `builtin.file` condition in `poms`:

[source,yaml]
----
[...]
      as: poms
[...]
----

You can use the variables of `builtin.file` in the `builtin.xml` condition, by writing `from` and then using Mustache templates in the `provider_ condition` block.

This is how the condition knows how to use the variable set to the name `poms`.

[source,yaml]
----
[...]
    from: poms
[...]
----

Then you can use the variables by setting them as Mustache templates in
any of the inputs to the _provider_ condition.

[source,yaml]
----
[...]
      filepaths: "{{poms.filepaths}}"
[...]
----

[NOTE]
====
If you only want to use the values of a condition as a chain, you can set `ignore: true`.

This will tell the engine not to use this condition to find a rule violation:

[source,yaml]
----
[...]
    ignore: true
[...]
----
====

[role="_additional-resources"]
.Additional resources
* link:https://mustache.github.io/mustache.5.html[Mustache templates] 