// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: REFERENCE

[id="yaml-java-locations_{context}"]
= Java locations

[role="_abstract"]
The `java` provider allows scoping the search down to certain source code locations.

* *IMPORT*: IMPORT allows for searches on class imports. It can either
be used with Fully Qualified Names (FQNs) or an asterisk to allow for wider matches:

[source,yaml]
----
java.referenced:
  pattern: org.apache.lucene.search.*
  location: IMPORT
----

would match on each of these imports:

[source,java]
----
import org.apache.lucene.search.Query;
import org.apache.lucene.search.Sort;
import org.apache.lucene.search.SortField;
----

* *PACKAGE*: the `PACKAGE` location matches on any usage of a package, be
it in an import or used as part of an FQN in the code:

[source,yaml]
----
java.referenced:
  pattern: org.apache.lucene.search.*
  location: PACKAGE
----

would match on each of the following imports and the FQN usage:

[source,java]
----
import org.apache.lucene.search.Query;
import org.apache.lucene.search.Sort;
import org.apache.lucene.search.SortField;
----

[source,java]
----
public class Test {
  private org.apache.lucene.search.Query query;
}
----

.Supported Java locations
[cols="3,3,6"]
|===
|Location |Description |Rule condition example

|TYPE|Matches against all types, including classes, interfaces, enums, and annotation types that appear anywhere.
a|The following example looks for occurrences of `java.util.List`.
[source, yaml]
----
 when:
  java.referenced:
   location: TYPE
   pattern: java.util.List
---- 
|ANNOTATION|Matches against annotations.
a|The following example matches the `@org.framework.Bean(url = "http://www.example.com")` annotation in the source code.
[source, yaml]
----
when:
  java.referenced:
    location: ANNOTATION
    pattern: org.framework.Bean
    annotated:
      elements:
        - name: url
          value: "http://www.example.com"
----
|IMPLEMENTS_TYPE|Matches against any type implementing the given type.
a|The following example looks for a class that implements `java.util.ArrayList`.
[source, yaml]
----
 when:
  java.referenced:
   location: IMPLEMENTS_TYPE
   pattern: java.util.ArrayList
----
|RETURN_TYPE|Matches against a type being returned by a method.
a|The following example searches for `@PersistenceContext` annotation for injecting data sources and `@Produces` annotation on the `EntityManager`. These annotations are not required when you target migrating the source code to `Quarkus`.
[source, yaml]
----
when:
  java.referenced:
    location: RETURN_TYPE
      pattern: javax.persistence.EntityManager
      annotated:
        pattern: javax.enterprise.inject.Produces
----
|VARIABLE_DECLARATION|Matches against a type being declared as a variable
a|The following example searches for `QueueConnectionFactory` that was used to obtain a connection to JMS queues appearing as a variable declaration. Replace the string `QueueConnectionFactory` with `ConnectionFactory`.
[source, yaml]
----
when:
  - java.referenced:
      location: VARIABLE_DECLARATION
      pattern: javax.jms.QueueConnectionFactory
----
|FIELD|Matches against a type appearing in a field
declaration. It can be coupled with an annotation match happening on the field. See
xref:yaml-annotation-inspection_java-conditions-capabilities[Annotation inspection]
a|The following example searches if `QueueConnectionFactory` appears in a field declaration and is used to obtain connection to JMS queues. Replace the string `QueueConnectionFactory` with `ConnectionFactory`.
[source, yaml]
----
when:
  - java.referenced:
      location: FIELD_DECLARATION
      pattern: javax.jms.QueueConnectionFactory
----
|METHOD|Matches against a given method declaration. It can be coupled
with an annotation match. See
xref:yaml-annotation-inspection_java-conditions-capabilities[Annotation inspection]
a|The following example finds declarations of methods named `method` that accept `java.lang.String` and return `org.konveyor.ExtendedString`.

[source, yaml]
----
when:
 java.referenced:
   location: METHOD
   pattern: 'method(java.lang.String) org.konveyor.ExtendedString' 
----
|METHOD_CALL|Matches against the method call in the source code.
a|The following example matches the `getConnection` method call of the `java.sql.DriverManager` class with three parameters of type `String`.
[source, yaml]
----
when:
  java.referenced:
    location: METHOD_CALL
    pattern: java.sql.DriverManager.getConnection(java.lang.String, java.lang.String, java.lang.String)
----
|CLASS (declaration)|Matches against a given method declaration. Can be coupled with an annotation match. See xref:yaml-annotation-inspection_java-conditions-capabilities[Annotation inspection].
a|The following example locates all classes under the `javax.xml` package occurring in all locations of the source code.
[source, yaml]
----
when:
 java.referenced:
  pattern: javax.xml.*
----
|CONSTRUCTOR_CALL|Matches against constructor calls in the source code.
a|The following example matches the `FileOutputStream` constructor call that takes a String and a boolean value as input parameters.
[source, yaml]
----
when:
  java.referenced:
    location: CONSTRUCTOR_CALL
    pattern: java.io.FileOutputStream(java.lang.String, boolean)
----
|IMPORT|Matches against class imports. You can use it with FQNs or an asterisk (*) to allow for wider matches.
a|The following example matches with the imports of `org.apache.lucene.search` package and subpackages in the source code.
[source, yaml]
----
when:
 java.referenced:
   pattern: org.apache.lucene.search.*
   location: IMPORT
----
|PACKAGE|Matches on any usage of a package, be it in an import or used as part of a fully qualified name in the code.
a|The following example matches all occurrences of `org.jboss` package and its subpackages in the source code.
[source, yaml]
----
when:
  java.referenced:
    location: PACKAGE
    pattern: org.jboss.*
----
|INHERITANCE|Matches against a class inheriting from a given type.
a|The following example searches for interfaces that extend the `org.jboss.system.ServiceMBeanSupport` class. 

[source, yaml]
----
 when:
  java.referenced:
    pattern: 'org.jboss.system.ServiceMBeanSupport'
    location: INHERITANCE
----
|===