// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: REFERENCE
[id="yaml-provider-conditions_{context}"]
= Rule condition

[role="_abstract"]
In the rule condition, the Architect defines the patterns that {ProductShortName} searches for in the source code to trigger an issue. The condition you can define to search an application written in a programming language depends on the capabilities that providers offer. 

A rule condition instructs the analyzer to use a specific provider and one of its capabilities. A condition follows the `<provider_name>.<capability>` pattern. 

[source,yaml, subs="+quotes"]
----
when:
  _<provider_name>_._<capability>_
    _<input_fields>_
----

The analyzer currently supports the following providers:

* `builtin`
* `java`
* `go`
* `nodejs`
* `python`
* `csharp`

:FeatureName: `csharp`, `python`, and `nodejs` providers
[IMPORTANT]
====
[subs="attributes+"]
{FeatureName} are Developer Preview features only. Developer Preview features are not supported by Red Hat in any way and are not functionally complete or production-ready. Do not use Developer Preview features for production or business-critical workloads. Developer Preview features provide early access to upcoming product features in advance of their possible inclusion in a Red Hat product offering, enabling customers to test functionality and provide feedback during the development process. These features might not have any documentation, are subject to change or removal at any time, and testing is limited. Red Hat might provide ways to submit feedback on Developer Preview features without an associated Service Level Agreement (SLA).
====
:!FeatureName:


[[table-Supported-providers-and-rule-conditions]]
[options="header"][cols="99,99,99,99"][%autowidth]
|===

|Provider rule conditions |Provider name

| Providers that are fully supported and included in the product
| `java`

| Providers that have rules already defined in the product
a| 
* `java`

|Providers that require custom rulesets for analysis
a|
* `go`
* `python`
* `nodejs`
* `csharp`
|===

The following table summarizes all the providers and their
capabilities:

.Summary of providers and their capabilities
[width="100%",cols="15%,25%,60%",options="header",]
|===
|Provider Name |Capabilities |Description

.2+|`java`
|`referenced`
a|Find references of a pattern with an optional code location for detailed searches. 
For example, 
[source,yaml, subs="+quotes"]
----
when:
  java.referenced:
    _<fields>_
----
|`dependency`
a|Check whether the application has a given dependency.
For example, 

[source,yaml, subs="+quotes"]
----
when:
  java.dependency:
    _<fields>_
----

.5+|`builtin`
|`xml`
|Search XML files using XPath queries.


|`json`
a|Search JSON files using JSONPath queries.
For example,
[source, yaml, subs="+quotes"]
----
when:
  builtin.json:
    _<fields>_ 
----

|`filecontent`
a|Search content in regular files using regular expression patterns.
For example,
[source, yaml, subs="+quotes"]
----
when:
  builtin.filecontent:
    _<fields>_ 
----


|`file`
a|Find files with names matching a given pattern.
For example,
[source, yaml, subs="+quotes"]
----
when:
  builtin.file:
    _<fields>_ 
----

|`hasTags`
a|Check whether you created a tag for the application using a tagging rule.
For example,
[source, yaml, subs="+quotes"]
----
when:
  builtin.hasTags:
    _<fields>_ 
----

.2+|`go`
|`referenced`
a|Find references to a pattern.
For example, 
[source,yaml, subs="+quotes"]
----
when:
  go.referenced:
    _<fields>_
----

|`dependency`
a|Check whether the application has a given dependency.
For example, 
[source,yaml, subs="+quotes"]
----
when:
  go.dependency:
    _<fields>_
----

|`csharp`
|`referenced`
a|Find references to a pattern.
For example, 
[source,yaml, subs="+quotes"]
----
when:
  csharp.referenced:
    _<fields>_
----
|===

Following the example in the previous table, you can create the first part of the condition that does not contain any of the condition fields.

To create a `java` provider condition that uses the `referenced` capability:

[source,yaml, subs="+quotes"]
----
when:
  java.referenced:
    _<fields>_
----

[NOTE]
====
Depending on the _provider_ and the _capability_, there will be different `<fields>` in the condition.
====

The following table summarizes available providers, their capabilities and their fields:

.Summary of providers, their capabilities, and their fields
[width="100%",cols="10%,10%,10%,10%,60%",options="header",]
|===
|Provider |Capability |Fields |Required |Description

.7+|`java`
.3+|`referenced`
|`pattern`
|Yes
a|Regular expression pattern.
For example,
[source, yaml]
----
when:
  java.referenced:
    location: PACKAGE
    pattern: org.jboss.*
----

|`location`
|No
a|Source code location. See Java locations.
For example,
[source, yaml]
----
when:
  java.referenced:
    pattern: org.kubernetes*
    location: IMPORT
----

|`annotated`
|No
a|Additional query to inspect annotations. See Annotation inspection.
For example,
[source, yaml]
----
when:
  java.referenced:
    location: ANNOTATION
    pattern: javax.ejb.Singleton
----

.4+|`dependency`
|`name`
|Yes
a|Name of the dependency.
For example,
[source, yaml]
----
when:
  java.dependency:
    name: junit.junit
----

|`nameregex`
|No
|Regular expression pattern to match the name.

|`upperbound`
|No
a|Match versions lower than or equal to.
For example,
[source, yaml]
----
when:
  java.dependency:
    name: junit.junit
    upperbound: 4.12.2
----

|`lowerbound`
|No
a|Match versions greater than or equal to.
For example,
[source, yaml]
----
when:
  java.dependency:
    name: junit.junit
    upperbound: 4.12.2
    lowerbound: 4.4.0
----

.9+|`builtin`
.3+|`xml`
|`xpath`
|Yes
a|an XPath query
[source, yaml]
----
when:
  builtin.xml:
    xpath: "//dependencies/dependency"
----

|`namespaces`
|No
a|A map to scope down query to namespaces.
[source, yaml]
----
when:
  builtin.xml:
    filepaths:
     - beans.xml
    namespaces:
        b: http://xmlns.jcp.org/xml/ns/javaee
    xpath: /b:beans
----

|`filepaths`
|No
a|Optional list of files to scope down search.
[source, yaml]
----
when:
    or:
    - builtin.xml:
        xpath: "//dependencies/dependency"
        filepaths: "{{poms.filepaths}}"
      from: poms
    - builtin.file:
        pattern: pom.xml
      as: poms
      ignore: true
----

.2+|`json`
|`xpath`
|Yes
a|an XPath query
For example,
[source, yaml]
----
when:
    and:
    - builtin.json:
        xpath: //inclusionTestNode
----

|`filepaths`
|No
a|Optional list of files to scope down search.
For example,
[source, yaml]
----
when:
    and:
    - builtin.json:
        xpath: //inclusionTestNode
        filepaths: "{{incTest.filepaths}}"
----

.2+|`filecontent`
|`pattern`
|Yes
a|Regular expression pattern to match in content.
For example,

[source, yaml]
----
when:
  builtin.filecontent:
    pattern: "import.*React"
----

|`filePattern`
|No
a|Only search in files with names matching this pattern.
For example,

[source, yaml]
----
when:
  builtin.filecontent:
    pattern: "import.*React"
    filePattern: "\\.tsx$"
----

|`file` 
|`pattern`
|Yes
a|Find files with names matching this pattern.
For example,
[source, yaml]
----
when:
    builtin.file:
      pattern: "*.go"
----

|`hasTags`
|
|
a|This is an inline list of string tags. See Tag action.
For example,

[source, yaml]
----
when:
  or:
   - builtin.hasTags:
     - Golang
     - Kubernetes
----

.5+|`go`
|`referenced`
|`pattern`
|Yes
a|Regular expression pattern.
For example,
[source, yaml]
----
when:
  go.referenced:
    pattern: "v1beta1.CustomResourceDefinition"
----

.4+|`dependency`
|`name`
|Yes
a|Name of the dependency.
For example,
[source, yaml]
----
when:
  - go.dependency:
      name: sigs.k8s.io/structured-merge-diff/v4
----

|`nameregex`
|No
|Regular expression pattern to match the name.

|`upperbound`
|No
a|Match versions lower than or equal to.
For example,
[source, yaml]
----
when:
  - go.dependency:
      name: sigs.k8s.io/structured-merge-diff/v4
      upperbound: v4.2.2
----

|`lowerbound`
|No
a|Match versions greater than or equal to.
For example,
[source, yaml]
----
when:
  - go.dependency:
      name: sigs.k8s.io/structured-merge-diff/v4
      lowerbound: v4.2.0
----

.2+|`csharp`
.2+|`referenced`
|`pattern`
|Yes
|Regular expression to match a reference in the source code. For example, `System.Web.Mvc.*`.

|`location`
|Yes
a|Specify one of the following for which {ProductShortName} runs a search query:

 * Type reference including classes, interfaces and structure types (struct). For example: 

[source, yaml]
  ----
  when:
    csharp.referenced:
      location: CLASS
      pattern: System.Web.Http.ApiController.*
  ----

[source, yaml]
  ----
  when:
    csharp.referenced:
      location: ALL
      pattern: "System.Console.Print*"
  ----

 * Method calls and definitions. For example:

[source, yaml]
  ----
  when:
    csharp.referenced:
      location: METHOD
      pattern: "*.AppDomain.Unload"
  ----

 * Field usages and declaration. For example:

[source, yaml]
  ----
  when:
    csharp.referenced:
      location: FIELD
      pattern: "DotNetOpenAuth.AspNet.AuthenticationResult.Provider"
  ----

 * Namespace imports and usages. For example: 
 
[source, yaml]
  ----
  when:
    csharp.referenced:
      location: ALL
      pattern: "System.Windows.Forms"
  ----

 * `ALL` - You can also specify `ALL` as `location` to run a search query on any location in the code, including namespaces, structure types, and interfaces.
|===

[role="_additional-resources"]
* xref:yaml-java-provider_rules-prov-cond[Java]
* xref:yaml-java-locations_java-conditions-capabilities[Java locations]
* xref:yaml-annotation-inspection_java-conditions-capabilities[Annotation inspection]
* xref:yaml-tag-actions_rule-yaml-actions[Tag action]
* xref:yaml-go-provider_rules-prov-cond[Go]
* xref:yaml-dotnet-provider_rules-prov-cond[Csharp]



