// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: REFERENCE
[id="yaml-custom-variables_{context}"]
= Custom variables

[role="_abstract"]
You can create custom variables in provider conditions. You can use custom variables to capture relevant information from a line in the source code that violates the rule. {ProductShortName} interpolates the values of these variables with the piece of data in the source code. You can add variables to a rule in the `customVariables` field.

You can use the custom variable values to generate detailed template messages in a rule's action (see Message actions). 

[source,yaml]
----
- ruleID: lang-ref-004
   customVariables:
   - pattern: '([A-z]+)\.get\(\)' 
      name: VariableName 
    message: "Found generic call - {{ VariableName }}" 
  when:
      java.referenced:
          location: METHOD_CALL
          pattern: com.example.apps.GenericClass.get

----
where:

  `pattern` :: A regular expression pattern that {ProductShortName} uses to find a match on the source code line.
  `name` :: The name of the variable that can be used in templates.
  `message` :: A template for a message by using a custom variable.

[role="_additional-resources"]
.Additional resources
* xref:yaml-message-actions_rule-yaml-actions[Message actions]