// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: REFERENCE
[id="yaml-custom-variables_{context}"]
= Custom variables

Provider conditions can have associated custom variables. You can use custom variables to capture relevant information from the matched line in the source code. The values of these variables are interpolated with data matched in the source code. These values can be used to generate detailed template messages in a rule's action (see xref:yaml-rule-actions_rule-yaml-actions[Message actions]). They can be added to a rule in the `customVariables` field:

[source,yaml]
----
- ruleID: lang-ref-004
   customVariables:
   - pattern: '([A-z]+)\.get\(\)' # <1>
      name: VariableName # <2>
    message: "Found generic call - {{ VariableName }}" # <3>
  when:
      java.referenced:
          location: METHOD_CALL
          pattern: com.example.apps.GenericClass.get

----
<1> `pattern`: A regular expression pattern that is matched on the source code line when a match is found.
<2> `name`: The name of the variable that can be used in templates.
<3> `message`: A template for a message using a custom variable.
