// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: REFERENCE
[id="yaml-dotnet-provider_{context}"]
= Csharp provider

[role="_abstract"]
The `csharp` provider is an external provider used to analyze `.NET` and `C#` source code. Currently, the provider supports the `referenced` capability.

The `csharp` provider uses a gRPC interface to perform a semantic analysis of an application source code in the `source-only` mode. The provider parses the source code by using tree-sitter and uses stack graph for the analysis to find references to types, methods, classes, and fields. Based on the `C#` rule definition, the analyzer identifies violations in your code that you must resolve before the application migration. 

The `csharp` provider you to install `.NET` software development kit (SDK) 9.x or later.

== `referenced`

The `csharp` provider supports `referenced` capability in rules to define fields such as `pattern`and `location` based on which the provider searches the code for violations. 

[source,yaml]
----
when:
  csharp.referenced:
    pattern: "<pattern>" 
    location: CLASS 
----
where:

 `pattern` :: A regular expression pattern to match the needed reference. For example, `System.Web.Http.ApiController.*`
 `location` :: Specifies the location in the source code to search the pattern. For example, `CLASS`.

NOTE: You can also specify `location` as `METHOD`, `FIELD`, or `ALL`. When the `location` is `ALL`, the `C#` provider runs a search query for namespaces, structure types, and interfaces.
