// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: REFERENCE

[id="yaml-java-locations_{context}"]
= Java locations

The `java` provider allows scoping the search down to certain source code locations.

* *IMPORT*: IMPORT allows for searches on class imports. It can either
be used with FQNs or an asterisk to allow for wider matches:

[source,yaml]
----
java.referenced:
  pattern: org.apache.lucene.search*
  location: IMPORT
----

would match on each of these imports:

[source,java]
----
import org.apache.lucene.search.Query;
import org.apache.lucene.search.Sort;
import org.apache.lucene.search.SortField;
----

:warning: If you want to match using an asterisk (`++*++`) for a wider
range of results, it is recommended to place it directly after the
package, not after the dot:

:no++_++entry++_++sign: `org.apache.lucene.search.++*++`
:white++_++check++_++mark: `org.apache.lucene.search++*++`

* *PACKAGE*: the PACKAGE location matches on any usage of a package, be
it in an import or used as part of a fully qualified name in the code:

[source,yaml]
----
java.referenced:
  pattern: org.apache.lucene.search*
  location: PACKAGE
----

would match on both the import and the fully qualified usage:

[source,java]
----
import org.apache.lucene.search.*;
----

[source,java]
----
public class Test {
  private org.apache.lucene.search.Query query;
}
----

:warning: As in the IMPORT condition, try to avoid using asterisk
(`++*++`) right after the package-separation dot (`.`) for better
results.

* *CONSTRUCTOR++_++CALL* and *METHOD++_++CALL*: for matching
constructors and methods, respectively. The pattern possibilities are
quite varied, and it is possible to match against specific return types,
arguments, etc.

For instance, looking for a method named "`method`" declared on
`org.konveyor.MyClass` that returns a `List` of a type that extends
`java.lang.String` and accepts a single parameter:

[source,yaml]
----
java.referenced:
  location: METHOD
  pattern: 'org.konveyor.Myclass.method(*) java.util.List<? extends java.lang.String>'
----

More information about the possibilities of these patterns can be found in link:https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fsearch%2FSearchPattern.html&anchor=createPattern(java.lang.String,int,int,int)[the official Java documentaion, which contain all the information for building these patterns] in the `createPattern(String, int, int, int)` section.

[WARNING] 
====
Presently, fully qualified static method matching is prone
to errors.
====

* *TYPE*: matches against types in general, appearing anywhere.
* *INHERITANCE*: matches against a class inheriting from a given type.
* *ANNOTATION*: matches against annotations.
* *IMPLEMENTS++_++TYPE*: matches against any type implementing the given
type.
* *ENUM++_++CONSTANT*: matches against enum constants.
* *RETURN++_++TYPE*: matches against a type being returned by a method.
* *VARIABLE++_++DECLARATION*: matches against a type being declared as a
variable.
* *FIELD* (declaration): matches against a type appearing in a field
declaration. It can be coupled with an annotation match, this is, an
annotation happening on the field (see
link:#annotation-inspection[Annotation inspection])
* *METHOD*: matches against a given method declaration. It can be coupled
with an annotation match (see link:#annotation-inspection[Annotation
inspection]).
* *CLASS* (declaration): matches against a given method declaration. Can
be coupled with an annotation match (see
link:#annotation-inspection[Annotation inspection]).


The supported locations are the following:

* `CONSTRUCTOR_CALL`
* `TYPE`
* `INHERITANCE`
* `METHOD_CALL`
* `ANNOTATION`
* `IMPLEMENTS_TYPE`
* `ENUM_CONSTANT`
* `RETURN_TYPE`
* `IMPORT`
* `VARIABLE_DECLARATION`
* `FIELD`
* `METHOD`

.`dependency`

By using the `dependency` capability, the provider finds dependencies for a given application. {ProductShortName} generates a list of the application's dependencies, and you can use this capability to query the list and check whether a certain dependency exists for the application within a given range of the dependency's versions.

[source,yaml]
----
when:
  java.dependency:
    name: "<dependency_name>" # <1>
    upperbound: "<version_string>" # <2>
    lowerbound: "<version_string>" # <3>
----
<1> Name of the dependency to search for.
<2> Upper bound on the version of the dependency.
<3> Lower bound on the version of the dependency.
