// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc
:_mod-docs-content-type: CONCEPT
[id="assessment-module-features_{context}"]
= The Assessment module features

[role="_abstract"]
You can use the assessment module in the {ProductFullName} user interface (UI) to evaluate the suitability of applications for modernization. These evaluations help you identify migration risks, estimate modernization effort, and prioritize applications in your portfolio.

The {ProductFullName} *Assessment* module offers the following features for assessing and analyzing applications:

Assessment hub::
The *Assessment* hub integrates with the *Application inventory*.

Assessment questionnaires::
The *Assessment* module supports assessment questionnaires relevant to one or more applications.

Enhanced assessment questionnaire capabilities::
You can import and export assessment questionnaires. You can also design custom questionnaires with a downloadable template by using the YAML syntax, which includes the following features:

* Conditional questions: You can include or exclude questions based on the application or archetype if a certain tag is present on this application or archetype.
* Application auto-tagging based on answers: You can define tags to be applied to applications or archetypes if a certain answer was provided.
* Automated answers from tags in applications or archetypes.

+
NOTE: You can customize and save the default questionnaire.

Archetypes::
You can use archetypes to assess a group applications with similar characteristics. Each archetype has a shared taxonomy of tags, stakeholders, and stakeholder groups. All applications inherit assessment and review from their assigned archetypes.


[role="_additional-resources"]
.Additional resources
* xref:mta-custom-questionnaire_assessment-questionnaires[The custom assessment questionnaire]
* xref:mta-default-questionnaire_assessment-questionnaires[The default assessment questionnaire]
* xref:working-with-archetypes_user-interface-guide[Working with archetypes]
