:_newdoc-version: 2.18.5
:_template-generated: 2025-09-17
:_mod-docs-content-type: PROCEDURE

[id="accessing-analysis-insights_{context}"]
= Accessing analysis insights

Analysis insights contain information about the technologies used in the application and their usage in the code. Unlike issues, you do not need to fix insights for a successful migration. They are generated by any rule that does not have a positive effort value and category assigned. They might have a message and a tag. 
You can access analysis insights after you run an application analysis either from a static or dynamic report.

.Procedure

* Depending on your scenario, complete either of the following procedures:

** Access application insights from the static report:
.. Download an analysis report in the `.tar` format. For more information, see xref:downloading-an-analysis-report_analyzing-applications[Downloading an analysis report].
.. Extract the `.tar` file.
.. Open the `index.html` file to view the static report.
.. Click *Insights*.

** Access application insights from the dynamic report:
.. In the *Migration* view, click *Insights*.
.. On the *Insights* page, filter application insights by an application name to display insights for a particular application.


