// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="configuring-source-control-credentials_{context}"]
= Configuring source control credentials

[role="_abstract"]
To provide the {ProductFullName} with secure access to private repositories when analyzing an application or creating a custom migration target, configure source control credentials. 

Source control credentials include the username and password or Supply Chain Management (SCM) private key and a passphrase.

.Procedure

. In *Administration* view, click *Credentials*.
. Click *Create new*.
. Enter the following information:
* Name
* Description (Optional)
. In the *Type* list, select *Source Control*.
. In the *User credentials* list, select *Credential Type* and enter the requested information:

* Username/Password
** Username
** Password (hidden)
* SCM Private Key/Passphrase
** SCM Private Key
** Private Key Passphrase (hidden)

+
NOTE: Type-specific credential information such as keys and passphrases is either hidden or shown as [Encrypted].

. Optional: If you want to set source control credentials as default, enable the *Use as the source control credential if an application does not have any assigned?* switch.
. Click *Create*.
+
NOTE: {ProductShortName} validates the input and creates a new credential. SCM keys must be parsed and checked for validity. If the validation fails, the following error message is displayed: `“not a valid key/XML file”`.
