:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21

:_mod-docs-content-type: PROCEDURE

[id="automatic-tagging-of-an-application_{context}"]
= Setting up automatic tagging

[role="_abstract"]
To classify applications based on their technology stack, utilize automatic tagging in the {ProductFullName} user interface (UI).

{ProductFullName} UI automatically spawns language discovery and technology discovery tasks when adding an application to the *Application Inventory*. When the language discovery task is running, the technology discovery and analysis tasks wait until the language discovery task is finished. These tasks automatically add tags to the application. {ProductShortName} can automatically add tags to the application based on the application analysis. Automatic tagging is especially useful when dealing with large portfolios of applications.

NOTE: Automatic tagging of applications based on application analysis is enabled by default.


.Procedure

* Before running an application analysis, ensure that the *Enable automated tagging* checkbox is selected in the *Advanced* section of the *Analysis configuration* wizard.
+
To disable automatic tagging, deselect the *Enable automated tagging* checkbox.
