// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="configuring-jira-credentials_{context}"]
= Configuring Jira credentials

[role="_abstract"]
To define a Jira instance in {ProductShortName} and establish a connection to that instance, create an {ProductFullName} credential to authenticate to the Jira instance's API.

You can create either of the following types of Jira credentials:

* For Jira Cloud and a private Jira server or data center, use the *Basic auth* credential type. 		
* For Jira Cloud and a private Jira server or data center, use the *Basic auth* credential type. For a private Jira server or data center, use the *Bearer Token* credential type.

IMPORTANT: You cannot delete a credential that has already been assigned to a Jira connection instance.

.Procedure

. In *Administration* view, click *Credentials*.
. Click *Create new*.
. Enter the following information:
* *Name*
* *Description* (optional)
. In the *Type* list, select *Basic Auth (Jira)* or *Bearer Token (Jira)*:
+
* If you selected *Basic Auth (Jira)*, complete the following steps:

.. In the *Email* field, enter your email.
.. In the *Token* field, depending on the specific Jira configuration, enter either your token generated on the Jira site or your Jira login password.
+
NOTE: To obtain a Jira token, you need to log in to the Jira site.

.. Click *Save*.
+
The new credential appears on the *Credentials* page.

* If you selected *Bearer Token (Jira)*, complete the following steps:

.. In the *Token* field, enter your token generated on the Jira site.
.. Click *Save*.
+
The new credential appears on the *Credentials* page.

. Optional: To edit the credential, click *Edit*.


[role="_additional-resources"]
.Next steps

* xref:creating-a-jira-connection_creating-and-configuring-a-jira-connection[Create a Jira connection].
