// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="adding-applications_{context}"]
= Adding a new application to the {ProductShortName} UI

[role="_abstract"]
To populate your inventory for analysis, add applications to the {ProductFullName} user interface (UI).

You can add a new application to the *Application Inventory* for subsequent assessment and analysis.

NOTE: Before creating an application, set up business services, check tags and tag categories, and create additions.

.Prerequisites

* You are logged in to an {ProductShortName} server.

.Procedure

. In the *Migration* view, click *Application Inventory*.
. Click *Create new*.
. Under *Basic information*, enter the following fields:
* *Name*: A unique name for the new application.
* *Description*: A short description of the application (optional).
* *Business service*: A purpose of the application (optional).
* *Manual tags*: Software tags that characterize the application (optional, one or more).
* *Owner*: A registered software owner from the drop-down list (optional).
* *Contributors*: Contributors from the drop-down list (optional, one or more).
* *Comments*: Relevant comments on the application (optional).

. Click *Source Code* and enter the following fields:
* *Repository type*: *Git* or *Subversion*.
* *Source repository*: A URL of the repository where the software code is saved.
+
For the *Subversion* repository type, the URL to the root of the repository or a fully qualified URL which optionally includes the branch and nested directory. When fully qualified, the *Branch* and *Root path* must be blank.

* *Branch*: An application code branch in the repository (optional).
** For the *Git* repository type, this branch can be any reference, for example, `commit-hash`, `branch`, or `tag`.
** For the *Subversion* repository type, this branch is a fully qualified path to an application's branch or tag, for example, `branches/stable` or `tags/stable`. This must be blank when the *Source repository* URL includes the branch.
* *Root path*: A root path inside the repository for the target application (optional).
+
For the *Subversion* repository type, this field must be blank when the *Source repository* URL includes the root path.


+
NOTE: If you enter any value in either the *Branch* or *Root path* fields, the *Source repository* field becomes mandatory.

. Optional: Click *Binary* and enter the following fields:
* *Group*: The Maven group for the application artifact.
* *Artifact*: The Maven artifact for the application.
* *Version*: A software version of the application.
* *Packaging*: The packaging for the application artifact, for example, `JAR`, `WAR`, or `EAR`.

+
NOTE: If you enter any value in any of the Binary section fields, all fields automatically become mandatory.

. Click *Create*. The new application is displayed in the list of defined applications.

. Optional: Change the application settings by clicking *Edit* next to the application name: 		

.. Make the required adjustments.					
.. Click *Save*. 		

+
NOTE: After editing an application, {ProductShortName} recreates the language discovery and technology discovery tasks. For more information, see xref:displaying-automated-tasks_managing-applications[Displaying automated tasks].			


