:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21
:_mod-docs-content-type: PROCEDURE

[id="generating-deployment-assets_{context}"]
= Generating deployment assets by using a discovery manifest

[role="_abstract"] 
To prepare your application for deployment to a container platform, generate deployment assets by using a discovery manifest in the {ProductFullName} user interface (UI).

When you generate assets for an application, the generators render manifests for all the migration paths associated with the archetype of the application.

Note that you can generate application assets by using only source code, without generating a discovery manifest first. If the discovery manifest is unavailable, the generator uses the following implicit data from the application profile for opinionated asset generation:

* *Application metadata:* Information such as the application name, version, and unique identifiers.
* *Application archetypes:* Standardized templates or structures identified during the initial analysis.
* *Identified application tags:* Logic must be applied based on the tags found during analysis. For example:
** For Quarkus, configure specific environment variables for native-mode deployments.
** For Spring Boot, apply standard Spring framework configurations and dependencies to the generated manifests.

.Prerequisites

//provide link to platform awareness for the discovery manifest.
* You generated the discovery manifest.
* You configured the application tags in an archetype.
* You configured generators and target profile in the archetype.

.Procedure

. In the *Migration* view, click *Applications*.
. Click the Options menu ({kebab}) of an application.
. Click *Generate assets* to open the *Generate assets* dialog.
. Select a target profile and click *Next*.
. Click the toggle button to open the JSON view where you can enter the parameter values.
. Click *Next* to review the configurations to generate assets.
. Click *Generate assets*.

+
You can view the generated assets in the asset repository that you configured.