:_newdoc-version: 2.18.5
:_template-generated: 2025-09-12
:_mod-docs-content-type: PROCEDURE

[id="setting-default-credentials_{context}"]
= Setting default credentials

You might want to import a large list of applications to the {ProductFullName} user interface (UI). Each of these applications require credentials for both the language and technology discovery tasks. Instead of manually defining credentials for each application, you can set credentials that will be used by default. 

IMPORTANT: You can only set Maven or source control credentials as default credentials. You can only define one default set of credentials per credential type.

NOTE: Default credentials are not used for applications that already have credentials assigned to them.



.Prerequisites
* You added or imported an application to the {ProductShortName} UI. For more information, see the following procedures:
** xref:adding-applications_managing-applications[Adding a new application]
** xref:importing-an-app-list_managing-applications[Importing a list of applications]


.Procedure

. Optional: Identify the application that does not have credentials assigned to it: 
.. In the Migration view, display the list of applications by clicking Application inventory. 
.. Hover over the application name that does not have credentials assigned to it. The application discovery tasks fail for such applications.
. In the Administration view, click Credentials. 
. Set the default credentials:
.. Click the Options menu () to the right of the credential you want to set as default.
.. Click Set as default.
+
Alternatively, you can set default credentials directly when creating Maven or source code credentials. For more information, see the following procedures:

* xref:configuring-maven-credentials_configuring-credentials[Configuring Maven credentials]
* xref:configuring-source-control-credentials_configuring-credentials[Configuring source control credentials]


.Verification

. In the *Migration* view, display the list of applications by clicking *Application inventory*. 
. Hover over the application name that does not have credentials assigned to it. Because you set default credentials, the application discovery tasks are restarted.

