// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="assessing-an-application_{context}"]
= Assessing an application

[role="_abstract"]
Estimate the risks and costs involved in preparing applications for modernization by performing an application assessment in the {ProductFullName} user interface (UI).

The {ProductFullName} assesses applications according to a set of questions relevant to the application, such as dependencies. To assess the application, you can use the default xref:mta-default-questionnaire_assessment-questionnaires[Legacy Pathfinder] {ProductShortName} questionnaire or import your xref:mta-custom-questionnaire_assessment-questionnaires[custom] questionnaire.

IMPORTANT: You can assess only one application at a time.


[NOTE]
====
During the assessment, you might encounter false positives in an application that cannot be fully resolved. This can happen because {ProductShortName} cannot discover the class that is being called. Therefore, {ProductShortName} cannot determine whether it is a valid match or not. You can use the following solution to resolve the issue:

. Ensure that the maven settings can get all the dependencies.

. Ensure the application can be fully compiled.
====

.Prerequisites

* You are logged in to an {ProductShortName} server.

.Procedure

. In the {ProductShortName} user interface, select the *Migration* view.
. Click *Application inventory* in the left menu bar. A list of the available applications appears in the main pane.
. Select the application you want to assess.
. Click the *Options* menu ({kebab}) at the right end of the row and select *Assess* from the drop-down menu.
. From the list of available questionnaires, click *Take* for the desired questionnaire.
. Select *Stakeholders* and *Stakeholder groups* from the lists to track who contributed to the assessment for future reference.
+
NOTE: You can also add *Stakeholder Groups* or *Stakeholders* in the *Controls* pane of the *Migration* view. For more information, see xref:configuring-mta-instance_user-interface-guide[Configuring a {ProductName} instance].

. Click *Next*.
. Answer each *Application assessment* question and click *Next*.
. Click *Save* to review the assessment and proceed with the steps in xref:reviewing-an-application_assessing-applications[Reviewing an application].

 
[role="_additional-resources"]
.Additional resources
* xref:assessment-questionnaires_assessing-applications[{ProductShortName} assessment questionnaires]
* xref:managing-mta-questionnaires_assessing-applications[Managing assessment questionnaires]

