// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="profile-application-analysis_{context}"]
= Using a profile to run an application analysis 

[role="_abstract"]
As a Migrator, you can use a pre-configured analysis profile to analyze an application for a target platform. 

.Procedure

. In the *Migration* view, click *Application inventory*.
. Select an application that you want to analyze.
. Review the credentials assigned to the application.
. Click *Analyze*.
. In the *Mode* section, select *Use analysis profile*.
. Select a pre-configured profile from the list to run an analysis. 
. Click *Next* 
. *Enable automated tagging*. Select the checkbox to automatically attach tags to the application.
+
NOTE: {ProductShortName} displays automatically attached tags only after you run the analysis. You can attach tags to the application manually instead of enabling automated tagging or in addition to it.

. *Enable enhanced analysis details*. If you enable this option, {ProductShortName} uploads the logs and output of commands that you run to the Hub as the output streams. The information includes the analyzer raw report.

//need more information on the above option.
. Click *Next*.
. In *Review*, verify the analysis parameters.
. Click *Run*.
+
The analysis status is `Scheduled` while {ProductShortName} downloads the container image. After the download completes, the status changes to `In-progress`.
+
The analysis takes minutes to hours depending on the size of the application and the capacity and resources of the cluster.
+
NOTE: The {ProductShortName} uses Kubernetes scheduling capabilities to determine how many analyzer instances to create based on cluster capacity. By default, if you select multiple applications for analysis, the {ProductShortName} provisions only one analyzer at a time. With additional cluster capacity, the{ProductShortName} can execute more analysis processes in parallel.

. Optional: To track the status of your active analysis task, open the *Task Manager* view by clicking the notifications button.
+
Alternatively, hover over the application name to display the pop-over window.

.Verification 

* Check the report after the analysis is complete: 

. Open the application view by clicking on the application name.
. Click the *Reports* tab to download the results in the HTML or YAML format. 
+
[NOTE]
====
You can download the report after running an analysis if the {ProductShortName} Administrator enables the download option on the *General configuration* page in the *Administration* view.
====