// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="configuring-profile-application-analysis_{context}"]
= Configuring an analysis profile


[role="_abstract"]
Configure a profile that has the configuration needed to analyze an application for a specific migration target.

.Procedure

. In the *Migration* view, click *Analysis Profiles*.

. Click *Create new* to open the *Create Analysis Profile* window.

. Enter a unique name for the configuration profile in the *Profile Details* page.

. Click *Next* to go to the *Configure analysis* section. You can configure the analysis source, target platforms, and the scope of the dependency analysis. 
. Select the *Analysis source* from the list:
* Binary
* Source code
* Source code and dependencies
* Upload a local binary. This option only appears if you are analyzing a single application. If you chose this option, you must *Upload a local binary*. Either drag a file into the area provided or click *Upload* and select the file to upload.
. Click *Next*.
. Select one or more target options in *Set targets* for the analysis:

* Application server migration to either of the following platforms:
** JBoss EAP 7
** JBoss EAP 8
* Containerization
* Quarkus
* OracleJDK to OpenJDK
* OpenJDK. Use this option to upgrade to either of the following JDK versions:
** OpenJDK 11
** OpenJDK 17
** OpenJDK 21
* Linux. Use this option to ensure that there are no Microsoft Windows paths hard-coded into your applications.
* Jakarta EE 9. Use this option to migrate from Java EE 8.
* Spring Boot on Red Hat Runtimes
* Open Liberty
* Camel. Use this option to migrate from Apache Camel 2 to Apache Camel 3 or from Apache Camel 3 to Apache Camel 4.
* Azure App Service
. Click *Next*.
. Select one of the following *Scope* options to better focus the analysis:

* Application and internal dependencies only.
* Application and all dependencies, including known Open Source libraries.
* Select the list of packages that you want to analyze manually. If you choose this option, type the file name and click *Add*.
* Exclude packages. If you toggle this option on, type the name of the package and click *Add*.

. Click *Next*.
. In *Advanced*, you can attach custom rules to the analysis by selecting the *Manual* or *Repository* mode:
** In the *Manual* mode, click *Add Rules*. Drag the relevant files or select the files from their directory and click *Add*.
** In the *Repository* mode, you can add rule files from a *Git* or *Subversion* repository.
+
IMPORTANT: Attaching custom rules is optional if you have already attached a migration target to the analysis. If you have not attached any migration target, you must attach rules.

. Optional: Set any of the following options:
* Additional target labels
* Additional source labels
* Excluded rules labels. Rules with these labels are not processed. Add or delete as needed.

. Click *Next*.
. In *Review*, verify the analysis parameters.
. Click *Save*.
+
{ProductShortName} saves the analysis profile on the *Analysis Profiles* page.