// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="configuring-maven-credentials_{context}"]
= Configuring Maven credentials

[role="_abstract"]
To provide the {ProductFullName} with secure access to your private Maven repositories, configure authentication credentials in the user interface. Adding these credentials ensures analysis tasks can automatically retrieve the required data.

.Procedure

. In *Administration* view, click *Credentials*.
. Click *Create new*.
. Enter the following information:
* Name
* Description (Optional)
. In the *Type* list, select *Maven Settings File.*
. Upload the `settings.xml` file or paste its contents.
. Optional: If you want to set Maven credentials as default, enable the *Use as the Maven credential if an application does not have any assigned?* switch. These credentials will be used by default for all applications that do not have any assigned credentials.
+
IMPORTANT: If you do not set Maven credentials as default, you must assign these credentials to the application manually before running an analysis. Otherwise, credentials will not be picked up by the application, which might result in the analysis running longer.

. Click *Create*.
+
NOTE: {ProductShortName} validates the input and creates a new credential. The Maven `settings.xml` file must be parsed and checked for validity. If the validation fails, the following error message is displayed: `not a valid key/XML file`.
