:_newdoc-version: 2.18.5
:_template-generated: 2026-09-24
:_mod-docs-content-type: PROCEDURE

[id="enable-agent-in-tackle_{context}"]
= Enable agent in Tackle

[role="_abstract"]
To install custom resource definitions needed for agents in your cluster, you must enable the agent in the Tackle custom resource (CR).

.Procedure

. Log in to your Red{nbsp}Hat OpenShift cluster.
. Enter the following command in the `oc` CLI:
+
[subs="+quotes"]
----
$ *oc project openshift-mta*
----
. Edit the Tackle CR:
+
[subs="+quotes"]
----
$ *oc edit tackle*
----
. Switch to the insert mode in the terminal text editor:
+
[subs="+quotes"]
----
*i*
----
. Configure the `agentic_enabled` and `agentic_steer_enabled` environment variables:
+
[source,yaml]
----
kind: Tackle
apiVersion: tackle.konveyor.io/v1alpha1
metadata:
  name: mta
  namespace: openshift-mta
spec:
  agentic_enabled: "false"
  agentic_steer_enabled: "false"
----
+
where:

agentic_enabled:: Optional configuration that works if you deployed the Agent Sandbox operator in the cluster. When set to `true`, the field enables agentic controller in the backend and agent features in the {ProductShortName} web console. The field is set to `false` by default.

agentic_steer_enabled:: Optional configuration that allows interactive user input to agents when running agents. The field is set to `false` by default.

. Save the Tackle CR and exit the text editor to apply the changes:
+
[subs="+quotes"]
----
*:wq!*
----
. Restart the Tackle Hub deployment:
+
[subs="+quotes"]
----
$ *oc rollout restart deployment/tackle-hub -n openshift-mta*
----

.Verification

* Verify the deployment by noting the `READY` status:
+
[subs="+quotes"]
----
$ *oc get deployments -n openshift-mta*
----
