:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21
:_mod-docs-content-type: PROCEDURE

[id="configuring-target-profiles_{context}"]
= Configuring a target profile

[role="_abstract"]
Create and track the target profiles for a specific archetype in the {ProductFullName} user interface (UI).

The target profile contains one or more generators. Each generator generates assets for different migration paths. 

You can configure more than one target profile for the archetype based on the target platforms to which you want to migrate applications of the specific archetype.

//what does priority order mean?
The generators are run in a priority order, in which manifests generated by lower priority generators do not override manifests generated by other generators.  

.Procedure

. In the *Migration* view, click *Archetypes*.
. Click the Options menu ({kebab}) of an archetype, and select *Manage target profiles*.
+
The *Target profiles for <archetype-name>* appears.
. Click *Create new target profile*.
. In the *Name* field in the opened dialogue, enter a unique name for the target profile.
. Click the *Tag category* field and select the category tag to associate with the tag.
. Select specific generators and click the right arrow to move the generator from the *Available generators* list to the *Chosen generators* list.
. Click *Create*.

+
You can click on the archetype row to open the archetype detail view where the target profiles for the archetype are listed.