// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="creating-a-jira-connection_{context}"]
= Creating a Jira connection

[role="_abstract"]
To track your application migrations, define a Jira instance in the {ProductFullName} user interface and establish a connection to that instance.

You cannot remove a Jira connection used to create issues for a migration wave if those issues still exist in Jira, even after you delete the migration wave.

.Prerequisites

* You created {ProductShortName} credentials. For more information, see xref:configuring-jira-credentials_creating-and-configuring-a-jira-connection[Configuring Jira credentials]. 

.Procedure

. In the *Administration* view, under *Issue Management*, click *Jira*.
. Click *Create new*.
. In the *New instance* window, enter the following information:
* Name of the instance
* URL of the web interface of your Jira account
* Select either the *Jira Cloud* or *Jira Server/Data center* instance type from the list:
** If you select *Jira Cloud* as the instance type, the list displays only *Basic Auth* credentials.
** If you select *Jira Server/Data center* as an instance type, the list displays both *Basic Auth* and *Token Bearer* credentials.
* Select credentials from the list.
. By default, you cannot establish a connection with a server that has an invalid certificate. To override this restriction, enable the *Enable insecure communication* switch.
. Click *Create*.

.Verification

* On the *Jira configuration* page, ensure that you established and authorized the connection:

** If the *Connection* column displays *Connected*, you have successfully established and authorized the Jira connection.					
** If the *Connection* column displays *Not connected*, click the status to check the reason for the error. 