// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="assessing-an-application_{context}"]
= Assessing an application

You can estimate the risks and costs involved in preparing applications for containerization by performing application assessment. You can assess an application and display the currently saved assessments by using the Assessment module.

The {ProductFullName} assesses applications according to a set of questions relevant to the application, such as dependencies.

To assess the application, you can use the default xref:mta-default-questionnaire_assessment-questionnaires[Legacy Pathfinder] {ProductShortName} questionnaire or import your xref:mta-custom-questionnaire_assessment-questionnaires[custom] questionnaires.

IMPORTANT: You can assess only one application at a time.

.Prerequisites

* You are logged in to an {ProductShortName} server.

.Procedure

. In the {ProductShortName} user interface, select the *Migration* view.
. Click *Application inventory* in the left menu bar. A list of the available applications appears in the main pane.
. Select the application you want to assess.
. Click the *Options* menu ({kebab}) at the right end of the row and select *Assess* from the drop-down menu.
. From the list of available questionnaires, click *Take* for the desired questionnaire.
. Select *Stakeholders* and *Stakeholder groups* from the lists to track who contributed to the assessment for future reference.
+
NOTE: You can also add *Stakeholder Groups* or *Stakeholders* in the *Controls* pane of the *Migration* view. For more information, see xref:configuring-mta-instance_user-interface-guide[Configuring a {ProductName} instance].

. Click *Next*.
. Answer each *Application assessment* question and click *Next*.
. Click *Save* to review the assessment and proceed with the steps in xref:reviewing-an-application_assessing-applications[Reviewing an application].

[NOTE]
====
If you are seeing false positives in an application that is not fully resolvable, then this is not entirely unexpected.


The reason, is that {ProductShortName} cannot discover the class that is being called. Therefore, {ProductShortName} cannot determine whether it is a valid match or not.


When this happens, {ProductShortName} defaults to exposing more information than less.


In this situation, the following solutions are suggested:

. Ensure that the maven settings can get all the dependencies.

. Ensure the application can be fully compiled.
====
 
[role="_additional-resources"]
.Additional resources
* xref:assessment-questionnaires_assessing-applications[{ProductShortName} assessment questionnaires]
* xref:managing-mta-questionnaires_assessing-applications[Managing assessment questionnaires]

