:_newdoc-version: 2.15.0
:_template-generated: 2024-2-20

:_mod-docs-content-type: REFERENCE

[id="custom-questionnaire-fields_{context}"]
= The custom questionnaire fields

[role="_abstract"]
You can build a custom assessment questionnaire in the {ProductFullName} user interface (UI) by configuring specific fields. These field definitions help you configure questions, answers, and weighting.

Every custom questionnaire field marked as _required_ is mandatory. If you do not define such fields, YAML validation will fail on upload. Each subsection of the field defines a new structure or object in YAML, for example:

[source,yaml]
----
...
name: Testing
thresholds:
    red: 30
    yellow: 45
    unknown: 5
...
----



.The custom questionnaire fields
[options="header"]
|====
|Questionnaire field|Description
|`name` (required, string) |The name of the questionnaire. This field must be unique for the entire {ProductShortName} instance.
|`description` (optional, string)|A short description of the questionnaire.
|`thresholds` (required) a|The definition of a threshold for each application or archetype risk category that the risk level affects. Valid threshold values include the following:

* `red` (required, unsigned integer): The numeric percentage of red answers allowed in the questionnaire before the {ProductShortName} marks the risk level as red, for example, `30` for `30%`.
* `yellow` (required, unsigned integer): The numeric percentage of yellow answers allowed in the questionnaire before the {ProductShortName} marks the risk level as yellow, for example, `30` for `30%`.
* `unknown` (required, unsigned integer): The numeric of unknown answers allowed in the questionnaire before the {ProductShortName} marks the risk level as unknown.

The higher risk level always takes precedence. For example, if you set the `yellow` threshold to 30% and `red` to 5%, and set the answers for the application or archetype to have 35% `yellow` and 6% `red`, the risk level for the application or archetype is red.

|`riskMessages` (required) a| The messages that reports display for each risk category. The following fields define the risk messages map:

* `red` (required, string): A message that reports display for the red risk level.
* `yellow` (required, string): A message that reports display for the yellow risk level.
* `green` (required, string): A message that reports display for the green risk level.
* `unknown` (required, string): A message that reports display for the unknown risk level.
|`sections` (required) a|A list of sections that the questionnaire must include.

* `name` (required, string): A name of the the section.
* `order` (required, integer): An order of the question in the section.
* `comment` (optional, string): A description of the section.
* `questions` (required): A list of questions that belong to the section.
** `order` (required, integer): An order of the question in the section.
** `text` (required, string): A question to include in the questionnaire.
** `explanation` (optional, string): An additional explanation for the question.
** `includeFor` (optional): A list that defines whether the {ProductShortName} displays the question if the application or archetype contains any of the listed tags.
*** `category` (required, string): A category of the target tag.
*** `tag` (required, string): A target tag.
** `excludeFor` (optional): A list that defines whether the {ProductShortName} skips the question if the application or archetype contains any of the listed tags.
*** `category` (required, string): A category of the target tag.
*** `tag` (required, string): A target tag.
** `answers` (required): A list of answers for the given question.
*** `order` (required, integer): An order of the question in the section.
*** `text` (required, string): An answer for the question.
*** `risk` (required): An implied risk level (red, yellow, green, or unknown) of the current answer. 
*** `rationale` (optional, string): A justification for the answer considered a risk.
*** `mitigation` (optional, string): An explanation of the potential mitigation strategy for the risk implied by the answer.
*** `applyTags` (optional): A list of tags that the {ProductShortName} automatically applies to the assessed application or archetype if this answer is selected.
**** `category` (required, string): A category of the target tag.
**** `tag` (required, string): A target tag.
*** `autoAnswerFor` (optional, list): A list of tags that prompt the {ProductShortName} to automatically select this answer when it assesses the application or archetype:
**** `category` (required, string): A category of the target tag.
**** `tag` (required, string): A target tag.
|====


[role="_additional-resources"]
.Additional resources
* xref:yaml-template-for-custom-questionnaire_mta-custom-questionnaire[The YAML template for the custom questionnaire]
