// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_content-type: REFERENCE

[id="cli-tool-known-issues_{context}"]
= {ProductShortName} {CLINameTitle} known issues

[role="_abstract"]
Review the known issues for the {ProductFullName} command-line interface (CLI) to identify existing problems and apply workarounds.


*Limitations with Podman on Microsoft Windows*

The {CLINameTitle} is built and distributed with support for Microsoft Windows.

However, when running any container image based on Red Hat Enterprise Linux 9 (RHEL9) or Universal Base Image 9 (UBI9), the following error can be returned when starting the container:

[subs="+quotes"]
----
Fatal glibc error: CPU does not support x86-64-v2
----

This error is caused because Red Hat Enterprise Linux 9 or Universal Base Image 9 container images must be run on a CPU architecture that supports `x86-64-v2`.

For more details, see link:https://access.redhat.com/solutions/7057314[Running Red Hat Enterprise Linux 9 (RHEL) or Universal Base Image (UBI) 9 container images fail with "Fatal glibc error: CPU does not support x86-64-v2"].

{CLINameTitle} runs the container runtime correctly. However, different container runtime configurations are not supported.

Although unsupported, you can run {CLINameTitle} with *Docker* instead of *Podman*, which would resolve this issue.

To achieve this, you replace the `CONTAINER_TOOL` path with the path to Docker.

For example, if you experience this issue, instead of issuing:

[subs="+quotes"]
----
CONTAINER_TOOL=/usr/local/bin/docker mta-cli analyze
----

You replace `CONTAINER_TOOL` with the path to Docker:

[subs="+quotes"]
----
<Docker Root Dir>=/usr/local/bin/docker mta-cli analyze
----

While this is not supported, it would allow you to explore {CLINameTitle} while you work to upgrade your hardware or move to hardware that supports `x86_64-v2`.
