// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_content-type: CONCEPT
[id="intro-to-the-cli_{context}"]
= Introduction to the {ProductShortName} command-line interface

The {ProductFullName} command-line interface (CLI) provides a comprehensive set of rules to assess the suitability of your applications for containerization and deployment on Red Hat OpenShift. By using the {ProductShortName} CLI, you can assess and prioritize migration and modernization efforts for applications written in different languages. For example, you can use {ProductShortName} to analyze applications written in the following languages:

* Java
* Go
* .NET
* Node.js
* Python

:FeatureName: Analyzing applications written in the .NET language
include::../snippets/developer-preview-admonition.adoc[]

:FeatureName: Analysing applications written in the Python and Node.js languages
include::../snippets/technology-preview-admonition.adoc[]

The CLI provides numerous reports that highlight the analysis without using the other tools. You can use the CLI to customize {ProductShortName} analysis options or integrate with external automation tools.