// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_content-type: CONCEPT
[id="intro-to-the-cli_{context}"]
= Introduction to the {ProductShortName} command-line interface

[role="_abstract"]
The {ProductFullName} command-line interface (CLI) provides a comprehensive set of rules to assess the suitability of your applications for containerization and deployment on Red Hat OpenShift. By using the {ProductShortName} CLI, you can assess and prioritize migration and modernization efforts for applications written in different languages.

{ProductShortName} CLI provides numerous reports that highlight the analysis without using the other tools. You can use {ProductShortName} CLI to customize analysis options or integrate with external automation tools.

You can use {ProductShortName} to analyze applications written in the following languages:

* Java
* Go
* .NET
* Node.js
* Python

:FeatureName: Analyzing applications written in the .NET language

[IMPORTANT]
====
[subs="attributes+"]
{FeatureName} is a Developer Preview feature only. Developer Preview features are not supported by Red Hat in any way and are not functionally complete or production-ready. Do not use Developer Preview features for production or business-critical workloads. Developer Preview features provide early access to upcoming product features in advance of their possible inclusion in a Red Hat product offering, enabling customers to test functionality and provide feedback during the development process. These features might not have any documentation, are subject to change or removal at any time, and testing is limited. Red Hat might provide ways to submit feedback on Developer Preview features without an associated SLA.
====
:!FeatureName:

:FeatureName: Analyzing applications written in the Python and Node.js languages

[IMPORTANT]
====
[subs="attributes+"]
{FeatureName} is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
:!FeatureName:
