// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_mod-docs-content-type: CONCEPT
[id="intro-to-the-cli_{context}"]
= Introduction to the {ProductShortName} command-line interface

[role="_abstract"]
The {ProductFullName} command-line interface (CLI) provides a comprehensive set of rules to assess the suitability of your applications for containerization and deployment on Red Hat OpenShift. By using the {ProductShortName} CLI, you can assess and prioritize migration and modernization efforts for applications written in different languages.

The {ProductShortName} CLI provides numerous reports that highlight the analysis without using the other tools. You can use {ProductShortName} CLI to customize analysis options or integrate with external automation tools.

You can use the {ProductShortName} to analyze applications written in the following languages:

* Java
* Go
* .NET
* Node.js
* Python

:FeatureName: Analyzing applications written in the .NET language

[IMPORTANT]
====
[subs="attributes+"]
{FeatureName} is Developer Preview software only. Developer Preview software is not supported by Red{nbsp}Hat in any way and is not functionally complete or production-ready. Do not use Developer Preview software for production or business-critical workloads. Developer Preview software provides early access to upcoming product software in advance of its possible inclusion in a Red{nbsp}Hat product offering. Customers can use this software to test functionality and provide feedback during the development process. This software might not have any documentation, is subject to change or removal at any time, and has received limited testing. Red{nbsp}Hat might provide ways to submit feedback on Developer Preview software without an associated SLA.

For more information about the support scope of Red{nbsp}Hat Developer Preview software, see link:https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope]
====
:!FeatureName:

:FeatureName: Analyzing applications written in the Python and Node.js languages

[IMPORTANT]
====
[subs="attributes+"]
{FeatureName} is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
:!FeatureName:
