:_newdoc-version: 2.18.3
:_template-generated: 2024-07-30
:_mod-docs-content-type: PROCEDURE

[id="mta-cli-analyze-unsupported-provider_{context}"]
= Analyzing a multi-language application for an unsupported language provider

When analyzing a multi-language application with {ProductFullName} CLI, you can run the analysis for an unsupported language provider. To do so, you must override an existing supported language provider with your own unsupported language provider by using the `--override-provider-settings` option. 

IMPORTANT: You must create a configuration file for your unsupported language provider before overriding the supported provider.


.Prerequisites

* You created a configuration file for your unsupported language provider, for example:
+
----
[
{
"name": "java",
"address": "localhost:14651"
"initConfig": [{
"location": "<java-app-path>",
"providerSpecificConfig": {
"bundles": "<bundle-path>",
"jvmMaxMem": "2G",
},
"analysisMode": "source-only"
}]
}
]
----

.Procedure

* Override an existing supported language provider with your unsupported provider:
+
[literal,subs="+quotes,verbatim,normal,normal"]
....
$ *mta-cli analyze --provider-override _<path_to_configuration_file>_ --output=_<path_to_the_output_directory>_ --rules _<path_to_custom_rules>_*
....