:_newdoc-version: 2.18.3
:_template-generated: 2024-07-25
:_mod-docs-content-type: PROCEDURE

[id="selecting-language-providers-for-analysis_{context}"]
= Analyzing a multi-language application for the selected supported language provider

When analyzing a multi-language application with {ProductFullName} CLI, you can explicitly set a supported language provider according to your application language to run the analysis for.


.Prerequisites

* You are running the latest version of {ProductShortName} CLI.


.Procedure

. List language providers supported for the analysis:
+
[literal,subs="+quotes,verbatim,normal,normal"]
....
$ *mta-cli analyze --list-providers*
....

. Run the application analysis for the selected language provider:
+
[literal,subs="+quotes,verbatim,normal,normal"]
....
$ *mta-cli analyze --input _<path_to_the_source_repository>_ --output _<path_to_the_output_directory>_ --provider _<language_provider>_ --rules _<path_to_custom_rules>_*
....
+
IMPORTANT: If you do not set the `--provider` option, the analysis might fail because it detects unsupported providers. The analysis will complete without `--provider` only if all discovered providers are supported.