// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="generating-discovery-manifest_{context}"]
= Generating a discovery manifest 

You can generate the discovery manifest for the Cloud Foundry (CF) application by using the `discover` command. The discovery manifest preserves configurations, such as application properties, resource allocations, environment variables, and service bindings found in the CF manifest. 

.Prerequisites

* You have Cloud Foundry (v3) as a source platform.
* You installed {ProductShortName} {CLIName} version 7.3.0 or later.

.Procedure

. Open the terminal application and navigate to the `<{ProductShortName}_HOME>/` directory.

. List the supported platforms for the discovery process:
+
[subs="+quotes"]
----
$ *mta-cli discover --list-platforms*
----

. Generate the discovery manifest:
+
[subs="+quotes"]
----
$ *mta-cli discover cloud-foundry --input _<path_to_input>_ --output-dir _<path_to_output-directory>_*
----

[role="_additional-resources"]
.Additional resources

* xref:discover-generate-command-options_generating-assets[The discover and generate command options]
