// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="generating-deployment-manifest_{context}"]
= Generating a deployment manifest 

[role="_abstract"]
To prepare your application for deployment to a container platform, generate a deployment manifest by using the {ProductFullName} command-line interface (CLI). Generating the deployment manifest creates the necessary configuration files to define your application's resources, streamlining the transition to your target environment.

You can auto-generate the {ocp-full} deployment manifest for the Cloud Foundry (CF) application by using the `generate` command. Based on the Helm template that you provide, the command generates manifests, such as a ConfigMap, and non-Kubernetes manifests, such as a Dockerfile, for application deployment. 

.Prerequisites

* You have Cloud Foundry (v3) as a source platform.
* You have {ocp-short} as a target platform. 
* You installed {ProductShortName} {CLIName} version 7.3.0.
* You generated a discovery manifest.
* You created a Helm template with the required configuration for the {ocp} deployment. 


.Procedure

. Open the terminal application and navigate to the `<{ProductShortName}_HOME>/` directory.

. Explore the  `helm_sample` chart directory:
+
[subs="+quotes"]
----
tree _<path_to_helm_chart>_
----
+
[subs="+quotes"]
----
├── Chart.yaml
├── templates
│   ├── configmap.yaml
│   └── files
│       └── konveyor
│           └── Dockerfile
└── values.yaml
----
+
You must save the Kubernetes `YAML` templates (for example, `ConfigMap` or `Deployment`) in the `templates` directory present in the root directory of the `Helm` chart. You must save text-based templates (for example, `Dockerfile`) in the _files/konveyor_ path in the `templates` directory.
+
When you generate generate the deployment manifest after generating the discovery manifest, the values in the `values.yaml` file override the values in the discovery manifest. If the `values` file is empty, {ProductShortName} considers the discovery manifest configuration as input to generate the deployment manifest. 

. Explore the discovery manifest configuration:
+
[subs="+quotes"]
----
cat _<path_to_discovery_manifest>_
----
+
[subs="+quotes"]
----
manifest:
    name: my-app
    labels:
        sensitive: "true"
    annotations:
        contact: bob@example.com jane@example.com
    env:
        RACK_ENV: production
        RAILS_ENV: production
    routes:
        - route: example.com
          protocol: http2
    processes:
        - type: web
          disk: 1024M
          memory: 512M
          healthCheck:
            invocationTimeout: 1
            interval: 30
            type: port
            timeout: 80
          readinessCheck:
            type: process
          instances: 1
          lifecycle: cnb
    stack: cflinuxfs4
    buildPacks:
        - docker://my-registry-a.corp/nodejs
        - docker://my-registry-b.corp/dynatrace
----
+
NOTE: You must configure the buildpacks in the Cloud Foundry application manifest to include the buildpacks in the discovery and deployment assets.
+
. Generate the deployment manifest as an output file:
+
[subs="+quotes"]
----
$ *mta-cli generate helm --chart-dir helm_sample \
--input _<path_to_discovery-manifest>_ \
--output-dir _<location_of_deployment_manifest>_ \*
----

. Verify the ConfigMap:
+
[subs="+quotes"]
----
$ *cd _<location_of_config_map>_ \*
$ *cat configmap.yaml*
----
. Verify the Dockerfile:
+
[subs="+quotes"]
----
$ *cd _<location_of_deployment_manifest>_ \*
$ *cat files/konveyor/Dockerfile*
----

[role="_additional-resources"]
.Additional resources

* xref:discover-generate-command-options_generating-assets[The discover and generate command options]
* link:https://github.com/konveyor/enhancements/tree/master/enhancements/assets-generation/cloud-foundry-application-discovery#app-level-configuration[CloudFoundry application schema fields for manifests]