:_newdoc-version: 2.18.3
:_template-generated: 2024-07-25
:_mod-docs-content-type: PROCEDURE

[id="analyze-selected-provider_{context}"]
= Analyzing an application for the selected supported language provider

[role="_abstract"]
To assess the effort required to migrate non-Java applications, analyze your source code by using the {ProductFullName} command-line interface (CLI). 

You can select a language provider to analyze from the list of supported providers. The analysis generates a report containing the details of the application migration effort, including potential migration issues. You can use the report to prioritize tasks and estimate the resources needed for the migration.


.Prerequisites

* You have the latest version of {ProductShortName} CLI installed on your system. 


.Procedure

. List language providers supported for the analysis:
+
[subs="+quotes"]
....
$ *mta-cli analyze --list-providers*
....

. Run the application analysis for the selected language provider: 
+
[subs="+quotes"]
....
$ *mta-cli analyze --input _<path_to_input>_ --output _<path_to_output>_ --provider _<language_provider>_ --rules _<path_to_custom_rules>_*
....
+
IMPORTANT: Note that if you do not set the `--provider` option, the analysis might fail because it detects unsupported providers. The analysis will complete without `--provider` only if all discovered providers are supported. 