:_newdoc-version: 2.18.3
:_template-generated: 2025-03-17
:_mod-docs-content-type: PROCEDURE

[id="analyzing-multiple-apps-with-mta-cli_{context}"]
= Analyzing multiple applications

[role="_abstract"]
To efficiently assess the migration effort for a portfolio of applications, you can analyze multiple applications simultaneously by using the {ProductFullName} command-line interface (CLI). This bulk analysis generates reports for all specified applications. You can use the reports to identify issues and prioritize tasks for large-scale migration projects.

:FeatureName: Analyzing multiple applications

[IMPORTANT]
====
[subs="attributes+"]
{FeatureName} is a Developer Preview feature only. Developer Preview features are not supported by Red Hat in any way and are not functionally complete or production-ready. Do not use Developer Preview features for production or business-critical workloads. Developer Preview features provide early access to upcoming product features in advance of their possible inclusion in a Red Hat product offering, enabling customers to test functionality and provide feedback during the development process. These features might not have any documentation, are subject to change or removal at any time, and testing is limited. Red Hat might provide ways to submit feedback on Developer Preview features without an associated SLA.
====
:!FeatureName:

.Procedure

. Run the analysis for multiple applications.
+
IMPORTANT: You must enter one input per analyze command, but make sure to enter the same output directory for all inputs.
+
For example, to analyze example applications `A`, `B`, and `C`, enter the following commands:

.. For input `A`, enter:
+
[subs="+quotes"]
....
$ *mta-cli analyze --bulk --input _<path_to_input_A>_ --output _<path_to_output_ABC>_ --source _<source_A>_ --target _<target_A>_*
....

.. For input `B`, enter:
+
[subs="+quotes"]
....
$ *mta-cli analyze --bulk --input _<path_to_input_B>_ --output _<path_to_output_ABC>_  --source _<source_B>_ --target _<target_B>_*
....

.. For input `C`, enter:
+
[subs="+quotes"]
....
$ *mta-cli analyze --bulk --input _<path_to_input_C>_ --output _<path_to_output_ABC>_  --source _<source_C>_ --target _<target_C>_*
....

. Access the analysis report. {ProductShortName} generates a single report, listing all issues that must be resolved before the applications can be migrated.

[role="_additional-resources"]
.Additional resources

* link:{mta-URL}/installing_the_migration_toolkit_for_applications/index#installing-cli-zip_installing-mta-cli[Installing the CLI by using a .zip file]
* xref:mta-cli-analyze-flags_analyzing-applications-mta-cli[The mta-cli analyze command options]
