// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_content-type: PROCEDURE
[id="installing-mta-disconnected-environment_{context}"]
= Installing the CLI on a disconnected environment

When your system is in a disconnected environment, you can install the {ProductFullName} command-line interface (CLI) by using an external computer to download the required images and by copying these images to the system you want to install {ProductShortName} CLI on.

IMPORTANT: The following procedure applies only to container mode.

NOTE: The analysis output in the disconnected environment usually results in less incidents because a dependency analysis does not run accurately without access to Maven.

.Prerequisites

* You downloaded the required {ProductShortName} CLI binary from {ProductName} Red Hat Developer page.
* You installed the Podman tool on your system.
* For the analysis of Java applications, you enabled container runtime usage by setting the `--run-local` flag to `false`: 
+
----
--run-local=false
----
+
The analysis of non-Java applications runs in container mode by default.


.Procedure

. On a connected device, perform the following steps:

.. Authenticate to registry.redhat.io:
+
[subs="+quotes"]
----
$ *podman login registry.redhat.io*
----

.. Run the `mta-cli` binary file. The binary file pulls the required provider images. For example:
+
[subs="+quotes"]
----
$ *mta-cli analyze*
----
+
IMPORTANT: This command only pulls the required images. For example, if you  run a command that requires Java images, a .NET image will not be pulled.

.. Display the image list:
+
[subs="+quotes"]
----

$ *podman images*
REPOSITORY                                                        TAG         IMAGE ID      CREATED       SIZE
registry.redhat.io/mta/mta-generic-external-provider-rhel9        7.3.1       8b8d7fa14570  13 days ago   692 MB
registry.redhat.io/mta/mta-cli-rhel9                              7.3.1       45422a12d936  13 days ago   1.6 GB
registry.redhat.io/mta/mta-java-external-provider-rhel9           7.3.1       4d6d0912a38b  13 days ago   715 MB
registry.redhat.io/mta/mta-dotnet-external-provider-rhel9         7.3.1       66ec9fc51408  13 days ago   1.27 GB
----

.. Save the images:
+
[subs="+quotes"]
----
$ *podman save _<image_ID>_ -o _<image_name>_.image*
----

.. Copy the images onto a USB drive or directly to the file system of the disconnected device. 

. On the disconnected device, enter:
+
[subs="+quotes"]
----
$ *podman load --input _<image_name>_.image*
----
