// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="generating-deployment-manifest_{context}"]
= Generating deployment manifests 

[role="_abstract"]
To prepare your application for deployment to a container platform, generate deployment manifests by using the {ProductFullName} command-line interface (CLI). Generating the deployment manifests creates the necessary configuration files to define your application's resources, streamlining the transition to your target environment.

You can auto-generate the {ocp-full} deployment manifests for the Cloud Foundry (CF) application by using the `generate` command. Based on the `Helm` template that you provide, the command generates manifests, such as a `ConfigMap`, and non-Kubernetes manifests, such as a `Dockerfile`, for application deployment. 

.Prerequisites

* You have Cloud Foundry (v3) as a source platform.
* You have {ocp-short} as a target platform. 
* You installed {ProductShortName} {CLIName} version 7.3.0.
* You generated a discovery manifest.
* You created a Helm template with the required configuration for the {ocp} deployment. 


.Procedure

. Open the terminal application and navigate to the `<{ProductShortName}_HOME>/` directory.

. Explore the root directory of the `Helm` chart:
+
[subs="+quotes"]
----
tree _<path_to_helm_chart>_
----
+
[subs="+quotes"]
----
├── Chart.yaml
├── files
│   └── konveyor
│       └── Dockerfile
├── templates
│   └── configmap.yaml
└── values.yaml

----
+
You must save the Kubernetes `YAML` templates, for example, `ConfigMap` or `Deployment`, in the `templates` directory present in the root directory of the `Helm` chart. You must save non-Kubernetes templates, for example, `Dockerfile`, in the `files/konveyor` path in the `Helm` chart root directory.
+
NOTE: See xref:values-deployment_generating-assets[Generating deployment manifests from discovery manifest and values.yaml] for information about the values that {ProductShortName} takes as inputs to generate the deployment manifests.

. Generate the deployment manifests in an output directory:
+
[subs="+quotes"]
----
$ *mta-cli generate helm --chart-dir helm_sample \*
*--input _<path_to_discovery-manifest>_ \*
*--output-dir _<location_of_deployment_manifest>_*
----

. Verify the ConfigMap:
+
[subs="+quotes"]
----
$ *cd _<location_of_config_map>_ \*
$ *cat configmap.yaml*
----
. Verify the Dockerfile:
+
[subs="+quotes"]
----
$ *cd _<location_of_deployment_manifest>_ \*
$ *cat files/konveyor/Dockerfile*
----

[role="_additional-resources"]
.Additional resources

* xref:discover-generate-command-options_generating-assets[The discover and generate command options]
