:_newdoc-version: 2.18.3
:_template-generated: 2024-07-30
:_mod-docs-content-type: PROCEDURE

[id="analyze-unsupported-provider_{context}"]
= Analyzing an application for an unsupported language provider

[role="_abstract"]To estimate the migration effort for applications built with technologies not natively supported by the {ProductFullName} command-line interface, analyze the source code. The analysis generates a report containing the details of the application migration effort, including potential migration…

To run the analysis for an unsupported language provider, you must overwrite the existing supported language provider with your own unsupported language provider.  	 

IMPORTANT: You must create a configuration file for your unsupported language provider before overriding the supported provider. 


.Prerequisites

* You created a configuration file for your unsupported language provider, for example:
+
....
[
{
"name": "java",
"address": "localhost:14651"
"initConfig": [{
"location": "<java-app-path>",
"providerSpecificConfig": {
"bundles": "<bundle-path>",
"jvmMaxMem": "2G",
},
"analysisMode": "source-only"
}]
}
]
....

.Procedure

* Override an existing supported language provider with your unsupported provider and run the analysis:
+
[subs="+quotes"]
....
$ *mta-cli analyze --provider-override _<path_to_configuration_file>_ --output _<path_to_output>_ --rules _<path_to_custom_rules>_*
....