:_newdoc-version: 2.18.3
:_template-generated: 2025-03-14
:_mod-docs-content-type: PROCEDURE

[id="installing-cli-zip_{context}"]
= Installing the CLI by using a .zip file

You can install the {ProductFullName} command-line interface (CLI) by using the downloadable `.zip` file available at the link:https://developers.redhat.com/products/mta/download[official {ProductShortName} download page].


.Prerequisites

* Red Hat Container Registry Authentication for `registry.redhat.io`. Red Hat distributes container images from `registry.redhat.io`, which requires authentication. For more details, see link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication].
+
NOTE: This prerequisite is not applicable for the containerless mode. For more information, see xref:running-the-containerless-mta-cli_analyzing-applications-mta-cli[Analyzing applications in the containerless mode]. 

* You installed Java Development Kit (JDK) version 17 or later.
* You set the `JAVA_HOME` environmental variable. 
* You installed Maven version 3.9.9 or later with its binary added to the `$PATH` variable.



.Procedure

. Navigate to the link:{DevDownloadPageURL}[{ProductShortName} download page] and download one of the following operating system specific CLI file or the `src` file:
+
* {ProductShortNameLower}-{ProductVersion}-cli-linux.zip
* {ProductShortNameLower}-{ProductVersion}-cli-macos.zip
* {ProductShortNameLower}-{ProductVersion}-cli-windows.zip
* {ProductShortNameLower}-{ProductVersion}-cli-src.zip

. Extract the `.zip` file. `.zip` extracts the `mta-cli` binary, along with other required directories and files.

. Move the `mta-cli` binary to your `$PATH` variable.
+
NOTE: You can place the `mta-cli` binary in any folder that is included into the `$PATH` variable. Alternatively, you can add a folder that contains `mta-cli` to `$PATH`. This way, you do not need to specify a full path when using the CLI.
