:_newdoc-version: 2.18.3
:_template-generated: 2024-11-15
:_mod-docs-content-type: PROCEDURE

[id="running-the-containerless-mta-cli_{context}"]
= Analyzing an application in containerless mode

[role="_abstract"]
By default, the {ProductFullName} command-line interface (CLI) runs in containerless mode. In this mode, the CLI uses the provided shell script to run assessments directly on your local machine, and it does not require Podman or Docker.

[NOTE]
====
Containerless mode is the default for Java application analysis. To use a container runtime instead, set the `--run-local` parameter to `false`:

----
--run-local=false
----

For applications that are written in languages other than Java, the analysis automatically runs in container mode.
====

.Prerequisites

* You installed the {ProductShortName} CLI.
* You installed Java Development Kit (JDK) version 17 or later.
* If you use OpenJDK on Red Hat Enterprise Linux (RHEL) or Fedora, you installed the Java `devel` package.
* You installed Maven version 3.9.9 or later.
* The CLI assumes that a path to the `mvn` binary is correctly registered in the system variable. Therefore, ensure that you added `mvn` to the following variable:
** `Path` for Windows.
** `PATH` for Linux and macOS.
* You set the `JAVA_HOME` environment variable.
* You set the `JVM_MAX_MEM` system variable.
+
NOTE: If you do not set `JVM_MAX_MEM`, the analysis might hang because Java might require more memory than the default `JVM_MAX_MEM` value.
* For Gradle analysis, you completed the following steps:
** You installed OpenJDK version 8.
** You set `$JAVA8_HOME` and it is pointing to the OpenJDK 8 home directory.
** Your project has a Gradle Wrapper.

.Procedure

. Optional: Display all `mta-cli analyze` command options:
+
[subs="+quotes"]
....
$ mta-cli analyze --help
....

. Run the application analysis:
+
[subs="+quotes"]
....
$ mta-cli analyze --overwrite --input _<path_to_input>_  --output _<path_to_output>_ --target _<target_source>_
....
+
NOTE: The `--overwrite` option overwrites the output folder if it exists.


[role="_additional-resources"]
.Additional resources

* xref:installing-cli-zip_installing-mta-cli[Installing the CLI by using a .zip file]
* xref:mta-cli-analyze-flags_analyzing-applications-mta-cli[The mta-cli analyze command options]
* link:https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper]
