:_newdoc-version: 2.18.3
:_template-generated: 2025-05-28

:_mod-docs-content-type: PROCEDURE

[id="discover-values-deployment_{context}"]
= Generating deployment manifests from discovery manifest and values.yaml

[role="_abstract"]
You can generate deployment manifests from a discovery manifest with a `values.yaml` file. When you generate the deployment manifest from the discovery manifest, the values in the `values.yaml` file override the values in the discovery manifest. If the `values` file is empty or missing, {ProductShortName} uses the discovery manifest values as input to generate the deployment manifest. 

You must save the Kubernetes `YAML` templates, for example, `ConfigMap` or `Deployment`, in the `templates` directory present in the root directory of the `Helm` chart. You must save non-Kubernetes templates, for example, `Dockerfile`, in the `files/konveyor` path in the `Helm` chart root directory.

* Show the content of the discovery manifest:
+
[source, terminal]
----
$ *cat _<path_to_discovery_manifest>_*
----
+
[source, yaml]
----
manifest:
    appName: my-app
    database:
        enabled: true
        host: postgres.example.com
    labels:
        sensitive: "true"
    annotations:
        contact: bob@example.com jane@example.com
    env:
        RACK_ENV: production
        RAILS_ENV: production
    routes:
        - route: example.com
          protocol: http2
    processes:
        - type: web
          disk: 1024M
          memory: 512M
          healthCheck:
            invocationTimeout: 1
            interval: 30
            type: port
            timeout: 80
          readinessCheck:
            type: process
          instances: 1
          lifecycle: cnb
    stack: cflinuxfs4
    buildPacks:
        - docker://my-registry-a.corp/nodejs
        - docker://my-registry-b.corp/dynatrace
----
+
NOTE: You must configure the buildpacks in the Cloud Foundry application manifest to include the buildpacks in the discovery and deployment assets.

* Display `values.yaml` file that has database host and URL:
+
[source, terminal]
----
$ *cat _<path_to_values.yaml>_*
----
+
+
[source, yaml]
----
appName: my-app-production  # Overrides application name 
  database:
    host: prod-postgres.company.com   # Overrides host value 
  redis:                             # Adds a new field 
    url: redis://prod-redis:6379
----
+
NOTE: The discovery manifest does not contain the value.yaml fields.

* Display the content of the `Dockerfile` template :
+
[source, terminal]
----
$ *cat _<path_to_dockerfile_template>_*
----
+
[subs="+quotes"]
----
FROM node:18

ENV APP_NAME={{ .Values.appName }}
{{- if .Values.database.enabled }}
ENV DATABASE_HOST={{ .Values.database.host }}
{{- end }}
{{- if .Values.redis }}
ENV REDIS_URL={{ .Values.redis.url }}
{{- end }}
----
. Generate the deployment assets by using the following command:
+
[source, terminal]
----
$ *mta-cli generate helm --chart-dir helm_sample* \
  *--input <path_to_discovery-manifest>* \
  *--output-dir <location_of_deployment_manifest>*
----

.Verification

* Verify that the rendered `Dockerfile` has the fields from the `values.yaml` file:
+
[source, terminal]
----
$ *cat _<path_to_dockerfile>_*
----
+
[source, yaml]
----
FROM node:18

  ENV APP_NAME=my-app-production
  ENV DATABASE_HOST=prod-postgres.company.com
  ENV REDIS_URL=redis://prod-redis:6379
----
