:_newdoc-version: 2.18.3
:_template-generated: 2025-03-17
:_mod-docs-content-type: PROCEDURE

[id="analyzing-multiple-apps-with-mta-cli_{context}"]
= Analyzing multiple applications

[role="_abstract"]
To efficiently assess the migration effort for a portfolio of applications, you can analyze multiple applications simultaneously by using the {ProductFullName} command-line interface (CLI). This bulk analysis generates reports for all specified applications. You can use the reports to identify issues and prioritize tasks for large-scale migration projects.

:FeatureName: Analyzing multiple applications

[IMPORTANT]
====
[subs="attributes+"]
{FeatureName} is Developer Preview software only. Developer Preview software is not supported by Red{nbsp}Hat in any way and is not functionally complete or production-ready. Do not use Developer Preview software for production or business-critical workloads. Developer Preview software provides early access to upcoming product software in advance of its possible inclusion in a Red{nbsp}Hat product offering. Customers can use this software to test functionality and provide feedback during the development process. This software might not have any documentation, is subject to change or removal at any time, and has received limited testing. Red{nbsp}Hat might provide ways to submit feedback on Developer Preview software without an associated SLA.

For more information about the support scope of Red{nbsp}Hat Developer Preview software, see link:https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope].
====
:!FeatureName:

.Procedure

. Run the analysis for multiple applications.
+
IMPORTANT: You must enter one input per analyze command, but make sure to enter the same output directory for all inputs.
+
For example, to analyze example applications `A`, `B`, and `C`, enter the following commands:

.. For input `A`, enter:
+
[subs="+quotes"]
....
$ *mta-cli analyze --bulk --input _<path_to_input_A>_ --output _<path_to_output_ABC>_ --source _<source_A>_ --target _<target_A>_*
....

.. For input `B`, enter:
+
[subs="+quotes"]
....
$ *mta-cli analyze --bulk --input _<path_to_input_B>_ --output _<path_to_output_ABC>_  --source _<source_B>_ --target _<target_B>_*
....

.. For input `C`, enter:
+
[subs="+quotes"]
....
$ *mta-cli analyze --bulk --input _<path_to_input_C>_ --output _<path_to_output_ABC>_  --source _<source_C>_ --target _<target_C>_*
....

. Access the analysis report. {ProductShortName} generates a single report, listing all issues that must be resolved before the applications can be migrated.

[role="_additional-resources"]
.Additional resources

* link:{mta-URL}/installing_the_migration_toolkit_for_applications/index#installing-cli-zip_installing-mta-cli[Installing the CLI by using a .zip file]
* xref:mta-cli-analyze-flags_analyzing-applications-mta-cli[The mta-cli analyze command options]
