:_newdoc-version: 2.18.5
:_template-generated: 2025-06-18
:_mod-docs-content-type: REFERENCE

[id="analysis-report-sections_{context}"]
= Analysis report sections

[role="_abstract"]
The {ProductFullName} command-line interface (CLI) analysis report includes distinct sections that organize the report details by severity, technology, and application details. Check the following table to understand the purpose of each report section to help you navigate the report and interpret specific migration data.

NOTE: You can only review the report applicable to the current application.

:FeatureName: Insights
include::../snippets/technology-preview-admonition.adoc[]

.Analysis report sections
[options="header"]
|====
|Section|Description
|Dashboard|An overview of the incidents and total story points, sorted by category.
|Issues|A concise summary of all issues and their details that require attention.
|Dependencies|All Java-packaged dependencies found within the application. 
|Technologies|All embedded libraries grouped by functionality. Use this report to display the technologies used in each application. 
|Insights|Information about a violation generated by a rule with zero effort. Issues are generated by general rules, whereas string tags are generated by the tagging rules. String tags indicate the presence of a technology but do not show the code location. Insights contain information about the technologies used in the application and their usage in the code.

Insights do not impact the migration. For example, a rule searching for deprecated API usage in the code that does not impact the current migration but can be tracked and fixed when needed in the future. 		

Unlike with issues, you do not need to fix insights for a successful migration. They are generated by any rule that does not have a positive effort value and category assigned. They might have a message and tag.
|====


