:_newdoc-version: 2.18.3
:_template-generated: 2025-05-28

:_mod-docs-content-type: REFERENCE

[id="assets-generation-example_{context}"]
= Assets generation example

The following is an example of generating discovery and deployment manifests of a Cloud Foundry (CF) Node.js application.

For this example, the following files and directories are used:

* CF Node.js application manifest name: `cf-nodejs-app.yaml`
* Discovery manifest name: `discover.yaml`
* Location of the application Helm chart: `helm_sample`
* Deployment manifests: a ConfigMap and a Dockerfile
* Output location of the deployment manifests: `newDir`

Assumed that the `cf-nodejs-app.yaml` is located in the same directory as the {ProductShortName} {CLIName} binary. If the CF application manifest location is different, you can also enter the location path to the manifest as the `input`.

.Prerequisites

* You installed {ProductShortName} {CLIName} 7.3.0.
* You have a CF application manifest as a YAML file. 
* You created a Helm template with the required configurations for the {ocp} deployment. 

.Procedure

. Open the terminal application and navigate to the `<{ProductShortName}_HOME>/` directory.

. Verify the content of the CF Node.js application manifest:
+
[subs="+quotes"]
----
$ *cat cf-nodejs-app.yaml*
name: cf-nodejs
lifecycle: cnb
buildpacks:
  - docker://my-registry-a.corp/nodejs
  - docker://my-registry-b.corp/dynatrace
memory: 512M
instances: 1
random-route: true
----

. Generate the discovery manifest:
+
[subs="+quotes"]
----
$ *mta-cli discover cloud-foundry \
--input cf-nodejs-app.yaml \
--output discover.yaml \*
----

. Verify the content of the discover manifest:
+
[subs="+quotes"]
----
$ *cat discover.yaml*
name: cf-nodejs
randomRoute: true
timeout: 60
buildPacks:
- docker://my-registry-a.corp/nodejs
- docker://my-registry-b.corp/dynatrace
instances: 1
----

. Generate the deployment manifest in the `newDir` directory by using the `discover.yaml` file:
+
[subs="+quotes"]
----
$ *mta-cli generate helm \
--chart-dir helm_sample \
--input discover.yaml --output-dir newDir*
----

. Check the contents of the Dockerfile in the `newDir` directory:
+
[subs="+quotes"]
----
$ *cat ./newDir/Dockerfile*
FROM busybox:latest

RUN echo "Hello cf-nodejs!"
----

. Check the contents of the ConfigMap in the `newDir` directory:
+
[subs="+quotes"]
----
$ *cat ./newDir/configmap.yaml*
apiVersion: v1
kind: ConfigMap
metadata:
  name: cf-nodejs-config
data:
  RANDOM_ROUTE: true
  TIMEOUT: "60"
  BUILD_PACKS: |
    - docker://my-registry-a.corp/nodejs
    - docker://my-registry-b.corp/dynatrace
  INSTANCES: "1"
----

. In the ConfigMap, override the `name` to `nodejs-app` and `INSTANCES` to `2` :
+
[subs="+quotes"]
----
$ *mta-cli generate helm \
--chart-dir helm_sample \
--input discover.yaml --set name="nodejs-app" \
--set instances=2 \
--output-dir newDir \*
----

. Check the contents of the ConfigMap again:
+
[subs="+quotes"]
----
$ *cat ./newDir/configmap.yaml*
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-app
data:
  RANDOM_ROUTE: true
  TIMEOUT: "60"
  BUILD_PACKS: |
    - docker://my-registry-a.corp/nodejs
    - docker://my-registry-b.corp/dynatrace
  INSTANCES: "2"
----

[role="_additional-resources"]
.Additional resources

* xref:discover-generate-command-options_generating-assets[The discover and generate command options]
