:_newdoc-version: 2.18.3
:_template-generated: 2025-05-28

:_mod-docs-content-type: REFERENCE

[id="migration-tasks-categories_{context}"]
= Migration tasks categories

[role="_abstract"]
View the {ProductFullName} migration task categories that you can use to indicate the severity of a migration task. Understanding these categories helps you prioritize migration tasks based on their criticality and estimated effort.

{ProductFirstRef} uses the following categories to group issues to help prioritize the migration effort:

Mandatory:: The task must be completed for a successful migration. If the changes are not made, the resulting application will not build or run successfully. Examples include replacement of proprietary APIs that are not supported in the target platform.

Optional:: If the migration task is not completed, the application should work, but the results might not be optimal. If the change is not made at the time of migration, it is recommended to put it on the schedule soon after your migration is completed.
//An example of this would be the upgrade of EJB 2.x code to EJB 3.

Potential:: The task should be examined during the migration process, but there is not enough detailed information to determine if the task is mandatory for the migration to succeed. An example of this would be migrating a third-party proprietary type where there is no directly compatible type.

Information:: The task is included to inform you of the existence of certain files. These might need to be examined or modified as part of the modernization effort, but changes are typically not required.
//An example of this would be the presence of a logging dependency or a Maven `pom.xml`.
