:_newdoc-version: 2.18.3
:_template-generated: 2025-05-28

:_mod-docs-content-type: REFERENCE

[id="tips-for-performance-optimization_{context}"]
= Tips for {ProductShortName} performance optimization

{ProductFullName} performance depends on a number of factors, including hardware configuration, the number and types of files in the application, the size and number of applications to be evaluated, and whether the application contains source or compiled code. For example, a file that is larger than 10 MB might need a lot of time to process.

{ProductShortName} spends about 40% of the time decompiling classes, 40% of the time executing rules, and the remainder of the time processing other tasks and generating reports. To improve the performance of {ProductShortName}, you can perform the following actions:

* If possible, run {ProductShortName} against the source code instead of the archives. This eliminates the need to decompile additional JARs and archives.
* Increase your `ulimit` when analyzing large applications. For more information, see the link:https://access.redhat.com/solutions/60746[How to increase number of open files limit in Red Hat Enterprise Linux?] Knowledgebase article.
* If you have access to a server that has better resources than your laptop or desktop machine, consider running {ProductShortName} on that server.

If these application and command-line suggestions do not improve performance, you might need to upgrade your hardware:

* If you have access to a server that has better resources than your laptop or desktop, consider running {ProductShortName} on that server.
* Very large applications that require decompilation have large memory requirements. 8 GB RAM is recommended. This allows 3-4 GB RAM for use by the JVM.
* An upgrade from a single or dual-core to a quad-core CPU processor provides better performance.
* Disk space and fragmentation can impact performance. A fast disk, especially a solid-state drive (SSD), with greater than 4 GB of defragmented disk space should improve performance.

