:_newdoc-version: 2.18.5
:_template-generated: 2025-09-12
:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context-of-mta-custom-questionnaire: {context}]

ifndef::context[]
[id="mta-custom-questionnaire"]
endif::[]
ifdef::context[]
[id="mta-custom-questionnaire_{context}"]
endif::[]
= The custom assessment questionnaire

:context: mta-custom-questionnaire

[role="_abstract"]
To determine the readiness of your portfolio for modernization, use a custom assessment questionnaire to provide the {ProductFullName} user interface (UI) with the details required for the migration process.

You can import the custom assessment questionnaire by using a custom YAML syntax to define the questionnaire. The YAML syntax supports the following features:

Conditional questions::
The YAML syntax supports including or excluding questions based on tags existing on the application or archetype, for example:

* If the application or archetype has the `Language/Java` tag, the `What is the main JAVA framework used in your application?` question is included in the questionnaire:
+
[source,yaml]
----
...
  questions:
    - order: 1
      text: What is the main JAVA framework used in your application?
      explanation: Identify the primary JAVA framework used in your application.
      includeFor:
        - category: Language
          tag: Java
...
----

* If the application or archetype has the `Deployment/Serverless` and `Architecture/Monolith` tag, the `Are you currently using any form of container orchestration?` question is excluded from the questionnaire:
+
[source,yaml]
----
...
  questions:
    - order: 4
      text: Are you currently using any form of container orchestration?
      explanation: Determine if the application utilizes container orchestration tools such as Kubernetes or Docker Swarm.
      excludeFor:
        - category: Deployment
          tag: Serverless
        - category: Architecture
          tag: Monolith
...
----

Automated answers based on tags present on the assessed application or archetype::
The {ProductShortName} selects automated answers based on the tags that exist on the application or archetype. For example, if an application or archetype has the `Runtime/Quarkus` tag, the {ProductShortName} automatically selects the `Quarkus` answer. Similarly, if an application or archetype has the `Runtime/Spring Boot` tag, the {ProductShortName} automatically selects the `Spring Boot` answer:
+
[source,yaml]
----
...
  text: What is the main technology in your application?
    explanation: Identify the main framework or technology used in your application.
      answers:
        - order: 1
          text: Quarkus
          risk: green
          autoAnswerFor:
            - category: Runtime
              tag: Quarkus
        - order: 2
          text: Spring Boot
          risk: green
          autoAnswerFor:
            - category: Runtime
              tag: Spring Boot
...
----


Automatic tagging of applications based on answers::
During the assessment, the {ProductShortName} automatically applies tags to the application or archetype based on the answer if this answer is selected. Because these tags are transitive, the {ProductShortName} removes them if you discard the assessment. The following elements define each tag:
+
--
* *category*: Category of the target tag (`String`).
* *tag*: Definition for the target tag as (`String`).
--
+
For example, if the selected answer is `Quarkus`, the {ProductShortName} applies the `Runtime/Quarkus` tag to the assessed application or archetype. If the selected answer is `Spring Boot`, the {ProductShortName} applies the `Runtime/Spring Boot` tag to the assessed application or archetype:
+
[source,yaml]
----
...
questions:
  - order: 1
    text: What is the main technology in your application?
    explanation: Identify the main framework or technology used in your application.
    answers:
      - order: 1
        text: Quarkus
        risk: green
        applyTags:
          - category: Runtime
            tag: Quarkus
      - order: 2
        text: Spring Boot
        risk: green
        applyTags:
          - category: Runtime
            tag: Spring Boot
...
----


include::topics/mta-ui/ref_yaml-template-for-custom-questionnaire.adoc[leveloffset=+1]

include::topics/mta-ui/ref_custom-questionnaire-fields.adoc[leveloffset=+1]


ifdef::parent-context-of-mta-custom-questionnaire[:context: {parent-context-of-mta-custom-questionnaire}]
ifndef::parent-context-of-mta-custom-questionnaire[:!context:]

