:_newdoc-version: 2.18.3
:_template-generated: 2025-03-17

ifdef::context[:parent-context-of-platform-awareness: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="platform-awareness"]
endif::[]
ifdef::context[]
[id="platform-awareness_{context}"]
endif::[]
= Platform awareness in {ProductShortName} {WebName}

:context: platform-awareness

[role="_abstract"]
To import all or selective applications directly from source platform instances, use platform awareness in {ProductFullName} user interface (UI). 

You can associate applications with source platforms in the following ways:

* Manually configure source platforms for applications that are available in {ProductShortName} inventory.

* Discover (import) applications from a source platform instance. 
In this case, the applications are connected with the source platform when they are imported in the {ProductShortName} inventory.

In {ProductShortName} 8.0.0, Red Hat supports Cloud Foundry (CF) as the source platform. 
 
After you import applications, you can retrieve platform and runtime configurations, also known as discovery. Discovery is the process of fetching configurations of the imported applications that are connected to their source platform instances. The retrieval or discovery generates a discovery manifest that contains application configurations.

You can later use the discovery manifest to generate the final set of assets required to deploy the applications in the target platform.

You can perform the following tasks in the {ProductShortName} {WebName}:

. Create multiple source platform (CF) instances. 
. Link an application created in the {ProductShortName} {WebName} to the source platform.
. Fetch the discovery manifest. You can generate the discovery manifests per application or in bulk. 

include::topics/mta-ui/proc_creating-source-platform.adoc[leveloffset=+1]

include::topics/mta-ui/proc_discovering-apps-source-platform-administration-view.adoc[leveloffset=+1]

include::topics/mta-ui/proc_discovering-apps-source-platform-migration-view.adoc[leveloffset=+1]

include::topics/mta-ui/proc_adding-source-platform-application.adoc[leveloffset=+1]

include::topics/mta-ui/proc_generating-discovery-manifest-web.adoc[leveloffset=+1]

ifdef::parent-context-of-platform-awareness[:context: {parent-context-of-platform-awareness}]
ifndef::parent-context-of-platform-awareness[:!context:]