:_newdoc-version: 2.18.5
:_template-generated: 2025-09-12
:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context-of-tagging-applications: {context}]

ifndef::context[]
[id="tagging-applications"]
endif::[]
ifdef::context[]
[id="tagging-applications_{context}"]
endif::[]
= Tagging an application

:context: tagging-applications

[role="_abstract"]
To classify applications and instantly identify application information, for example, an application type, data center location, and technologies used within the application, attach tags to applications in the {ProductFullName} user interface (UI). You can also use tagging to associate xref:working-with-archetypes_user-interface-guide[archetypes] to applications for automatic assessment.

You can either set an xref:automatic-tagging-of-an-application_tagging-applications[automated] tagging or tag applications xref:manual-tagging-of-an-application_tagging-applications[manually]. 			

NOTE: Not all tags can be assigned automatically. For example, an analysis can only tag the application based on its technologies. If you want to tag the application also with the location of the data center where it is deployed, you need to tag the application manually.

include::topics/mta-ui/proc_creating-application-tags.adoc[leveloffset=+1]

include::topics/mta-ui/proc_manual-tagging-of-an-application.adoc[leveloffset=+1]

include::topics/mta-ui/proc_automatic-tagging-of-an-application.adoc[leveloffset=+1]

include::topics/mta-ui/proc_displaying-the-tags-of-an-application.adoc[leveloffset=+1]


ifdef::parent-context-of-tagging-applications[:context: {parent-context-of-tagging-applications}]
ifndef::parent-context-of-tagging-applications[:!context:]

