:_newdoc-version: 2.18.3
:_template-generated: 2025-05-28

ifdef::context[:parent-context-of-asset-generation-ui: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="asset-generation-ui"]
endif::[]
ifdef::context[]
[id="asset-generation-ui_{context}"]
endif::[]
= Generating assets for application deployment in {WebName}

:context: asset-generation-ui

[role="_abstract"]
To create different assets (manifests) required to deploy applications from Cloud Foundry (CF) instances to {ocp-full} or Kubernetes, use asset generation in {ProductShortName} {WebName}.

To generate assets, familiarize yourself with the following entities:

Archetypes::
An archetype contains criteria tags that identify technologies, such as JBoss EAP 6.
+
You can use archetypes to classify applications by their common technologies. For asset generation, you plan migration paths by archetype because you configure the other asset generation entities, such as target profiles that contain the generators, directly within the archetype.

Generators::
A generator uses a templating engine, such as Helm, and a set of templates as its input configuration.
+
When you run an asset generation process, the generator parses the application discovery manifest and uses templates defined for your target platform and migration path to create deployment assets. For example, if you migrate a JBoss EAP 6 application to JBoss EAP 8 on Kubernetes, the generator parses the application's discovery manifest to create the required deployment assets.

Target profiles::
A target profile represents your target migration platform and contains a sequence of generators. 
+
You can use the target profile to run multiple generators simultaneously, where each generator creates assets for a specific migration path. For example, to migrate a JBoss EAP 6 application to both OpenJDK 21 and JBoss EAP 8 on {ocp-short}, you can use a target profile with two generators, one for each migration path.

Application::
The application includes tags, the asset repository, and, optionally, the discovery manifest. If the discovery manifest is unavailable, the generator uses implicit data from the application profile.
+
//provide the retrieve configuration link after publishing the doc
If you want to use the discovery manifest, the configuration retrieval process generates this manifest. The manifest contains the platform and runtime configurations of an application deployed in the source platform (CF) instances. During asset generation, generator templates parse the discovery manifest to create the final deployment assets.
+
The application also contains tags that you must configure as criteria tags in an archetype.  
+
You can find the assets generated for deployment in the target platform in the asset repository. 

include::topics/mta-ui/proc_configuring-generators.adoc[leveloffset=+1]

include::topics/mta-ui/proc_configuring-target-profiles.adoc[leveloffset=+1]

include::topics/mta-ui/proc_configuring-asset-repository.adoc[leveloffset=+1]

include::topics/mta-ui/proc_generating-deployment-assets.adoc[leveloffset=+1]

ifdef::parent-context-of-generating-assets[:context: {parent-context-of-asset-generation-ui}]
ifndef::parent-context-of-asset-generation-ui[:!context:]