:_newdoc-version: 2.18.5
:_template-generated: 2025-09-12
:_mod-docs-content-type: ASSEMBLY
// JTBD job: configure-mta-instance-and-apps
// Statement: When I use the MTA UI, I want to configure the MTA instance, credentials, and repositories so I can analyze and manage applications.
// Persona: Admin


ifdef::context[:parent-context-of-tagging-applications:Configure instance, environment, credentials, repos Manage applications and assessmentst}"]
endif::[]
= Tagging an application

:context: tagging-applications

[role="_abstract"]
Attach tags to applications to classify them, identify technologies, and associate archetypes for automatic assessment.

You can attach various tags to the application that you are analyzing. You can use tags to classify applications and instantly identify application information, for example, an application type, data center location, and technologies used within the application. You can also use tagging to associate archetypes to applications for automatic assessment. For more information about archetypes, see xref:working-with-archetypes_user-interface-guide[Working with archetypes].

Tagging can be done xref:automatic-tagging-of-an-application_tagging-applications[automatically] or xref:manual-tagging-of-an-application_tagging-applications[manually]. 			

NOTE: Not all tags can be assigned automatically. For example, an analysis can only tag the application based on its technologies. If you want to tag the application also with the location of the data center where it is deployed, you need to tag the application manually.

include::topics/mta-ui/proc_creating-application-tags.adoc[leveloffset=+1]

include::topics/mta-ui/proc_manual-tagging-of-an-application.adoc[leveloffset=+1]

include::topics/mta-ui/con_automatic-tagging-of-an-application.adoc[leveloffset=+1]

include::topics/mta-ui/proc_displaying-the-tags-of-an-application.adoc[leveloffset=+1]


ifdef::parent-context-of-tagging-applications[:context: {parent-context-of-tagging-applications}]
ifndef::parent-context-of-tagging-applications[:!context:]

