:_newdoc-version: 2.18.5
:_template-generated: 2025-09-12
:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context-of-assessment-questionnaires: {context}]

ifndef::context[]
[id="assessment-questionnaires"]
endif::[]
ifdef::context[]
[id="assessment-questionnaires_{context}"]
endif::[]
= {ProductShortName} assessment questionnaires

:context: assessment-questionnaires

[role="_abstract"]
To determine the readiness of your portfolio for modernization, use assessment questionnaires to provide the {ProductFullName} user interface (UI) with the details required for the migration process. The {ProductFullName} uses either xref:mta-default-questionnaire_assessment-questionnaires[default] or xref:mta-custom-questionnaire_assessment-questionnaires[custom] assessment questionnaire 

include::topics/mta-ui/con_mta-default-questionnaire.adoc[leveloffset=+1]

include::assembly_mta-custom-questionnaire.adoc[leveloffset=+1]


ifdef::parent-context-of-assessment-questionnaires[:context: {parent-context-of-assessment-questionnaires}]
ifndef::parent-context-of-assessment-questionnaires[:!context:]

