:_newdoc-version: 2.18.5
:_template-generated: 2025-09-12
:_mod-docs-content-type: ASSEMBLY
// JTBD job: configure-mta-instance-and-apps
// Statement: When I use the MTA UI, I want to configure the MTA instance, credentials, and repositories so I can analyze and manage applications.
// Persona: Admin


ifdef::context[:parent-context-of-working-with-archetypes: {context}Configure instance, environment, credentials, repos Manage applications and assessmentspes_{context}"]
endif::[]
= Working with archetypes

:context: working-with-archetypes

[role="_abstract"]
Use archetypes to group applications by common characteristics and assess multiple applications at once.

An *archetype* is a group of applications with common characteristics. You can use archetypes to assess multiple applications at once.

Application archetypes are defined by criteria tags and the application taxonomy. Each archetype defines how the _assessment module_ assesses the application according to the characteristics defined in that archetype. If the tags of an application match the criteria tags of an archetype, the application is associated with the archetype.

Creation of an archetype is defined by a series of *tags*, *stakeholders*, and *stakeholder groups*. The tags include the following types:

* *Criteria tags* are tags that the archetype requires to include an application as a member.
+
NOTE: An application must have all of the archetype's criteria tags to be a member. For example, if the application _a_ only has tag _a_, but the archetype _a_ criteria tags include tags _a_ AND _b_, the application _a_ will not be a member of the archetype _a_.

* *Archetype tags* are tags that are applied to the archetype entity.

NOTE: All applications associated with the archetype inherit the _assessment_ and _review_ from the archetype groups to which these applications belong. This is the default setting. You can override inheritance for the application by completing an individual assessment and review.

include::topics/mta-ui/proc_defining-an-archetype.adoc[leveloffset=+1]

include::topics/mta-ui/proc_assessing-an-archetype.adoc[leveloffset=+1]

include::topics/mta-ui/proc_reviewing-an-archetype.adoc[leveloffset=+1]


ifdef::parent-context-of-working-with-archetypes[:context: {parent-context-of-working-with-archetypes}]
ifndef::parent-context-of-working-with-archetypes[:!context:]

