:_newdoc-version: 2.18.3
:_template-generated: 2025-04-08

ifdef::context[:parent-context-of-run-dev-lightspeed-analysis: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="run-dev-lightspeed-analysis"]
endif::[]
ifdef::context[]
[id="run-dev-lightspeed-analysis_{context}"]
endif::[]
= Running an analysis and resolving issues

:context: run-dev-lightspeed-analysis

[role="_abstract"]
After configuring the {mta-dl-full}, run an analysis to identify the code issues and generate resolution suggestions. 

When you request code fix suggestions, {mta-dl-plugin} performs the following tasks:

* Streams LLM messages that describe the issue, resolution, and the file that {mta-dl-plugin} updates.
* Generates new files in the *Resolutions* pane. These files have the updates to the code to resolve the issues detected in the current analysis. You can review the changes, apply, or revert the updates.

If you apply all the resolutions, {mta-dl-plugin} applies the changes and triggers another analysis to check if there are more issues. Subsequent analysis reports fewer issues and incidents.

include::topics/developer-lightspeed/proc_apply-rag-resolution.adoc[leveloffset=+1]

include::topics/developer-lightspeed/proc_running-agent-analysis.adoc[leveloffset=+1]

ifdef::parent-context-of-run-dev-lightspeed-analysis[:context: {parent-context-of-run-dev-lightspeed-analysis}]
ifndef::parent-context-of-run-dev-lightspeed-analysis[:!context:]

:!run-dev-lightspeed-analysis: