:_newdoc-version: 2.18.3
:_template-generated: 2025-04-08

ifdef::context[:parent-context-of-run-dev-lightspeed-analysis: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="run-dev-lightspeed-analysis"]
endif::[]
ifdef::context[]
[id="run-dev-lightspeed-analysis_{context}"]
endif::[]
= Generating and resolving issues 

:context: run-dev-lightspeed-analysis

After you complete the configurations, the next step is running an analysis to identify the issues in the code and generate suggestions to address the issues. You can run an analysis by using {mta-dl-plugin} in the solution server mode or in the agent mode.

When you run an analysis using either mode, {mta-dl-plugin} automatically performs the following tasks: 

* Displays issues in all the files in your project in the *Issues* pane.
* While generating suggestions to resolve issues, you can view the migration hints that explain the resolution and in which files the updates are applied.
* Generates new files in *Resolutions* pane. These files have the updates to the code that resolves the issues detected in the current analysis. You can review the changes, apply, or revert the updates. 

If you apply all the resolutions, {mta-dl-plugin} applies the changes and triggers another analysis to check if there are more issues.
 
include::topics/developer-lightspeed/proc_running-rag-analysis.adoc[leveloffset=+1]

include::topics/developer-lightspeed/proc_apply-rag-resolution.adoc[leveloffset=+1]

include::topics/developer-lightspeed/proc_running-agent-analysis.adoc[leveloffset=+1]

ifdef::parent-context-of-run-dev-lightspeed-analysis[:context: {parent-context-of-run-dev-lightspeed-analysis}]
ifndef::parent-context-of-run-dev-lightspeed-analysis[:!context:]

