:_newdoc-version: 2.18.3
:_template-generated: 2025-04-08

ifdef::context[:parent-context-of-run-dev-lightspeed-analysis: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="run-dev-lightspeed-analysis"]
endif::[]
ifdef::context[]
[id="run-dev-lightspeed-analysis_{context}"]
endif::[]
= Running an analysis and resolving issues 

:context: run-dev-lightspeed-analysis

After you complete the configurations, the next step is running an analysis to identify the issues in the code and generate suggestions to resolve the issues. You can get suggestions to fix code by using {mta-dl-full}.

When you run an analysis, {ProductShortName} displays the issues in the *Analysis Results* view.

When you request code fix suggestions, {mta-dl-plugin} performs the following tasks: 

* Streams LLM messages that describe the issue description, resolution, and the file in which the updates are applied.
* Generates new files in the *Resolutions* pane. These files have the updates to the code to resolve the issues detected in the current analysis. You can review the changes, apply, or revert the updates. 

If you apply all the resolutions, {mta-dl-plugin} applies the changes and triggers another analysis to check if there are more issues. Subsequent analysis reports fewer issues and incidents.
 
include::topics/developer-lightspeed/proc_running-rag-analysis.adoc[leveloffset=+1]

include::topics/developer-lightspeed/proc_apply-rag-resolution.adoc[leveloffset=+1]

include::topics/developer-lightspeed/proc_running-agent-analysis.adoc[leveloffset=+1]

ifdef::parent-context-of-run-dev-lightspeed-analysis[:context: {parent-context-of-run-dev-lightspeed-analysis}]
ifndef::parent-context-of-run-dev-lightspeed-analysis[:!context:]

