:_mod-docs-content-type: PROCEDURE
[id="installing-vscode-extension_{context}"]
= Installing the {ProductShortName} extension for Visual Studio Code

[role="_abstract"]
You can use the {ProductFullName} Visual Studio Code plugin to perform a standard application analysis.  

You can download the {ProductShortName} plugin version 8.1.0 as an extension pack that bundles the Core extension along with all the supported language-specific extension. You can use this extension even when you want to analyze a project in a specific programming language.

Alternatively, you can also download the {ProductShortName} Core extension and one language-specific extension to analyze a project coded in the programming language supported by the extension.

You can also enable Red Hat Developer Lightspeed for the {ProductName} to use Generative AI (GenAI) capabilities to fix code issues before migrating to target technologies. Note that Developer Lightspeed for {ProductShortName} is enabled by default. For more information, see link:{mta-URL}/configuring_and_using_red_hat_developer_lightspeed_for_mta/index[Configuring and using Developer Lightspeed for {ProductShortName}].

.Prerequisites 

* You installed the Java Development Kit (JDK). {ProductShortName} supports the following JDKs:

** Oracle JDK 17 or later
** Eclipse Temurin™ JDK 17 or later
** OpenJDK 17 or later

* You have 8 GB of RAM available.

* For macOS installation, you have the value of `maxproc` set to `2048` or greater.

.Procedure

* Install the {ProductShortName} {ProductVersion} Visual Studio (VS) Code plugin extension pack from the link:https://marketplace.visualstudio.com/items?itemName=konveyor.konveyor[VS Code marketplace]. 
* Alternatively, install the {ProductShortName} 8.1.0 Core plugin along with the {ProductShortName} extension for a supported language from the link:https://marketplace.visualstudio.com/search?term=konveyor&target=VSCode&category=All%20categories&sortBy=Relevance[VS Code marketplace]
