:_mod-docs-content-type: PROCEDURE
[id="installing-vscode-extension_{context}"]
= Installing the {ProductShortName} extension for Visual Studio Code

[role="_abstract"]
Install the {ProductFullName} extension pack or the {ProductShortName} Core extension with a language-specific extension to perform an application analysis. Use the extension pack to analyze in all supported languages or the Core and a language-specific plugin to optimize the memory usage.

You can install the following language-specific {ProductShortName} Visual Studio Code extensions from the Visual Studio Code Marketplace:

* `Java`
* `JavaScript` to analyze `JavaScript` and `Node.js` applications
* `C#` to analyze `C#` and `.NET` applications
* `Go`

:FeatureName: `Extension pack`, `C#`, `JavaScript`, and `Go` extensions
[IMPORTANT]
====
{FeatureName} are Developer Preview features only. Developer Preview features are not supported by Red{nbsp}Hat in any way and are not functionally complete or production-ready. Do not use Developer Preview features for production or business-critical workloads. Developer Preview features provide early access to upcoming product features in advance of their possible inclusion in a Red{nbsp}Hat product offering, enabling customers to test functionality and provide feedback during the development process. These features might not have any documentation, are subject to change or removal at any time, and testing is limited. Red{nbsp}Hat might provide ways to submit feedback on Developer Preview features without an associated service level agreement (SLA).
====
:!FeatureName:

.Prerequisites 

* You installed the Java Development Kit (JDK). {ProductShortName} supports the following JDKs:

** Oracle JDK 17 or later
** Eclipse Temurin™ JDK 17 or later
** OpenJDK 17 or later

* You have 8 GB of RAM available.

* For macOS installation, you have the value of `maxproc` set to `2048` or greater.

.Procedure

* Install the {ProductShortName} {ProductVersion} Visual Studio Code plugin from the Visual Studio Code Marketplace.

.Additional resources
* link:https://marketplace.visualstudio.com/search?term=migration%20toolkit&target=VSCode&category=All%20categories&sortBy=Relevance[Visual Studio Code Marketplace]
* link:{mta-URL}/configuring_and_using_red_hat_developer_lightspeed_for_mta/index[Configuring and using Developer Lightspeed for {ProductShortName}]
* link:https://access.redhat.com/support/offerings/devpreview[Developer Preview Support Scope]
