:_newdoc-version: 2.18.5
:_template-generated: 2025-09-26
:_mod-docs-content-type: PROCEDURE

[id="configuring-lighstspeed-ide-settings_{context}"]
= Configuring the IDE settings

[role="_abstract"]
{ProductShortName} settings apply to every analysis that you perform by using the Visual Studio (VS) Code extension. The extension settings have the following categories:

* Analysis-related settings
* Debugging and logging settings
* Solution server settings
* Generative AI settings 

.Procedure

. Open the {ProductShortName} settings by clicking `Extensions` > `{ProductShortName} Extension for VSCode` > `Settings`.
+
Alternatively, open the setting by performing the following steps:

.. Type `Ctrl + Shift + P` or `Cmd + Shift + P` on the search bar to open the Command Palette.
.. Enter `Preferences: Open Settings (UI)`. 
.. Open the settings page by clicing `Extensions` > `MTA`.
+
. Configure the following settings:

* Log level: Set the log level for the {ProductShortName} binary. The default log level is `debug`. The log level increases or decreases the verbosity of logs. 
* Analyzer path: Specify an {ProductShortName} custom binary path. If you do not provide a path, {mta-dl-plugin} uses the default path to the binary.
* Debug:Webview: Enable debug level logging for Webview message handling in VS Code.


.Next steps
* xref:configuring-profile-settings_vsc-extension-guide[Configure the {ProductShortName} profile settings].

[role="_additional-resources"]
.Additional resources
* link:https://docs.redhat.com/en/documentation/migration_toolkit_for_applications/8.0/html/developer-lightspeed-guide/index[Configuring and using Developer Lightspeed for {ProductShortName}].
