:_mod-docs-content-type: PROCEDURE
[id="installing-vscode-extension_{context}"]
= Installing the {ProductShortName} extension for Visual Studio Code

[role="_abstract"]
You can use the {ProductFullName} Visual Studio Code plugin to perform a standard application analysis. You can also enable Red Hat Developer Lightspeed for the {ProductName} to use Generative AI (GenAI) capabilities to fix code issues before migrating to target technologies. Note that Developer Lightspeed for {ProductShortName} is enabled by default. For more information, see link:{mta-URL}/configuring_and_using_red_hat_developer_lightspeed_for_mta/index[Configuring and using Developer Lightspeed for {ProductShortName}].

.Prerequisites 

* You installed the Java Development Kit (JDK). {ProductShortName} supports the following JDKs:

** Oracle JDK 17 or later
** Eclipse Temurin™ JDK 17 or later
** OpenJDK 17 or later

* You have 8 GB of RAM available.

* For macOS installation, you have the value of `maxproc` set to `2048` or greater.

.Procedure

* Install the {ProductShortName} {ProductVersion} Visual Studio Code plugin from the link:https://marketplace.visualstudio.com/search?term=migration%20toolkit&target=VSCode&category=All%20categories&sortBy=Relevance[Visual Studio Code marketplace]. 
