:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21

:_mod-docs-content-type: CONCEPT

[id="how-to-use-developer-lightspeed_{context}"]
= How to use {mta-dl-plugin}

[role="_abstract"]
You can opt to use {mta-dl-full} features to request a code fix suggestion after running a static code analysis of an application. 

To make code changes by using the LLM, you must enable the generative AI option in {ProductShortName} extension settings. Optionally, you can use an LLM proxy service if you want the {ProductShortName} Hub to access the LLM through an administrator-controlled endpoint. See xref:tackle-enable-llm-proxy_getting-started[Enabling LLM proxy in the Tackle custom resource]  for more information.

The configuration that you complete to use {mta-dl-plugin} depends on how you prefer to request code resolutions. You can complete one of the following workflow depending on if you want to use the Solution Server or the Agent AI. 

[NOTE]
====
If you make any change after enabling the generative AI settings in the extension, you must restart the extension for the change to take effect.
====

[id="solution-server-workflow_{context}"]
== Workflow to use the solution server

To use the Solution Server for code fix suggestions:

* Create a secret for your LLM key in the Red Hat {ocp-name} cluster.

* Enable the Solution Server in the Tackle custom resource (CR).

* Configure the LLM base URL and model in the Tackle CR.

* Enable the generative AI option in the {ProductShortName} extension settings.

* Add the Solution Server configuration in the `settings.json` file.

* Configure the profile settings and activate the LLM provider in the `provider-settings.yaml` file. 

[id="agent-mode-workflow_{context}"]
== Workflow to use the agent mode

To use the agent mode for code fix suggestions:

* Enable the generative AI and the agent mode in the {ProductShortName} extension settings.

* Configure the profile settings and activate the LLM provider in the `provider-settings.yaml` file. 