:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21

:_mod-docs-content-type: CONCEPT

[id="getting-started_{context}"]
= Getting Started with {mta-dl-plugin}

[role="_abstract"]
Inheritance, which is the default setting, means that all applications associated with the archetype inherit the _assessment_ and _review_ from the archetype groups to which these applications belong. However, you can override inheritance for the application by completing an individual assessment and review.

== Prerequisites  

Before you install {mta-dl-plugin}, you must:

* Create an API key for an LLM model.

* Supported LLM providers: OpenAI, Amazon Bedrock, Azure OpenAI, DeepSeek, Google Gemini, Ollama
OpenAI-API-compatible endpoints such as OpenShift AI

* Install Language Support for Java(TM) by Red Hat extension

* Install Java v17 and later

* Install Maven v3.9+

* Install Git and add it to the $PATH variable

* Installed the {ProductShortName} Operator 8.0.0

* Installed the {ProductShortName} command line 8.0.0

== Persistent volume requirements



== Installation
abc

== How to use {mta-dl-plugin}

* Configure an application in Visual Studio Code
