// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_mod-docs-content-type: CONCEPT
[id="solution-server_{context}"]

= About the Solution Server
:context: solution-server

[role=_abstract]
To understand how past code fixes are stored, review the role of the Solution Server. The Solution Server maintains the organizational memory for migration resolutions.

The Solution Server operates a backend database that stores solved examples and migration hints. It records accepted code changes whenever a developer accepts a suggested fix in their environment.

The Solution Server saves these resolution patterns to increase confidence metrics for future migration rules. Higher success metrics provide greater confidence levels for accepted code changes in subsequent analyses.


:FeatureName: Solution Server
[IMPORTANT]
====
[subs="attributes+"]
{FeatureName} is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
:!FeatureName:

:!solution-server:
