// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_mod-docs-content-type: CONCEPT
[id="agent-ai_{context}"]

= About the Agent AI
:context: agent-ai

[role="_abstract"]
You can enable the agent AI or the Solution Server mode to request AI-assisted code resolutions. In the agent AI mode, {mta-dl-plugin} streams an automated analysis of the code in a loop and makes changes in the code. In the initial run, the AI agent:

* Plans the context to define the issues.
* Chooses a suitable sub agent for the analysis task. {mta-dl-plugin} works with the LLM to generate fix suggestions. The LLM displays the reasoning transcript and files to change.
* Applies the changes to the code once you approve the updates.

If you accept that the agent AI must continue to make changes, it compiles the code and runs a partial analysis. In this iteration, the agent AI attempts to fix diagnostic issues (if any) generated by tools that you installed in the Visual Studio Code Integrated Development Environment (IDE). You can review the changes and accept the agent AI's suggestion to address these diagnostic issues. 

After each iteration of applying changes to the code, the agent AI asks if you want the agent to continue fixing more issues. When you accept, it runs another iteration of automated analysis until it has resolved all issues or it has made a maximum of two attempts to fix an issue.

Agent AI generates a new preview in each iteration when it updates the code with the suggested resolutions. The time that the agent AI takes to complete all iterations depends on the number of new diagnostic issues that it detects in the code.

:!agent-ai:
