:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21

:_mod-docs-content-type: CONCEPT

[id="developer-lightspeed-logs_{context}"]
= {mta-dl-plugin} logs

[role="_abstract"]
{mta-dl-full} generates logs to debug issues specific to the extension host and the {ProductShortName} analysis and Remote Procedure Call (RPC) server. You can also configure the log level for the {mta-dl-plugin} in the extension settings. The default log level is *debug*.

{mta-dl-plugin} stores the following logs:

* Extension logs (`extension.log`) with automatic rotation. The plugin retains three files with a maximum size of 10 MB each. 
* Analyzer RPC logs (`analyzer.log`) without automatic rotation.

[id="dev-lightspeed-archive-logs_{context}"]

== Log archives

To archive the logs as a zip file, type `{ProductShortName}: Generate Debug Archive` in the Visual Studio Code Command Palette and select the information type to archive as a log file. 

The archive command allows capturing all relevant log files in a zip archive at the specified location in your project. By default, you can access the archived logs in the .vscode directory of your project.

The archival feature helps you to save the following information:

* Large language model (LLM) provider configuration: The provider settings fields to include in the archive. To ensure security, {mta-dl-plugin} redacts all fields by default. Do not expose any secrets.
* LLM model arguments
* LLM traces: If you enabled tracing LLM interactions, you can choose to include LLM traces in the logs.

[id="dev-lightspeed-access-logs_{context}"]

== Log access

You can access the logs in the following ways:

* *Log file*: Type `Developer: Open Extension Logs Folder` and open the `redhat.mta-vscode-extension` directory that has the extension log and the analyzer log.

* *Output panel*: Select `{mta-dl-plugin}` from the drop-down menu.

* *Webview logs*: You can also inspect webview content by using the webview logs. To access the webview logs, type `Open Webview Developer Tools` in the Visual Studio Code Command Palette.