:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21

:_mod-docs-content-type: REFERENCE

[id="how-to-use-developer-lightspeed_{context}"]
= {mta-dl-plugin} workflows

[role="_abstract"]
You can configure the {mta-dl-plugin} extension to use centralized configuration and the large language model (LLM) through an LLM proxy. 
Alternatively, you can configure the extension to use the LLM provider settings in your Visual Studio Code environment for code resolution suggestions.

[NOTE]
====
If you make any change in configuration after enabling the generative AI settings in the extension, you must restart the extension for the change to take effect.
====

The configuration workflow that you complete to use {mta-dl-plugin} depends on the following factors:

* Whether you prefer to connect the {ProductShortName} extension to the LLM by using the LLM proxy. 
* Whether you want to use Agent AI for request resolutions without using LLM proxy.

You can complete one of the following workflows:

[id="agent-mode-workflow_{context}"]
== Workflow to use the Agent AI mode without the LLM proxy

As an Administrator, you must:

* Create a tackle secret for your LLM key in the Red Hat {ocp-name} cluster.

* Configure the Tackle custom resource (CR) to enable the LLM provider and the LLM model in the Tackle custom resource (CR). 

As a Migrator, you can complete the following workflow to use the Agent AI mode for code resolutions:

* Enable the generative AI in the {ProductShortName} extension settings.

* Configure a profile for the analysis.

* Activate the LLM provider in the `provider-settings.yaml` file. 

* Enable the Agent AI and run an analysis to request code fix suggestion by using the Agent AI mode.

[id="llm-proxy-workflow_{context}"]
== Workflow to use the LLM through the proxy service

You can allow client endpoints, for example, the {ProductShortName} Visual Studio Code extension, to use the proxy service to access the large language models (LLMs). The client uses Keycloak credentials to authenticate to the {ProductShortName} Hub. To authenticate to the LLM, the client sends a JSON Web Token (JWT) that Keycloak issues to the proxy service. The proxy service validates the client's JWT against the Hub's Keycloak instance. 

The proxy service completes a separate authentication process to access the LLM through an Administrator-controlled endpoint. The proxy service authenticates to the LLM by using the cluster secret that has the LLM API key that the Administrator configured. Thus, the proxy service allows Administrators to create, manage, and rotate LLM API keys without the need to share the LLM key with multiple client endpoints.

After you enable the LLM proxy, you can use either the Solution Server or Agent AI to generate code resolution requests in the Integrated Development Environment (IDE) extension. To use the Solution Server, the Administrator must deploy it in the {ocp-name} cluster with the proxy service. You cannot use the Solution Server without the proxy service.  

As an Administrator, you must complete the following workflow to enable the LLM proxy in the {ocp-name} cluster:

* Create a tackle secret cluster.

* Configure the Tackle custom resource (CR) to enable the LLM proxy service, enable the Solution Server if you want Migrators to use the Solution Server mode, and configure the LLM provider and the LLM model.

As a Migrator, you can:

* Enable the generative AI in the {ProductShortName} extension settings.

* If you want to use the Agent AI mode for code resolutions, enable the Agent AI and run an analysis.

* To use the Solution Server mode:
.. Connect to the {ProductShortName} Hub and run an analysis by using a profile downloaded from the Hub. See Running an application analysis by using a profile. 
.. Apply code resolutions that the Solution Server suggests.

.Additional resources

* xref:tackle-llm-secret_getting-started[Create a tackle secret in the cluster] 

* xref:tackle-enable-llm-proxy_getting-started[Configure the Tackle custom resource (CR)]

* xref:configuring-developer-lightspeed-ide-settings_configuring-dev-lightspeed-ide[Enable generative AI in the {ProductShortName} extension settings] 

* xref:configuring-developer-lightspeed-profile-settings_configuring-dev-lightspeed-ide[Configure a profile]

* xref:llm-provider-settings_configuring-llm[Activate the LLM provider] 

* xref:running-agent-analysis_run-dev-lightspeed-analysis[Enable Agent AI and run an analysis]

* xref:configuring-developer-lightspeed-ide-settings_configuring-dev-lightspeed-ide[{ProductShortName} extension settings]

* link:{mta-URL}/configuring_and_using_the_visual_studio_code_extension_for_mta/index#analyzing-application-profiles_vsc-extension-guide[Running an application analysis by using a profile]

* xref:apply-rag-resolution_run-dev-lightspeed-analysis[code resolutions that the Solution Server suggests]