:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21

:_mod-docs-content-type: CONCEPT

[id="how-to-use-developer-lightspeed_{context}"]
= How to use {mta-dl-plugin}

[role="_abstract"]You can opt to use {mta-dl-full} features to request a code fix suggestion after running a static code analysis of an application. {mta-dl-plugin} augments the manual changes made to code throughout your organization in different migration waves and creates a context that is shared with a large…

To make code changes by using the LLM, you must enable the generative AI option, along with either the Solution Server or the Agent AI. The configurations that you complete before you request code fixes depend on how you prefer to request code resolutions.

[NOTE]
====
If you make any change after enabling the generative AI settings in the extension, you must restart the extension for the change to take effect.
====

To use the Solution Server for code fix suggestions:

* Create a secret for your LLM key in the Red Hat {ocp-name} cluster.

* Enable the Solution Server in the Tackle custom resource (CR).

* Configure the LLM base URL and model in the Tackle CR.

* Enable the generative AI option in the {ProductShortName} extension settings.

* Add the Solution Server configuration in the `settings.json` file.

* Configure the profile settings and activate the LLM provider in the `provider-settings.yaml` file. 

To use the agent mode for code fix suggestions:

* Enable the generative AI and the agent mode in the {ProductShortName} extension settings.

* Configure the profile settings and activate the LLM provider in the `provider-settings.yaml` file. 