// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_mod-docs-content-type: CONCEPT
[id="solution-server_{context}"]

= About the Solution Server
:context: solution-server

[role="_abstract"]
Solution Server is a component that allows {mta-dl-plugin} to build a collective memory of source code changes from all analyses that an organization performs. This helps you to use the recurring patterns of solutions for issues that repeat in many applications. You can opt to use the Solution Server to request AI-assisted code resolutions. 

The Solution Server uses solved examples to suggest high-confidence resolutions for similar issues. When you accept a suggested code fix, the Solution Server updates the context. By using this improved context, the LLM generates more reliable resolutions in future.

The Solution Server delivers two primary benefits to users:

* *Contextual Hints*: It surfaces examples of past migration solutions, including successful user modifications and accepted fixes, offering actionable hints for difficult or previously unsolved migration problems.
* *Migration Success Metrics*: It exposes detailed success metrics for each migration rule, derived from real-world usage data. Integrated Development Environments (IDEs) or automation tools can use these metrics to present users with a “confidence level” or likelihood of {mta-dl-plugin} successfully migrating a given code segment.

When you use the Solution Server, you can view a diff of the updated portions of the code and the original source code to do a manual review. In a manual review of the suggested AI resolutions, you can accept, reject, or edit the suggested code changes.

:FeatureName: Solution Server
[IMPORTANT]
====
[subs="attributes+"]
{FeatureName} is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.
====
:!FeatureName:

.Additional resources
* link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope]

:!solution-server:
