:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21

:_mod-docs-content-type: CONCEPT

[id="developer-lightspeed-logs_{context}"]
= Debugging {mta-dl-plugin}

[role="_abstract"]
{mta-dl-full} generates logs to debug issues specific to the extension host and the {ProductShortName} analysis and RPC server. You can also configure the log level for the {mta-dl-plugin} in the extension settings. The default log level is *debug*.

Extension logs are stored as `extension.log` with automatic rotation. The maximum size of the log file is 10 MB and three files are retained. Analyzer RPC logs are stored as `analyzer.log` without rotation.

[id="dev-lightspeed-access-logs_{context}"]

== Access the logs

You can access the extension logs in the following ways:

* *Command Palette*: Type `Show Logs` or `Open Log` and select `Extension Host`.

* *Output panel*: Select `Extension Host` from the drop-down menu.

* *Log file*: Go to `.vscode/mta-logs` directory in your project and open the extension log file.

To access the analyzer log file, go to `.vscode/mta-logs` directory in your project and open the analyzer log file.

You can also inspect webview content by using the webview logs. To access the webview logs, type `Open Webview Developer Tools` in the VS Code Command Palette.

[id="dev-lightspeed-archive-logs_{context}"]

== Archive logs

The archival feature helps you to save the following information:

* Large language model (LLM) provider configuration 
* LLM model arguments
* Template configuration 
* LLama header
* LLM retry attempts
* LLM retries delay

Type `Generate Debug Archive` in the VS Code Command Palette and select the information type that must be archived as a log file. You can access the tar file of archived logs in the `.vscode` directory of your project.
