:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21
:_mod-docs-content-type: PROCEDURE

[id="tackle-enable-dev-lightspeed_{context}"]
= Enabling {mta-dl-plugin} in Tackle custom resource

[role="_abstract"]
Solution Server integrates with the {ProductShortName} Hub backend component to use the database and volumes necessary to store and retrieve the solved examples.

To enable Solution Server and other AI configurations in the {mta-dl-full} VS Code extension, you must modify the Tackle custom resource (CR) with additional parameters.

.Prerequisites

//the hard link must be changed to the same topic in 8.0.0 that has the `{mta-dl-plugin}-database` req.
. You deployed an additional RWO volume for  the `{mta-dl-plugin}-database` if you want to use {mta-dl-plugin}. See link:{mta-URL}/installing_the_migration_toolkit_for_applications/index#persistent-volume-requirements_installing-mta-ui[Persistent volume requirements] for more information.

. You installed the {ProductShortName} Operator v8.0.0 or later.


.Procedure

. Log in to the Red Hat {ocp-name} cluster and switch to the `openshift-mta` project.
+
. Edit the Tackle CR settings in the `tackle_hub.yml` file with the following command:
+
[source, terminal]
----
oc edit tackle
----

. Enter applicable values for `kai_llm_provider` and `kai_llm_model` variables.
+
[source, yaml]
----
---
kind: Tackle
apiVersion: tackle.konveyor.io/v1alpha1
metadata:
  name: mta
  namespace: openshift-mta
spec:
  kai_solution_server_enabled: true
  kai_llm_provider: <provider-name> #For example, OpenAI.
  # optional, pick a suitable model for your provider
  kai_llm_model: <model-name>
...
----
+

[NOTE]
====
For OpenAI models and LLMs deployed in the {ocp-name} AI cluster, enter `OpenAI` as the `kai_llm_provider` value.
====

. Apply the Tackle CR by in the `openshift-mta` project using the following command.
+
[source, terminal]
----
 $ oc apply -f tackle_hub.yaml
----

.Verification

. Enter the following command to verify the {mta-dl-plugin} resources deployed for Solution Server.
+
[source, terminal]
----
oc get deploy,svc -n openshift-mta | grep -E 'kai-(api|db|importer)'
----
