:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21
:_mod-docs-content-type: PROCEDURE

[id="tackle-enable-llm-proxy_{context}"]
= Enabling LLM proxy in the Tackle custom resource

[role="_abstract"]
You must enable the large language model (LLM) proxy in the Tackle custom resource (CR) and deploy it in the Red Hat {ocp-name} project where you installed the {ProductShortName} Operator.

The proxy authenticates to the LLM in the backend by using the OpenShift secret configured in the cluster. This helps the administrator to create, manage, and rotate the LLM key without sharing the key with many client endpoints (for example, {ProductShortName} IDE extension) in the organization. 

The client endpoint authenticates to the proxy by using the Hub credentials (Keycloak JSON Web Token). The proxy authenticates the client by validating the JWT tokens. 

.Prerequisites

. You deployed an additional RWO volume for  the `{mta-dl-plugin}-database` if you want to use {mta-dl-plugin}. See link:{mta-URL}/installing_the_migration_toolkit_for_applications/index#persistent-volume-requirements_installing-mta-ui[Persistent volume requirements] for more information.

. You installed the {ProductShortName} Operator v8.0.0.


.Procedure

. Log in to the Red Hat {ocp-name} cluster and switch to the `openshift-mta` project.
+
. Edit the Tackle CR settings in the `tackle_hub.yml` file with the following command:
+
[source, terminal]
----
oc edit tackle
----

. Enable `kai_llm_proxy_enabled` in the Tackle CR.
+
[source, yaml]
----
---
kind: Tackle
apiVersion: tackle.konveyor.io/v1alpha1
metadata:
  name: mta
  namespace: openshift-mta
spec:
  kai_llm_proxy_enabled: true
---
----

. Apply the Tackle CR by in the `openshift-mta` project using the following command.
+
[source, terminal]
----
 $ oc apply -f tackle_hub.yaml
----

