:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21
:_mod-docs-content-type: PROCEDURE

[id="configuring-llm-podman_{context}"]
= Configuring the LLM in Podman Desktop

[role="_abstract"]

The Podman AI lab extension enables you to use an open-source model from a curated list of models and use it locally in your system. 

The code fix suggestions generated by a model depends on the model's capabilities. Models deployed through the Podman AI Lab must were found to be insufficient for the complexity of code changes required to fix issues discovered by {ProductShortName}. You must not use such models in production environment.

.Prerequisites

* You installed link:https://podman-desktop.io/docs/installation[Podman Desktop] in your system.

* You completed initial configurations in {mta-dl-plugin} required for the analysis.

.Procedure

. Go to the Podman AI Lab extension and click *Catalog* under *Models*.

. Download one or more models.

. Go to *Services* and click *New Model Service*.

. Select a model that you downloaded in the *Model* drop down menu and click *Create Service*.

. Click the deployed model service to open the *Service Details* page.

. Note the server URL and the model name. 
You must configure these specifications in the {mta-dl-plugin} extension. 

. Export the inference server URL as follows:
+
[source, terminal]
----
export OPENAI_API_BASE=<server-url>
----
+
. In the {mta-dl-plugin} extension, type `Open the GenAI model provider configuration file` in the Command Pallete to open the `provider-settings.yaml` file.

. Enter the model details from Podman Desktop. For example, use the following configuration for a Mistral model. 
+
[source, yaml]
----
podman_mistral:
    provider: "ChatOpenAI"
     environment:
      OPENAI_API_KEY: "unused value"
    args:
      model: "mistral-7b-instruct-v0-2"
      base_url: "http://localhost:35841/v1"
----
+
[NOTE]
====
The Podman Desktop service endpoint does not need a password but the OpenAI library expects the `OPENAI_API_KEY` to be set. In this case, the value of the `OPENAI_API_KEY` variable does not matter.
====