:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21
:_mod-docs-content-type: PROCEDURE

[id="running-agent-analysis_{context}"]
= Generating code resolutions in the agent mode

[role="_abstract"]
As a Migrator, you can use the agent mode to run an automated analysis that streams the code resolutions that the agent can apply to your source code. When using the agent mode, you can reject the changes or stop the stream but you cannot edit the updated files during the stream.

The agent detects new issues in the code that may have occurred because of the earlier accepted changes or diagnostic issues that your tool may generate following an earlier analysis. If you allow the process to continue, {mta-dl-plugin} runs the stream again and generates a new file with the latest updates.

.Prerequisites

* You opened a Java project in your Visual Studio Code workspace.
* You configured an analysis profile on the *{ProductShortName} Analysis View* page.

.Procedure

. Enable the agent mode in one of the following ways:
+
.. Open the *MTA Analysis View* page.
.. Enable the *Agent Mode* on.
+
OR
+
.. Go to *Extensions > {ProductShortName}-core > GenAI: Agent Mode*
.. Select the *Agent Mode* checkbox. 
+
. Click the {mta-dl-plugin} extension and click *Open {ProductShortName} Analysis View*.
+
. Select a profile for the analysis.
+
. Click *Start* to start the {ProductShortName} Remote Procedure Call (RPC) server.
+
. Click *Run Analysis* on the *{ProductShortName} Analysis View* page.
The *Resolution Details* tab opens, where you can view the automated analysis that makes changes in applicable files.
+
. Click the *Review Changes* option to open the editor that shows the diff view of the modified file.
+
. Review the changes and click *Apply* to update the file with all the changes or *Reject* to reject all changes. If you applied the changes, then {mta-dl-plugin} creates the updated file with code changes.
+
. Open *Source Control* to access the updated file.
+
. In the *Resolution Details* view, accept the proposal from {mta-dl-plugin} to make further changes. 
The stream of analysis repeats, after which you can review and accept the changes. {mta-dl-plugin} creates the file with the code changes, and the stream continues until you reject the proposal for further analysis.