:_newdoc-version: 2.18.5
:_template-generated: 2025-07-31
:_mod-docs-content-type: CONCEPT

[id="roles-personas-users-permissions_{context}"]
= Roles, personas, users, and permissions

[role="_abstract"]
The {ProductFullName} uses three roles, each corresponding to a persona. The roles are predefined in your Red Hat Build of Keycloak (RHBK) instance. If you are an {ProductShortName} administrator, you can create users in your RHBK instance and assign each user one or more roles, one role per persona. 

A user can have more than one role. Each role must correspond to a specific persona:

* The `tackle-admin` role corresponds to the Administrator persona. The administrator has all permissions that architects and migrators have. Administrators can also create application-wide configuration parameters that other users can consume but cannot change or view, for example, Git credentials or Maven `settings.xml` files.

* The `tackle-architect` role corresponds to the Architect persona. An architect is a technical lead for the migration project. Architects can run assessments and can create and modify applications and information related to the applications. Architects cannot modify or delete sensitive information, but can consume such information. For example, architects can associate an existing set of credentials to the repository of a specific application. 	

* The `tackle-migrator` role corresponds to the Migrator persona. A migrator can analyze applications. However, the migrator cannot create, modify, or delete the applications. 

{ProductShortName} has two views, *Administration* and *Migration*. Only administrators can access the *Administration* view. Architects and migrators cannot see or access the *Administration* view. Administrators can perform all actions supported by the *Migration* view. Architects and migrators can see all elements of the *Migration* view. However, whether architects and migrators can perform actions in the *Migration* view depends on the permissions granted to their role.