:_newdoc-version: 2.18.5
:_template-generated: 2025-07-31
:_mod-docs-content-type: CONCEPT

[id="mta-rules_{context}"]
= {ProductShortName} rules

[role="_abstract"]
The {ProductFullName} contains rule-based migration tools called analyzers. You can use analyzers to analyze the application user interfaces (APIs), technologies, and architectures used by the applications you want to migrate.

{ProductShortName} analyzer rules use the following rule pattern:

----
when(condition)
 message(message)
 tag(tags)
----

You can use the {ProductShortName} rules internally to perform the following tasks:

* Extract files from archives
* Decompile files
* Scan and classify file types
* Analyze XML and other file content
* Analyze the application code
* Build the reports

{ProductShortName} builds a data model based on the rule execution results and stores component data and relationships in a graph database. This database can then be queried and updated as needed by the migration rules and for reporting purposes.

[NOTE]
====
You can create your own custom analyzer rules. You can use custom rules to identify the use of custom libraries or other components that the provided standard migration rules might not cover.

For instructions on how to write custom rules, see link:{mta-URL}/rules_development_guide/index[Rules Development Guide].
====


