:_newdoc-version: 2.18.3
:_template-generated: 2025-03-14
:_mod-docs-content-type: PROCEDURE

[id="installing-cli-zip_{context}"]
= Installing the CLI by using a .zip file

[role="_abstract"]
You can use the {ProductFullName} command-line interface (CLI) to assess and analyze your applications to prepare these applications for the migration.

You can install the {ProductShortName} CLI by using the downloadable `.zip` file available on the link:https://developers.redhat.com/products/mta/download[official {ProductShortName} download page].


.Prerequisites

* You logged in to `registry.redhat.io`. For more details, see link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication].
+
pass:[<!-- vale RedHat.Spelling = NO -->]
NOTE: This prerequisite is not applicable for the containerless mode.
pass:[<!-- vale RedHat.Spelling = YES -->] For more information, see link:{mta-URL}/using_the_mta_command-line_interface_to_analyze_applications/index#running-the-containerless-mta-cli_analyzing-applications-mta-cli[Analyzing an application in containerless mode].

* You installed Java Development Kit (JDK) version 17 or later.
* You set the `JAVA_HOME` environmental variable.
* You installed Maven version 3.9.9 or later and added the Maven binary to the `$PATH` variable.

.Procedure

. Navigate to the link:{DevDownloadPageURL}[{ProductShortName} download page] and download one of the following operating system-specific CLI files or the `src` file:
+
pass:[<!-- vale RedHat.CaseSensitiveTerms = NO -->]
* {ProductShortNameLower}-{ProductVersion}-cli-linux-amd64.zip
* {ProductShortNameLower}-{ProductVersion}-cli-linux-arm64.zip
* {ProductShortNameLower}-{ProductVersion}-cli-darwin-amd64.zip
* {ProductShortNameLower}-{ProductVersion}-cli-darwin-arm64.zip
* {ProductShortNameLower}-{ProductVersion}-cli-windows-amd64.zip
* {ProductShortNameLower}-{ProductVersion}-cli-windows-arm64.zip
* {ProductShortNameLower}-{ProductVersion}-cli-src.zip
pass:[<!-- vale RedHat.CaseSensitiveTerms = YES -->]

. Extract the `.zip` file to the `.kantra` directory inside your `$HOME` directory. The `.zip` file extracts the `mta-cli` binary, along with other required directories and files.

. Move the `mta-cli` binary to your `$PATH` variable.

+
NOTE: You can place the `mta-cli` binary in any folder that is included in the `$PATH` variable. Alternatively, you can add a folder that contains `mta-cli` to `$PATH`. This way, you do not need to specify a full path when using the CLI.
