:_newdoc-version: 2.18.3
:_template-generated: 2025-03-17
:_mod-docs-content-type: PROCEDURE

[id="installing-cli-for-docker_{context}"]
= Installing the CLI for use with Docker on Windows

[role="_abstract"]
To migrate applications built with .NET framework version 4.5 or later, on Microsoft Windows to cross-platform .NET 8.0, you must install the {ProductFullName} command-line interface (CLI) for use with Docker on Windows.

To install the {ProductShortName} CLI for use with Docker on Windows, you must configure Docker to use Windows containers first.

.Prerequisites

* You have a host with 64-bit Windows 11, version 21H2 or later.

* You downloaded the Docker Desktop for Windows installation program. For more details, see link:https://docs.docker.com/desktop/install/windows-install/[Install Docker Desktop on Windows].

.Procedure

. Open a PowerShell with Administrator privileges.

. Ensure Hyper-V is installed and enabled:
+
[subs="+quotes"]
----
PS C:\Users\<user_name>> *Enable-WindowsOptionalFeature -Online `
   -FeatureName Microsoft-Hyper-V-All*
----
+
[subs="+quotes"]
----
PS C:\Users\<user_name>> *Enable-WindowsOptionalFeature -Online `
   -FeatureName Containers*
----
+
NOTE: You might need to reboot Windows for the change to take effect.

. Install Docker Desktop on Windows.

.. Run the installer by double-clicking the `Docker_Desktop_Installer.exe` file. 
+
By default, Docker Desktop is installed to the `C:\Program Files\Docker\Docker` path.

.. Ensure that Docker runs Windows containers as the backend instead of Linux containers:

... In the Windows task bar, right-click the Docker icon.
... Click *Switch to Windows containers*.

. In PowerShell, create a folder for {ProductShortName}:
+
[subs="+quotes"]
----
PS C:\Users\<user_name>> *mkdir C:\Users\<user_name>\MTA*
----

. Extract the `{ProductShortNameLower}-{ProductVersion}-cli-windows.zip` file to the `MTA` folder:
+
[subs="+quotes"]
----
PS C:\Users\<user_name>> *cd C:\Users\<user_name>\Downloads*
----
+
[subs="+quotes"]
----
PS C:\Users\<user_name>> *Expand-Archive `
   -Path "{ProductShortNameLower}-{ProductVersion}-cli-windows.zip" `
   -DestinationPath "C:\Users\<user_name>\MTA"*
----

. Ensure that Docker is running Windows containers the `OS/Arch` is set to `windows/amd64`:
+
[subs="+quotes"]
----
PS C:\Users\<user_name>> *docker version*
----
+
[subs="+quotes"]
----
Client:
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:03:32 2024
 OS/Arch:           *windows/amd64*
 Context:           desktop-windows
Server: Docker Desktop 4.32.0 (157355)
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:13 2024
  OS/Arch:          *windows/amd64*
  Experimental:     false
----

. Set the `CONTAINER_TOOL` environment variable to use Docker:
+
[subs="+quotes"]
----
PS C:\Users\<user_name>> *$env:CONTAINER_TOOL="C:\Windows\system32\docker.exe"*
----

. Set the `DOTNET_PROVIDER_IMG` environment variable to use the upstream `dotnet-external-provider`:
+
[subs="+quotes"]
----
PS C:\Users\<user_name>> *$env:DOTNET_PROVIDER_IMG="quay.io/konveyor/dotnet-external-provider:v0.5.0"*
----

. Set the `RUNNER_IMG` environment variable to use the upstream image:
+
[subs="+quotes"]
----
PS C:\Users\<user_name>> *$env:RUNNER_IMG="quay.io/konveyor/kantra:v0.5.0"*
----

