:_newdoc-version: 2.18.3
:_template-generated: 2025-05-28

ifdef::context[:parent-context-of-rules-prov-cond: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="rules-prov-cond"]
endif::[]
ifdef::context[]
[id="rules-prov-cond_{context}"]
endif::[]
= Providers and rule conditions 

:context: rules-prov-cond

[role="_abstract"]
Providers are the modular components that work with the analysis engine to analyze application source code. They run search queries on the code based on rule patterns that you defined to scan for issues. 

The external providers, except `C#`, use the Language Server Protocol (LSP) to perform an analysis. The provider forms a search query and sends it to the  LSP server to check against the application. When the LSP server returns a match for the search in the source code, the analyzer triggers a violation. 

Currently, {ProductShortName} supports the following providers:

* `builtin`
* `Java` 
* `C#`
* External providers (for `Python`, `Go`, and `Node.js` applications) initialized by the generic provider binary

[NOTE]
====
You can use the generic provider binary to create an external provider for any language that is compliant with link:https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/[LSP 3.17 specifications].
====

include::topics/rules-development/con_provider-capability-in-custom-rules.adoc[leveloffset=+1]

include::topics/rules-development/yaml-provider-conditions.adoc[leveloffset=+1]

include::topics/rules-development/yaml-builtin-provider.adoc[leveloffset=+1]

include::topics/rules-development/yaml-java-provider.adoc[leveloffset=+1]

include::topics/rules-development/yaml-go-provider.adoc[leveloffset=+1]

include::topics/rules-development/yaml-dotnet-provider.adoc[leveloffset=+1]

ifdef::parent-context-of-rules-prov-cond[:context: {parent-context-of-rules-prov-cond}]
ifndef::parent-context-of-rules-prov-cond[:!context:]

:!rules-prov-cond: