:_newdoc-version: 2.18.3
:_template-generated: 2025-05-28

ifdef::context[:parent-context-of-rules-prov-cond: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="rules-prov-cond"]
endif::[]
ifdef::context[]
[id="rules-prov-cond_{context}"]
endif::[]
= Providers and rule conditions 

:context: rules-prov-cond

[role="_abstract"]
The providers are the modular components in charge of analyzing a given language. The external providers, except `C#`, are able to analyze code by leveraging the Language Server Protocol (LSP). Through the LSP, all code analysis is abstracted away from the analysis engine and left to the specific LSP server to run the search query defined in the rule on the source code. 

Additionally, {ProductShortName} provides a built-in provider with abilities such as XML parsing, running regular expressions on files, and so on.

Currently, {ProductShortName} supports the following providers:

* builtin
* Java 
* C#
* External providers (for `Python`, `Go`, and `Node.js` applications) initialized by the generic provider binary

[NOTE]
====
You can use the generic provider binary to create an external provider for any language that is compliant with link:https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/[LSP 3.17 specifications].
====

include::topics/rules-development/con_provider-capability-in-custom-rules.adoc[leveloffset=+1]

include::topics/rules-development/yaml-provider-conditions.adoc[leveloffset=+1]

include::topics/rules-development/yaml-builtin-provider.adoc[leveloffset=+1]

include::topics/rules-development/yaml-java-provider.adoc[leveloffset=+1]

include::topics/rules-development/yaml-go-provider.adoc[leveloffset=+1]

include::topics/rules-development/yaml-dotnet-provider.adoc[leveloffset=+1]

ifdef::parent-context-of-rules-prov-cond[:context: {parent-context-of-rules-prov-cond}]
ifndef::parent-context-of-rules-prov-cond[:!context:]

:!rules-prov-cond: