:_newdoc-version: 2.18.3
:_template-generated: 2025-05-28

ifdef::context[:parent-context-of-rules-prov-cond: {context}]

:_mod-docs-content-type: ASSEMBLY
// JTBD job: develop-custom-rules
// Statement: When MTA does not cover my migration scenario, I want to create custom YAML rules so I can extend analysis and transformation for my stack.
// Persona: Rule developer

ifndef::context[]
[id="rules-prov-cond"]
endif::[]
ifdef::context[]
[id="rules-prov-cond_{context}"]
endif::[]
= Providers and rule conditions 

:context: rules-prov-cond

[role="_abstract"]
Use providers and rule conditions to analyze code with the Language Server Protocol (LSP). {ProductShortName} includes built-in and language-specific providers; the when block in a rule defines matching conditions.

Currently, {ProductShortName} supports the following providers:

* Builtin
* Java 
* Go 
* External providers (for `Python`, `Dotnet` and `Node.js` applications) initialized by the generic provider binary

[NOTE]
====
You can use the generic provider binary to create an external provider for any language that is compliant with link:https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/[LSP 3.17 specifications].
====

.Using the provider capability in custom rules

In a rule, the when block is where the conditions for matching the rule are specified. Each provider offers a series of capabilities to do matching.. The search query in the rule condition can contain patterns, code locations, specific dependencies to be found, and so on, to evaluate the source code and dependencies. The provider sends the LSP server a request to check the search query against the application being analyzed. When the LSP server returns a match for the search in the source code, the analyzer triggers a violation.

The syntax for the when block is as follows: contains one condition, but that condition can have multiple conditions nested under it.

----
when:
  <condition>
    <nested-condition>
----

include::topics/rules-development/yaml-provider-conditions.adoc[leveloffset=+1]

include::topics/rules-development/yaml-builtin-provider.adoc[leveloffset=+1]

include::topics/rules-development/yaml-java-provider.adoc[leveloffset=+1]

include::topics/rules-development/yaml-go-provider.adoc[leveloffset=+1]

include::topics/rules-development/yaml-dotnet-provider.adoc[leveloffset=+1]

ifdef::parent-context-of-rules-prov-cond[:context: {parent-context-of-rules-prov-cond}]
ifndef::parent-context-of-rules-prov-cond[:!context:]

:!rules-prov-cond: