:_newdoc-version: 2.18.3
:_template-generated: 2025-05-28

ifdef::context[:parent-context-of-generating-assets: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="generating-assets"]
endif::[]
ifdef::context[]
[id="generating-assets_{context}"]
endif::[]
= Generating platform assets for application deployment

:context: generating-assets

[role="_abstract"]
To enable offline review and simplify the distribution of assessment results, you can generate static assets by using the {ProductFullName} command-line interface. This process produces standalone reports and data files, allowing you to share migration insights with stakeholders without requiring access to the analysis environment.

You can use the `discover` and `generate` commands in containerless mode to automatically generate the manifests needed to deploy a Cloud Foundry (CF) application in the {ocp-short}: 

* Use the `discover` command to generate the discovery manifest in the YAML format directly from a CF instance or from either of the following manifest files:

** A single application manifest
** A CF manifest
** A path to the directory with multiple manifest files, for example, with application manifests, CF manifests, or both of these manifest types.

+
The discovery manifest preserves the specifications found in the CF manifest. The specifications define the metadata, runtime, and platform configurations. 

* Use the `generate` command to generate the deployment manifest for {ocp} deployments. You can use this command to generate the Kubernetes and non-Kubernetes manifests.


:FeatureName: Generating platform assets for application deployment

[IMPORTANT]
====
[subs="attributes+"]
{FeatureName} is Developer Preview software only. Developer Preview software is not supported by Red{nbsp}Hat in any way and is not functionally complete or production-ready. Do not use Developer Preview software for production or business-critical workloads. Developer Preview software provides early access to upcoming product software in advance of its possible inclusion in a Red{nbsp}Hat product offering. Customers can use this software to test functionality and provide feedback during the development process. This software might not have any documentation, is subject to change or removal at any time, and has received limited testing. Red{nbsp}Hat might provide ways to submit feedback on Developer Preview software without an associated SLA.

For more information about the support scope of Red{nbsp}Hat Developer Preview software, see link:https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope].
====
:!FeatureName:

Generating deployment assets has the following benefits:

* Generating the Kubernetes and non-Kubernetes deployment manifests.   
* Generating deployment manifests by using familiar template engines, for example, Helm, that are widely used for Kubernetes deployments.
* Adhering to Kubernetes best practices when preparing the deployment manifest by using Helm templates.


include::topics/mta-cli/proc_generating-discovery-manifest.adoc[leveloffset=+1]

include::topics/mta-cli/ref_discovery_manifest_sample.adoc[leveloffset=+1]

include::topics/mta-cli/proc_performing-a-live-discovery.adoc[leveloffset=+1]

include::topics/mta-cli/proc_concealing-sensitive-information.adoc[leveloffset=+1]

include::topics/mta-cli/proc_generating-deployment-manifest.adoc[leveloffset=+1]

include::topics/mta-cli/proc_generate_deployment_assets_values_file.adoc[leveloffset=+1]

include::topics/mta-cli/proc_assets-generation-example.adoc[leveloffset=+1]

include::topics/mta-cli/ref_discover-generate-command-options.adoc[leveloffset=+1]


ifdef::parent-context-of-generating-assets[:context: {parent-context-of-generating-assets}]
ifndef::parent-context-of-generating-assets[:!context:]

