:_newdoc-version: 2.18.3
:_template-generated: 2025-05-28

ifdef::context[:parent-context-of-generating-assets: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="generating-assets"]
endif::[]
ifdef::context[]
[id="generating-assets_{context}"]
endif::[]
= Generating platform assets for application deployment

:context: generating-assets

[role="_abstract"]
To enable offline review and simplify the distribution of assessment results, you can generate static assets by using the {ProductFullName} command-line interface. This process produces standalone reports and data files, allowing you to share migration insights with stakeholders without requiring access to the analysis environment.

You can use the `discover` and `generate` commands in containerless mode to automatically generate the manifests needed to deploy a Cloud Foundry (CF) application in the {ocp-short}: 

* Use the `discover` command to generate the discovery manifest in the YAML format directly from a CF instance or from either of the following manifest files:

** A single application manifest
** A CF manifest
** A path to the directory with multiple manifest files, for example, with application manifests, CF manifests, or both of these manifest types.

+
The discovery manifest preserves the specifications found in the CF manifest. The specifications define the metadata, runtime, and platform configurations. 

* Use the `generate` command to generate the deployment manifest for {ocp} deployments by using the discovery manifest. The deployment manifest is generated by using a templating engine, such as Helm, that converts the discovery manifest into a Kubernetes-native format. You can also use this command to generate non-Kubernetes manifests, such as a Dockerfile or a configuration file.

:FeatureName: Generating platform assets for application deployment
include::topics/snippets/developer-preview-admonition.adoc[]

Generating deployment assets has the following benefits:

* Generating the Kubernetes and non-Kubernetes deployment manifests.   
* Generating deployment manifests by using familiar template engines, for example, Helm, that are widely used for Kubernetes deployments.
* Adhering to Kubernetes best practices when preparing the deployment manifest by using Helm templates.



include::topics/mta-cli/proc_generating-discovery-manifest.adoc[leveloffset=+1]

include::topics/mta-cli/proc_performing-a-live-discovery.adoc[leveloffset=+1]

include::topics/mta-cli/proc_concealing-sensitive-information.adoc[leveloffset=+1]

include::topics/mta-cli/proc_generating-deployment-manifest.adoc[leveloffset=+1]

include::topics/mta-cli/proc_assets-generation-example.adoc[leveloffset=+1]

include::topics/mta-cli/ref_discover-generate-command-options.adoc[leveloffset=+1]


ifdef::parent-context-of-generating-assets[:context: {parent-context-of-generating-assets}]
ifndef::parent-context-of-generating-assets[:!context:]

