:_newdoc-version: 2.18.3
:_template-generated: 2025-03-17

ifdef::context[:parent-context-of-analyzing-applications-mta-cli: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="analyzing-applications-mta-cli"]
endif::[]
ifdef::context[]
[id="analyzing-applications-mta-cli_{context}"]
endif::[]
= Analyzing Java applications with {ProductShortName} command-line interface

:context: analyzing-applications-mta-cli

[role="_abstract"]
To assess and prioritize migration and modernization efforts for applications written in different languages, analyze your applications by using the {ProductFullName} {CLINameTitle}. 

{ProductShortName} CLI supports running source code and binary analysis by using `analyzer-lsp`. `analyzer-lsp` is a tool that evaluates rules by using language providers.

Depending on your scenario, you can use the {ProductShortName} CLI to perform the following actions:

* Run the analysis against a single application.
* Run the analysis against multiple applications in either of the following ways:
** Enter a series of `--analyze` commands, each against an application and each generating a separate report.
** Use the `--bulk` option to analyze multiple applications at once and generate a single report. Note that this feature is a Developer Preview feature only.

* Run the analysis for Java applications in the containerless mode. Note that this option is set by default and is used automatically only if all requirements are met.
+
However, if you want to analyze applications in languages other than Java or, for example, use transformation commands, you still need to use containers.

////
[NOTE]
====
The analysis output in the disconnected environment usually results in fewer incidents because a dependency analysis does not run accurately without access to Maven.
====
////

include::topics/mta-cli/proc_analyzing-single-app-with-mta-cli.adoc[leveloffset=+1]
 
include::topics/mta-cli/proc_analyzing-multiple-apps-with-mta-cli.adoc[leveloffset=+1]

include::topics/mta-cli/proc_running-the-containerless-mta-cli.adoc[leveloffset=+1]

include::topics/mta-cli/ref_mta-cli-analyze-flags.adoc[leveloffset=+1]


ifdef::parent-context-of-analyzing-applications-mta-cli[:context: {parent-context-of-analyzing-applications-mta-cli}]
ifndef::parent-context-of-analyzing-applications-mta-cli[:!context:]

