:_newdoc-version: 2.18.3
:_template-generated: 2025-04-09

ifdef::context[:parent-context-of-analyzing-multi-language-applications: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="analyzing-nonjava-applications"]
endif::[]
ifdef::context[]
[id="analyzing-nonjava-applications_{context}"]
endif::[]
= Analyzing applications written in languages other than Java with {ProductShortName} command-line interface

:context: analyzing-nonjava-applications

[role="_abstract"]
To assess the migration effort for applications written in languages other than Java, you can analyze your source code by using the {ProductFullName} command-line interface (CLI). The analysis identifies dependencies and potential migration issues, helping you prioritize tasks and estimate the resources required to modernize your non-Java portfolio.

You can perform the analysis either of the following ways:

* Select a supported language provider to run the analysis for. 	
* Overwrite the existing supported language provider with your own unsupported language provider, and then run the analysis on it.
 

IMPORTANT: Analyzing applications written in languages other than Java is only possible in container mode. You can use the containerless CLI only for Java applications. For more information, see xref:running-the-containerless-mta-cli_analyzing-applications-mta-cli[Analyzing an application in containerless mode].


include::topics/mta-cli/proc_analyze-selected-provider.adoc[leveloffset=+1]

include::topics/mta-cli/proc_analyze-unsupported-provider.adoc[leveloffset=+1]


ifdef::parent-context-of-analyzing-multi-language-applications[:context: {parent-context-of-analyzing-multi-language-applications}]
ifndef::parent-context-of-analyzing-multi-language-applications[:!context:]

