:_newdoc-version: 2.18.3
:_template-generated: 2025-03-17

ifdef::context[:parent-context-of-platform-awareness: {context}]

:_mod-docs-content-type: ASSEMBLY
// JTBD job: use-web-console-assets
// Statement: When I use the web console, I want to create source platforms, discover apps, and generate assets so I can migrate from Cloud Foundry (or similar) to OpenShift.
// Persona:Create source platform and discover applications Configure generators and target profiles:[]
ifdef::context[]
[id="platform-awareness_{context}"]
endif::[]
= Platform awareness in {ProductShortName} {WebName}

:context: platform-awareness


[role="_abstract"]
Use platform awareness in the MTA web console for migration planning.

Starting with 8.0.0, {ProductShortName} supports platform awareness to import all or selective applications directly from source platform instances. 

You can associate applications to source platforms in two ways: 

* By manually configuring source platforms for applications that are available in {ProductShortName} inventory

* By discovering (importing) applications from a source platform instance. 
In this case, the applications are connected with the source platform when they are imported in the {ProductShortName} inventory.

In {ProductShortName} 8.0.0, Red Hat supports Cloud Foundry (CF) as the source platform. 

After you import applications, you can retrieve platform and runtime configurations (also known as discovery). Discovery is the process of fetching configurations of the imported applications that are connected to their source platform instances. The retrieval or discovery generates the discovery manifest that contain application configurations. 

You can later use the discovery manifest to generate the final set of assets required to deploy the applications in the target platform.

You can perform the following tasks in the {ProductShortName} {WebName}:

. Create multiple source platform (CF) instances. 
. Link an application created in the {ProductShortName} {WebName} to the source platform.
. Fetch the discovery manifest. You can generate the discovery manifests per application or in bulk. 

include::proc_creating-source-platform.adoc[leveloffset=+1]

include::proc_discovering-apps-source-platform-administration-view.adoc[leveloffset=+1]

include::proc_discovering-apps-source-platform-migration-view.adoc[leveloffset=+1]

include::proc_adding-source-platform-application.adoc[leveloffset=+1]

include::proc_generating-discovery-manifest-web.adoc[leveloffset=+1]

ifdef::parent-context-of-platform-awareness[:context: {parent-context-of-platform-awareness}]
ifndef::parent-context-of-platform-awareness[:!context:]