:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21
:_mod-docs-content-type: PROCEDURE

[id="configuring-target-profiles_{context}"]
= Configuring a target profile

[role="_abstract"]
Generate assets by using a target profile that contains one or more generators. Each generator generates assets for a different migration path. An Architect can create and track the target profiles for a specific archetype on the *Archetypes* page. You can configure more than one target profile for an archetype based on the target platforms to which you want to migrate applications of the specific archetype.

The generators are run in a priority order, in which manifests generated by lower priority generators do not override manifests generated by other generators.  

.Procedure

. In the *Migration* view, click *Archetypes*.
. Click the Options menu ({kebab}) of an archetype, and select *Manage target profiles*.
+
The *Target profiles for <archetype-name>* appears.
. Click *Create new target profile*.
. In the *Name* field in the opened dialogue, enter a unique name for the target profile.
. Click the *Tag category* field and select the category tag to associate with the tag.
. Select specific generators and click the right arrow to move the generator from the *Available generators* list to the *Chosen generators* list.
. (Optional) Select an analysis profile for the application from the list. You can download this profile configuration from the {ProductShortName} {CLIName} only if you select the profile from this list.
. Click *Create*.

You can click on the archetype row to open the archetype detail view where the target profiles for the archetype are listed.

[NOTE]
====
If you delete a target profile, {ProductShortName} also automatically deletes the analysis profile associated with the target profile.
====