:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21
:_mod-docs-content-type: PROCEDURE

[id="discovering-apps-source-platform_{context}"]
= Discovering applications through source platform in the Administration view

[role="_abstract"]
After you configure a source platform, you can discover and import one or more applications to the {ProductShortName} application inventory.

You can filter application manifests in the CF clusters by organizations and spaces, and application names. 

.Prerequisites

* You configured at least one source platform instance in the *Administration* view.

* Source platform instance must be running.

.Procedure

. In the {ProductShortName} user interface, select the *Administration* view.

. Click *Source platforms* in the navigation menu to go to the *Source platforms* page.

. Select a source platform on the *Source platforms* page.

. Click the Options menu ({kebab}) of a source platform.

. Click *Discover applications* to open the *Discover applications* window.
+
The discovery process imports all or selected applications deployed in the source platform instance to the *Applications Inventory* page on {ProductShortName}. 

. Optional: Click *+Add a name* to enter one application per text field and repeat the process to add more than one application. For example, app-a.

. Optional: Click *+Add a space* to enter one space per text field and repeat the process to add more than one space. For example, space1.

. Click *+Add an organization* to enter at least one organization per text field and repeat the process to add more than one organization. For example, org1.
+

[NOTE]
====
For a CF instance, the application `names` field can contain globs. For example, `app*`.
====

. Click *Next* to review the configuration.

. Click *Discover applications*.
This action tiggers an application import task.

. Close the *Discover applications* window.
+
. Optional: Hover over the source platform name to check the status of the application import task and click the application import task to view the task details in YAML format.