:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21
:_mod-docs-content-type: PROCEDURE

[id="discovering-apps-source-platform_{context}"]
= Discovering applications through source platform 

[role="_abstract"]
After you configure a source platform, you can discover and import one or more applications to the {ProductShortName} application inventory.

.Prerequisites

* You configured at least one source platform instance in the *Administration* mode.

* Source platform instance should be running.

.Procedure

. In the {ProductShortName} user interface, select the *Administration* working mode.

. Click *Source Platforms* in the navigation menu to go to the *Source Platforms* page.

. Select a source platform on the *Source platforms* page.

. Click the Options menu ({kebab}) of a source platform and click *Discover applications*. The *Discover applications* window appears.
+
The discovery process imports all or selected applications that are deployed in the source platform instance to the *Applications Inventory* page on {ProductShortName}. 

. Type the platform coordinate details based on which {ProductShortName} filters applications during the discovery process. 
+
The following example shows platform coordinates of a CF instance:
+
[source, json]
----
{
    "names": ["app-a", "app-b"],
    "spaces": ["example-space"]
}
----
+
[NOTE]
====
For a CF instance, the application `names` field can contain globs. For example, `app*`.
====
+
. Review the configuration and click *Discover applications*.
This action tiggers an application import task.

. Close the *Discover applications* window.
+
. (Optional) Hover over the source platform name to check the status of the application import task and click the application import task to view the task details in YAML format.