:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21

:_mod-docs-content-type: CONCEPT

[id="automatic-tagging-of-an-application_{context}"]
= Automatic tagging

[role="_abstract"]

{ProductShortName} automatically spawns language discovery and technology discovery tasks when adding an application to the *Application Inventory*. When the language discovery task is running, the technology discovery and analysis tasks wait until the language discovery task is finished. These tasks automatically add tags to the application. {ProductShortName} can automatically add tags to the application based on the application analysis. Automatic tagging is especially useful when dealing with large portfolios of applications.

Automatic tagging of applications based on application analysis is enabled by default. You can disable automatic tagging during application analysis by deselecting the *Enable automated tagging* checkbox in the *Advanced* section of the *Analysis configuration* wizard.

NOTE: To tag an application automatically, make sure that the *Enable automated tagging* checkbox is selected _before_ you run an application analysis.
