// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="create-nodejs-custom-rule_{context}"]
= Creating a custom Node.js rule

[role="_abstract"]
{ProductShortName} requires you to create custom rules to analyze `Node.js` applications. A `Node.js` rule can contain `nodejs.referenced` capability which supports the `pattern` field. 

The following example uses a custom rule to check if a `.tsx` file in the `Node.js` project imports the `React` framework.

.Procedure
. Create the directory `test-nodejs`.
+

[source, terminal]
----
$ mkdir -p ~/test-nodejs
----

. Save the following rule as `nodejs-rule-001.yml` in the `test-nodejs` directory:
+
[source, yaml]
----
  - ruleID: test-tsx-support-00000
  description: Found React import in .tsx file
  when:
    builtin.filecontent:
     pattern: "import.*React"
      filePattern: "\\.tsx$"
  message: Found React import in .tsx file
  effort: 1
----

. Create the following test application in the `Component.tsx` file:
+

[source, node.js]
----
import React from 'react';
 export const MyComponent: React.FC = () => <div>Hello</div>;
----

. Run the following command in the {ProductShortName} CLI:
+

[source, terminal]
----
$ ./mta-cli analyze -i ~/test-nodejs/ -o \
~/test-nodejs/report --run-local=false \
--rules ~/test-nodejs/nodejs-rule-001.yml
----
+

[NOTE]
====
Add the --overwrite option if you want to use the same directory for the report when you run subsequent tests. {ProductShortName} overwrites the current report with the result of the latest analysis that you run.
====

. Open the static report at `~/test-nodejs/report/static-report/index.html` in your browser.

. Click the <application_name> to open the Dashboard.

. Review the incidents in the *Issues* tab.

