// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_content-type: PROCEDURE

[id="installing-cli-tool_{context}"]
= Installing the {CLINameTitle}

You can install the {CLINameTitle} on Linux, Windows, or macOS operating systems using the downloadable `.zip` file.

[IMPORTANT]
====
Starting from {ProductShortName} 7.2.0, you can run the application analysis for Java applications in the containerless mode.

The containerless mode is set by default and is used automatically if all requirements are met. For more information, see xref:running-the-containerless-mta-cli_cli-guide[Running the containerless CLI].

However, if you want to analyze applications in languages other than Java or, for example, use xref:mta-cli-transform_cli-guide[transformation commands], you still need to use containers.
====

.Prerequisites for containerized CLI

The following are the prerequisites for the {ProductFullName} CLI installation (container):

* Red Hat Container Registry Authentication for `registry.redhat.io`. Red Hat distributes container images from `registry.redhat.io`, which requires authentication. For more details, see link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication].

* link:https://podman.io/[Podman] must be installed.

* 8 GB of RAM is required for the {ProductShortName} {CLIName}.

.Prerequisites for containerless CLI

The following are the prerequisites if you want to to run {ProductShortName} {CLIName} as in xref:running-the-containerless-mta-cli_cli-guide[containerless CLI] mode:

* Java Development Kit (JDK) is installed.
+
{ProductShortName} supports the following JDKs:

** Oracle JDK 17 or later
** Eclipse Temurin™ JDK 17 or later
** OpenJDK 17 or later
+
If you install OpenJDK on {op-system-base-full} or Fedora, the JDK requires a compiler provided by the `devel` package to also be installed, as having only the Java Runtime (JRE) installed causes issues during analysis. For more information about installing Red Hat build of OpenJDK 17 on {op-system-base-full}, see link:https://docs.redhat.com/en/documentation/red_hat_build_of_openjdk/17/html-single/installing_and_using_red_hat_build_of_openjdk_17_on_rhel/index#installing-jre-on-rhel-using-archive_openjdk[Installing Red Hat build of OpenJDK on RHEL by using yum].

* You must set the `JAVA_HOME` and the `PATH` environment variables.

* Maven 3.9.9 installed, and the bin directory is added to the `PATH` environment variable. Setting the path and environment variables depends on the operating system you are using. For more information about installing Maven, see link:https://maven.apache.org/install.html[Apache Maven installation].

* macOS installation requires:

** The value of `maxproc` must be `2048` or greater.

[id="installing-downloadable-cli-zip_{context}"]
== Installing the {CLINameTitle} `.zip` file

.Procedure

. Navigate to the link:{DevDownloadPageURL}[{ProductShortName} Download page] and download the OS-specific CLI file or the `src` file:
+
* {ProductShortNameLower}-{ProductVersion}-cli-linux-amd64.zip
* {ProductShortNameLower}-{ProductVersion}-cli-linux-arm64.zip
* {ProductShortNameLower}-{ProductVersion}-cli-darwin-amd64.zip
* {ProductShortNameLower}-{ProductVersion}-cli-darwin-arm64.zip
* {ProductShortNameLower}-{ProductVersion}-cli-windows-amd64.zip
* {ProductShortNameLower}-{ProductVersion}-cli-windows-arm64.zip
* {ProductShortNameLower}-{ProductVersion}-cli-src.zip

. Extract the `.zip` file to the `.kantra` directory inside your `$HOME` directory. The `.zip` file extracts the *mta-cli* binary, along with other required directories and files.
+
When you encounter `<{ProductShortName}_HOME>` in this guide, replace it with the actual path to your {ProductShortName} installation.


[id="installing-using-podman_{context}"]
== Installing the {CLINameTitle} by using Podman

You can install the containerized {CLINameTitle} using `podman pull`.

[NOTE]
====
You cannot install the containerless {CLINameTitle} using Podman as this procedure does not include pulling and unpacking the dependencies that are included in the `.zip` file.
====

.Prerequisites

* Red Hat Container Registry Authentication for `registry.redhat.io`. Red Hat distributes container images from `registry.redhat.io`, which requires authentication. See link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication] for additional details.

* Podman must be installed.

[NOTE]
====
Podman is a daemonless, open source, Linux-native tool designed to make it easy to find, run, build, share, and deploy applications using Open Containers Initiative (OCI) Containers and Container Images.
Podman provides a command-line interface (CLI) familiar to anyone who has used the Docker Container Engine.
For more information on installing and using Podman, see link:https://podman.io/docs/installation[Podman installation instructions].
====

.Procedure

. Use Podman to authenticate to `registry.redhat.io` by running the following command:
+
[source,terminal]
----
$ podman login registry.redhat.io
----
+
Enter the user name and password:
+
[source,terminal]
----
Username: <username>
Password: <***********>
----

. Copy the binary `PATH` to enable system-wide use by running the following command:
+
[source,terminal]
----
$ podman cp $(podman create registry.redhat.com/mta-toolkit/mta-mta-cli-rhel9:{ProductVersion}):/usr/local/bin/mta-cli ./
----
+
[WARNING]
====
Although installation using Podman is possible, downloading and installing the `.zip` file is the preferred installation.
====

[NOTE]
====
Podman setup and configuration consists of numerous variables that are not within the scope of this documentation. For further details on Podman, see link:https://podman.io/docs#familiarizing-yourself-with-podman[Familiarizing yourself with Podman].

For details on troubelshooting Podman, see link:https://github.com/containers/podman/blob/main/troubleshooting.md[A list of common issues and solutions for Podman].
====

[id="installing-using-docker_{context}"]
== Installing the {CLINameTitle} for use with Docker on Windows (Developer Preview)

You can install the {CLINameTitle} for use with Docker on Windows. This is the required approach when migrating applications built with .NET framework 4.5 or later on Windows to cross-platform .NET 8.0.

.Prerequisites

* A host with Windows 11+ 64-bit version 21H2 or higher.

* You have download the Docker Desktop for Windows installer. See link:https://docs.docker.com/desktop/install/windows-install/[Install Docker Desktop on Windows] for additional details.

.Procedure

. Open a PowerShell with Administrator privileges.

. Ensure Hyper-V is installed and enabled:
+
[source,powershell]
----
PS C:\Users\<your_user_name>> Enable-WindowsOptionalFeature -Online `
   -FeatureName Microsoft-Hyper-V-All
----
+
[source,powershell]
----
PS C:\Users\<your_user_name>> Enable-WindowsOptionalFeature -Online `
   -FeatureName Containers
----
+
[NOTE]
====
You may need to reboot Windows.
====

. Install Docker Desktop on Windows.

.. Double-click `Docker_Desktop_Installer.exe` to run the installer. By default, Docker Desktop is installed at `C:\Program Files\Docker\Docker`.

.. Deselect the *Use WSL 2 instead of Hyper-V* option on the Configuration page to ensure that Docker will run Windows containers as the backend instead of Linux containers.

. In PowerShell, create a folder for {ProductShortName}:
+
[source,powershell]
----
PS C:\Users\<your_user_name>> mkdir C:\Users\<your_user_name>\MTA
----
+
Replace `<your_user_name>` with the username for your home directory.

. Extract the `{ProductShortNameLower}-{ProductVersion}-cli-windows.zip` file to the `MTA` folder:
+
[source,powershell]
----
PS C:\Users\<your_user_name>> cd C:\Users\<your_user_name>\Downloads
----
+
Replace `<your_user_name>` with the username for your home directory.
+
[source,powershell]
----
PS C:\Users\<your_user_name>> Expand-Archive `
   -Path "{ProductShortNameLower}-{ProductVersion}-cli-windows.zip" `
   -DestinationPath "C:\Users\<your_user_name>\MTA"
----
+
Replace `<your_user_name>` with the username for your home directory.

. Ensure Docker is running Windows containers:
+
[source,powershell]
----
PS C:\Users\<your_user_name>> docker version
----
+
[source,powershell]
----
Client:
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:03:32 2024
 OS/Arch:           windows/amd64 <1>
 Context:           desktop-windows
Server: Docker Desktop 4.32.0 (157355)
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:13 2024
  OS/Arch:          windows/amd64 <1>
  Experimental:     false
----
<1> Ensure the `OS/Arch` setting is `windows/amd64`.

. Set the `PODMAN_BIN` environment variable to use Docker:
+
[source,powershell]
----
PS C:\Users\<your_user_name>> $env:PODMAN_BIN="C:\Windows\system32\docker.exe"
----

. Set the `DOTNET_PROVIDER_IMG` environment variable to use the upstream `dotnet-external-provider`:
+
[source,powershell]
----
PS C:\Users\<your_user_name>> $env:DOTNET_PROVIDER_IMG="quay.io/konveyor/dotnet-external-provider:v0.5.0"
----

. Set the `RUNNER_IMG` environment variable to use the upstream image:
+
[source,powershell]
----
PS C:\Users\<your_user_name>> $env:RUNNER_IMG="quay.io/konveyor/kantra:v0.5.0"
----
