// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_content-type: PROCEDURE
[id="installing-mta-disconnected-environment_{context}"]
= Installing {ProductShortName} on a disconnected environment

When your system is in a disconnected environment, you can install the Migration Toolkit for Applications (MTA) command-line interface (CLI) by using an external computer to download the required images and by copying these images to the system you want to install MTA CLI on.

IMPORTANT: The following procedure applies only to container mode.


NOTE: The analysis output in the disconnected environment usually results in less incidents because a dependency analysis does not run accurately without access to Maven.




On a connected device, first download and save the {ProductShortName} binary. Then download and save the Podman images, the {ProductShortName} CLI image and the provider image that you need.

* Download the required {ProductShortName} CLI binary from the link:https://developers.redhat.com/products/mta/download[{ProductName} Red Hat Developer page]:
** CLI for Linux x86_64 
** CLI for Linux aarch64
** CLI for MacOS x86_64
** CLI for MacOS aarch64
** CLI for Windows x86_64
** CLI for Windows aarch64

* On a connected device, download and save the images.

* Copy the binary to the disconnected device.

* In addition, you must save and import the associated container images by using Podman.

== Downloading the Podman images

.Prerequisites

* Podman installed. For more information, see link:https://podman.io/[Podman].

.Procedure

. Use Podman to authenticate to link:registry.redhat.io[registry.redhat.io]:
+
[source,terminal]
----
$ podman login registry.redhat.io
----

. Enter your username and then your password for registry.redhat.io:
+
[source,terminal]
----
Username: <registry_service_account_username>
Password: <registry_service_account_password>
----
+
You should see the following output:
+
[source,terminal]
----
Login Succeeded!
----

. Use Podman to pull the image from the registry:
+
[source,terminal]
----
$ podman pull registry.redhat.io/mta/mta-cli-rhel9:7.1.0
----

. Use Podman to pull the provider image that you need from the registry:

.. For Java, run:
+
[source,terminal]
----
$ podman pull registry.redhat.io/mta/mta-java-external-provider-rhel9:7.1.0
----
.. For .NET, run:
+
[source,terminal]
----
$ podman pull registry.redhat.io/mta/mta-dotnet-external-provider-rhel9:7.1.0
----

. Save the images:
+
[source,terminal]
----
$ podman save <image> -o <my_image.image>
----

. Copy the `.image` file and the binary onto a USB or directly to the file system of the disconnected device.

. On the disconnected device, run
+
[source,terminal]
----
$ podman load --input <my_image.image>
----
