// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc
// * docs/getting-started-guide/master.adoc
// * docs/maven-guide/master.adoc
// * docs/eclipse-code-ready-studio-guide/master.adocs
// * docs/release-notes/release_notes-5.0/master.adoc
// * docs/release-notes/release_notes-5.1/master.adoc
// * docs/rules-development-guide/master.adoc
// * docs/web-console-guide/master.adoc

[preface]
:_mod-docs-content-type: CONCEPT
[id="making-open-source-more-inclusive"]
= Making open source more inclusive

[role="_abstract"]
Red Hat is committed to replacing problematic language in our code, documentation, and web properties. We are beginning with four terms: primary or source (instead of the former term), replica or responder (instead of the former term), blocklist (instead of the former term), and allowlist (instead of the former term). Because of the enormity of this endeavor, these changes will be implemented gradually over several upcoming releases. For more details, see link:https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language[our CTO Chris Wright's message].
