:_newdoc-version: 2.18.3
:_template-generated: 2024-07-30
:_mod-docs-content-type: CONCEPT

[id="mta-cli-generate-assets_{context}"]
= Generating platform assets for application deployment

Starting from {ProductShortName} 7.3.0, you can run the `discover` and `generate` commands in the containerless {ProductShortName} {CLIName}. The commands automatically generate the manifests needed to deploy a Cloud Foundry (CF) application in the {ocp-short}. 

* `Discover` command: Generates the discovery manifest in the YAML format from the CF application manifest. The discovery manifest preserves the specifications found in the CF manifest that define the metadata, runtime, and platform configurations.
* `Generate` command: Generates the deployment manifest for {ocp} deployments by using the discovery manifest. The deployment manifest is generated by using a templating engine such as Helm that converts the discovery manifest into a Kubernetes-native format.  

.Benefits of generating deployment assets by using the {ProductShortName} {CLIName}
* Extending the {ProductShortName} {CLIName} to generate the Kubernetes and non-Kubernetes deployment manifests at once.   
* Generating deployment manifests using familiar template engines like Helm that are widely used for Kubernetes deployments.
* Adhering to Kubernetes best practices when preparing the deployment manifest using Helm templates.

:FeatureName: Generating platform assets for application deployment
include::developer-preview-feature.adoc[]

[id="support-matrix_{context}"]
== Support matrix

* Source platform: Cloud Foundry (v3) 
* Target platform: {ocp-short}
* CLI tool: {ProductShortName} {CLIName} 7.3.0
* Status: Developer preview in 7.3.0
