// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_content-type: REFERENCE
[id="cli-args_{context}"]
= About {ProductShortName} command-line arguments

The following is a detailed description of the available {ProductShortName} command line arguments.

[NOTE]
====
To run the {ProductShortName} command without prompting, for example when executing from a script, you must use the following arguments:

* `--overwrite`
* `--input`
* `--target`
====

.{ProductShortName} CLI arguments
[%collapsible]
====
[width="100%",cols="30%,30%,65%",options="header",]
|====
|Command |Type|Description

a|`--analyze-known-libraries`
|
|Flag to analyze known open-source libraries.

a|`--bulk`
|
a|Flag for running multiple analyze commands in bulk, which result in a combined static report.

|`--context-lines`
|Integer
|Flag to define the number of lines of source code to include in the output for each incident (default: `100`).

a|`-d`, `--dependency-folders`
|String Array
|Flag for the directory for dependencies.

a|`--enable-default-rulesets`
|Boolean
a|Flag to run default rulesets with analysis (default: `true`).

a|`-h`, `--help`
|
|Flag to output help for analyze

a|`--http-proxy`
| String
| Flag for Hyper Text Transfer Protocol (HTTP) proxy string URL

a|`--https-proxy`
| String
| Flag for Hypertext Transfer Protocol Secure (HTTPS) proxy string URL

a|`--incident-selector`
|String
a|Flag to select incidents based on custom variables, for example, `!package=io.konveyor.demo.config-utils`

a|`-i`, `--input`
|String
a|Flag for the path to application source code or a binary. For more details, see xref:cli-input-argument_cli-guide[Specifying the input].

a|`--jaeger-endpoint`
|String
|Flag for the jaeger endpoint to collect traces.

a|`--json-output`
|
a|Flag to create analysis and dependency output as JSON.

a|`--list-sources`
|
a|Flag to list rules for available migration sources.

a|`--list-targets`
|
|Flag to list rules for available migration targets.

a|`--list-providers`
|
|Flag to list available supported providers.

a|`-l`, `--label-selector`
|String
|Flag to run rules based on a specified label selector expression.

a|`--maven-settings`
|string
|Flag path to a custom Maven settings file to use

a|`-m`, `--mode`
|String
a|Flag for analysis mode, this must be one of `full`, for `source` and `dependencies`, or `source-only` (default `full`).

a|`-o`, `--output`
|String
|Flag for the path to the directory for analysis output. For more details, see xref:cli-output-argument_cli-guide[Specifying the output directory].

a|`--override-provider-settings`
|String
|Flag to override the provider settings. The analysis pod runs on the host network, and no providers are started.

a|`--overwrite`
|
|Flag to overwrite the output directory. If you do not specify this argument and the `--output` directory exists, you are prompted to choose whether to overwrite the contents.

a|`--provider`
|String Array
|Flag to specify which provider or providers to run.

a|`--rules`
|String Array
a|Flag to specify the filename or directory containing rule files. Use multiple times for additional rules, for example, `--rules --rules …`.

a|`--skip-static-report`
|
|Flag to not generate static report.

a|`-s`, `--source`
|String Array
a|Flag for the source technology to consider for analysis. Use multiple times for additional sources, for example, `--source --source …`. For more details, see xref:cli-source-argument_cli-guide[Setting the source technology].

a|`-t`, `--target`
|String Array
a|Flag for the target technology to consider for analysis. Use multiple times for additional targets, for example, `--target --target …`. For more details, see xref:cli-target-argument_cli-guide[Setting the target technology].
|====
====

[id="cli-input-argument_{context}"]
== Specifying the input

A space-delimited list of the path to the file or directory containing one or more applications to be analyzed. This argument is required.

.Usage
[source,options="nowrap",subs="attributes+"]
----
--input <INPUT_ARCHIVE_OR_DIRECTORY> [...]
----

Depending on whether the input file type provided to the `--input` argument is a file or directory, it will be evaluated as follows depending on the additional arguments provided.

Directory::
+
* `--sourceMode`: The directory is evaluated as a single application.

File::
+
* `--sourceMode`: The file is evaluated as a compressed project.


[id="cli-output-argument_{context}"]
== Specifying the output directory

Specify the path to the directory to output the report information generated by {ProductShortName}.

.Usage
[source,options="nowrap",subs="attributes+"]
----
--output <OUTPUT_REPORT_DIRECTORY>
----

* If omitted, the report will be generated in an `<INPUT_ARCHIVE_OR_DIRECTORY>.report` directory.
* If the output directory exists, you will be prompted with the following question with a default answer of `N`:
+
[source,options="nowrap",subs="attributes+"]
----
Overwrite all contents of "/home/username/<OUTPUT_REPORT_DIRECTORY>" (anything already in the directory will be deleted)? [y,N]
----

However, if you specify the `--overwrite` argument, {ProductShortName} will proceed to delete and recreate the directory. See the description of this argument for more information.

[id="cli-source-argument_{context}"]
== Setting the source technology

A space-delimited list of one or more source technologies, servers, platforms, or frameworks to migrate from. You can use this argument, in conjunction with the `--target` argument, to determine which rulesets are used. Use the `--listSourceTechnologies` argument to list all available sources.

.Usage
[source,options="nowrap",subs="attributes+"]
----
--source <SOURCE_1> <SOURCE_2>
----

The `--source` argument now provides version support, which follows the link:http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html[Maven version range syntax]. This instructs {ProductShortName} to only run the rulesets matching the specified versions, for example, `--source eap:5`.

[WARNING]
====
When migrating to JBoss EAP, be sure to specify the version, for example, `eap:6`. Specifying only `eap` will run rulesets for all versions of JBoss EAP, including those not relevant to your migration path.

See link:{ProductDocIntroToMTAGuideURL}/index#migration_paths_getting-started-guide[Supported migration paths] in _{IntroToMTABookName}_ for the appropriate JBoss EAP version.
====

[id="cli-target-argument_{context}"]
== Setting the target technology

A space-delimited list of one or more target technologies, servers, platforms, or frameworks to migrate to. You can use this argument, in conjunction with the `--source` argument, to determine which rulesets are used. If you do not specify this option, you are prompted to select a target. Use the `--listTargetTechnologies` argument to list all available targets.

.Usage
[source,options="nowrap",subs="attributes+"]
----
--target <TARGET_1> <TARGET_2>
----


The `--target` argument now provides version support, which follows the link:http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html[Maven version range syntax]. This instructs {ProductShortName} to only run the rulesets matching the specified versions, for example, `--target eap:7`.
