// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_content-type: PROCEDURE
[id="cli-run_{context}"]
= Running the {CLINameTitle}

You can run {ProductShortName} against your application.

.Procedure

. Open a terminal and navigate to the `<{ProductShortName}_HOME>/` directory.

. Execute the `{mta-cli}` script, or `{mta-cli}.exe` for Windows, and specify the appropriate arguments:

+
[source,terminal,subs="attributes+"]
----
$ ./{mta-cli} analyze --input /path/to/jee-example-app-1.0.0.ear \
    --output /path/to/output --source weblogic --target eap6 \
----
+
* `--input`: The application to be evaluated.
* `--output`: The output directory for the generated reports.
* `--source`: The source technology for the application migration.

. Access the report.

[id="command-examples_{context}"]
== {ProductShortName} command examples

[discrete]
=== Running {ProductShortName} on an application archive

The following command analyzes the link:https://github.com/windup/windup/blob/master/test-files/jee-example-app-1.0.0.ear[jee-example-app-1.0.0.ear] example EAR archive for migrating from JBoss EAP 5 to JBoss EAP 7:

[source,terminal,subs="attributes+"]
----
$ <{ProductShortName}_HOME>/{mta-cli} analyze \
    --input /path/to/jee-example-app-1.0.0.ear \
    --output /path/to/report-output/ --source eap5 --target eap7
----
[]

[discrete]
=== Running {ProductShortName} on source code

The following command analyzes the link:https://github.com/windup/windup/tree/master/test-files/seam-booking-5.2[seam-booking-5.2] example source code for migrating to JBoss EAP 6.

[source,terminal,subs="attributes+"]
----

$ <{ProductShortName}_HOME>/{mta-cli} analyze --mode source-only --input /path/to/seam-booking-5.2/ \
    --output /path/to/report-output/ --target eap6 --packages org.jboss.seam
----
[]
[discrete]
=== Running cloud-readiness rules

The following command analyzes the link:https://github.com/windup/windup/blob/master/test-files/jee-example-app-1.0.0.ear[jee-example-app-1.0.0.ear] example EAR archive for migrating to JBoss EAP 7. It also evaluates for cloud readiness:

[source,terminal,subs="attributes+"]
----
$ <{ProductShortName}_HOME>/{mta-cli} analyze --input /path/to/jee-example-app-1.0.0.ear \
    --output /path/to/report-output/ \
    --target eap7
----
[]

[id="docker-command-examples_{context}"]
== Docker {ProductShortName} command examples (Developer Preview)

When migrating a Windows .NET 4.5 or later application to cross-platform .NET 8, use Docker Desktop on Windows to analyze the application.

.Procedure

. Run the Docker Desktop for Windows as an administrator.

. Open a PowerShell instance as an administrator.

. Navigate to the {ProductShortName} directory:
+
[source,powershell]
----
PS C:\Users\<your_user_name> cd C:\Users\<your_user_name>\MTA
----
+
Replace `<your_user_name>` with the username for your home directory.

. Create a directory for analysis output:
+
[source,powershell]
----
PS C:\Users\<your_user_name>\MTA> mkdir mta-output
----

. Copy your application to the {ProductShortName} directory. The following command clones the link:https://github.com/sixeyed/nerd-dinner[Nerd Dinner] application as an example application:
+
[source,powershell]
----
PS C:\Users\<your_user_name>\MTA> git clone https://github.com/sixeyed/nerd-dinner.git
----

. Analyze the application. The following command analyzes the link:https://github.com/sixeyed/nerd-dinner[Nerd Dinner] application for migrating from Windows .NET 4.5 or later to cross-platform .NET 8:
+
[source,powershell]
----
PS C:\Users\<your_user_name>\MTA> .\mta-cli.exe analyze `
    --input C:\Users\<your_user_name>\MTA\nerd-dinner\mvc4\ `
    --output C:\Users\<your_user_name>\MTA\mta-output\ `
    --overwrite --log-level 10 --label-selector konveyor.io/source=dotnetframework
----
+
Replace `<your_user_name>` with the username for your home directory.

. Review the analysis results:
+
[source,powershell]
----
PS C:\Users\<your_user_name>\MTA> start-process "msedge" `
    -ArgumentList "file:///C:/Users/<your_user_name>/MTA/mta-output/static-report/index.html"
----
+
Replace `<your_user_name>` with the username for your home directory.