// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_mod-doc-content-type: CONCEPT
[id="mta-cli-analyze_{context}"]
= Performing analysis using the command line

`Analyze` supports running source code and binary analysis using `analyzer-lsp`.

.To run analysis on application source code, run the following command:

[source,terminal,subs="attributes+"]
----
{mta-cli} analyze --input=<path_to_source_code> --output=<path_to_output_directory>
----

All flags:

[source,terminal,subs="attributes+"]
----
Analyze application source code

Usage:
  {mta-cli} analyze [flags]

Flags:

      --analyze-known-libraries           Analyze known open-source libraries.

      --context-lines (int)               Number of lines of source code to
                                          include in the output for each
                                          incident (default: `100`).

  -d, --dependency-folders (stringArray)  Directory for dependencies.
      --enable-default-rulesets           Run default rulesets with analysis
                                          (default: `true`).

  -h, --help                              Help for analyze.

      --http-proxy (string)               HTTP proxy string URL.

      --https-proxy (string)              HTTPS proxy string URL.

      --incident-selector (string)        An expression to select incidents
                                          based on custom variables.
                                          Example:
                                          !package=io.demo.config-utils

  -i, --input (string)                    Path to application source code or
                                          a binary.

      --jaeger-endpoint (string)          Jaeger endpoint to collect traces.

      --json-output                       Create analysis and dependency
                                          output as JSON.

      --list-sources                      List rules for available
                                          migration sources.

      --list-targets                      List rules for available
                                          migration targets.

  -l, --label-selector (string)           Run rules based on specified label
                                          selector expression.

      --maven-settings (string)           Path to the custom maven
                                          settings file to use.

      --overwrite                         Overwrite output directory.

      --skip-static-report                Do not generate the static report.

  -m, --mode (string)                     Analysis mode, must be one of
                                          `full` or `source-only`
                                          (default: `full`).

      --no-proxy (string)                 Proxy-excluded URLs
                                          (relevant only with proxy).

  -o, --output (string)                   Path to the directory for analysis
                                          output.

      --overwrite                         Overwrite output directory.

      --rules (stringArray)               Filename or directory containing
                                          rule files.

      --skip-static-report                Do not generate the static report.

  -s, --source (string)                   Source technology to consider
                                          for analysis.
                                          To specify multiple sources,
                                          repeat the parameter:
                                          `--source <source_1>
                                          --source <source_2>` etc.

  -t, --target (string)                   Target technology to consider
                                          for analysis.
                                          To specify multiple targets,
                                          repeat the parameter:
                                          `S--target <target_1>
                                          --target <target_2>` etc.


Global Flags:

      --log-level uint32                  Log level (default: 4).

      --no-cleanup                        Do not cleanup temporary resources.
----


[NOTE]
====
The list of flags above does not include the `--bulk` flag because the flag is only offered as part of a Developer Preview feature. That feature is described in xref:mta-cli-run-multiple-apps_{context}[Support for providing a single report when analyzing multiple applications on the CLI].
====
.Usage example

. Get an example application to run analysis on.
. List available target technologies.
+
[source,terminal,subs="attributes+"]
----
{mta-cli} analyze --list-targets
----
. Run an analysis with a specified target technology, for example `cloud-readiness`.
+
[source,terminal,subs="attributes+"]
----
{mta-cli} analyze --input=<path-to/example-applications/example-1> --output=<path-to-output-dir> --target=cloud-readiness
----
. Several analysis reports are created in your specified output path:
+
[source,terminal,subs="attributes+"]

----
$ ls ./output/ -1
analysis.log
dependencies.yaml
dependency.log
output.yaml
static-report
----
+
* `output.yaml` is the file that contains the issues report.
* `static-report` contains the static HTML report.
* `dependencies.yaml` contains a dependencies report.
