:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21
:_mod-docs-content-type: PROCEDURE

[id="adding-source-platform-application_{context}"]
= Adding a source platform in an application

[role="_abstract"]
You can associate applications that are created in {ProductShortName} with their Cloud Foundry (CF) instances. Associate an {ProductShortName} application with its Cloud Foundry (CF) instance by configuring the application's coordinates in the source platform. The specific coordinates vary depending on the source platform you select. For example, the coordinates for CF instances are *name* and *space*. 

.Prerequisites

* You configured at least one source platform instance in the *Administration* mode.

.Procedure

. In the {ProductShortName} user interface, select the *Migration* working mode.
. Click *Application Inventory* in the left menu bar.
. Click the edit icon ({icon-edit}). The *New application* dialog appears.
. In the form, enter the following information:
.. *Name*: A unique name for the new application.
.. *Description*: A short description of the application (optional).
.. *Business service*: A purpose of the application (optional).
.. *Tags*: Software tags that characterize the application.
.. *Owner*: A registered software owner from the drop-down list (optional).
.. *Contributors*: Contributors from the drop-down list (optional).
.. *Comments*: Relevant comments on the migrated application.
. Click *Source code* and enter the following fields:
.. *Repository type*: *Git* or *Subversion*.
.. *Source repository*: A URL of the repository where the software code is saved.
.. *Branch*: An application code branch in the repository (optional).
.. *Root path*: A root path inside the repository for the target application (optional).
