:_newdoc-version: 2.18.3
:_template-generated: 2024-11-15
:_mod-docs-content-type: PROCEDURE

[id="running-the-containerless-mta-cli_{context}"]
= Running the containerless CLI

You can perform an application analysis for Java applications by using the {ProductShortName} CLI that does not require installation of a container runtime. 

.Prerequisites

* You have OpenJDK version 17 or later installed on your system.
* You have Maven installed on your system.
* You have Gradle installed on your system.
* The `RUN_LOCAL` environmental variable is set to `true`:
+
----
RUN_LOCAL=true 
----
+
Note that if you do not set this variable to `true`, the analysis will run inside a container. 
+
IMPORTANT: The analysis for languages other than Java is not affected by the  RUN_LOCAL variable.

.Procedure

. Move the installed {ProductShortName} CLI `.zip` file to your `$PATH`:
+
[source,terminal,subs="attributes+"]
----
$ mv <mta_cli_zip>/<os>-kantra /usr/bin
----

. Move the requirements to the `.kantra` directory:
+
[source,terminal,subs="attributes+"]
----
$ mv $HOME/kantra.<os>.<arch> $HOME/.kantra
----

. Open a terminal and navigate to the directory where you installed the {ProductShortName} CLI.

. Run the application analysis:
+
[source,terminal,subs="attributes+"]
----
$ mta-cli analyze-bin --overwrite --input <path_to_input>  --output <path_to_output> --target <target_source>
----
+
The command arguments represent the following:

** `--overwrite`: Overwrites the output folder if it exists.	
** `--input`: The application to be analyzed. 
** `--output`: The output directory for the generated reports. 
** `--target`: The target technology for the application migration, for example, `eap8`. 		


[role="_additional-resources"]
.Additional resources

* xref:installing-downloadable-cli-zip_cli-guide[Installing the CLI .zip file]

