:_newdoc-version: 2.18.3
:_template-generated: 2024-11-15
:_mod-docs-content-type: PROCEDURE

[id="running-the-containerless-mta-cli_{context}"]
= Running the containerless CLI

Starting from {ProductShortName} 7.2.0, you can perform an application analysis for Java applications by using the {ProductShortName} CLI that does not require installation of a container runtime. 

[IMPORTANT]
==== 
In {ProductShortName} 7.2.0 and later, containerless CLI is a default mode. To enable container runtime usage, you must set the `--run-local` flag to `false`:

----
--run-local=false
----
====

.Prerequisites

* You have OpenJDK version 17 or later installed on your system.
* You have Maven installed on your system.
* The CLI assumes that a path to the `mvn` binary is correctly registered in the system variable. Therefore, ensure that you added `mvn` to the following variable:
** `Path` for Windows.
** `PATH` for Linux and macOS.
* You have the `python3` package installed on your system.
* You have the `JAVA_HOME` environmental variable set.
* You have the `JVM_MAX_MEM` system variable set.
+
NOTE: If you do not set `JVM_MAX_MEM`, the analysis might hang.

.Procedure

. Move the installed {ProductShortName} CLI `.zip` file to your `$PATH`:
+
[source,terminal,subs="attributes+"]
----
$ mv <mta_cli_zip>/<os>-kantra /usr/bin
----

. Move the requirements to the `.kantra` directory:
+
[source,terminal,subs="attributes+"]
----
$ mv $HOME/kantra.<os>.<arch> $HOME/.kantra
----
+
NOTE: The CLI can run with the requirements moved to the directory from which you run an analysis. During the analysis, the CLI looks for the requirements in this directory first, and if it does not find the requirements, it looks for them in the `$HOME/.kantra` directory.


. Optional: Display all `mta-cli analyze` command options:
+
[source,terminal,subs="attributes+"]
----
mta-cli analyze --help
----

. Run the application analysis:
+
[source,terminal,subs="attributes+"]
----
$ mta-cli analyze --overwrite --input <path_to_input>  --output <path_to_output> --target <target_source>
----
+
The command arguments represent the following:

** `--overwrite`: Overwrites the output folder if it exists.	
** `--input`: The application to be analyzed. 
** `--output`: The output directory for the generated reports. 
** `--target`: The target technology for the application migration, for example, `eap8`.


[role="_additional-resources"]
.Additional resources

* xref:installing-downloadable-cli-zip_cli-guide[Installing the CLI .zip file]

