:_newdoc-version: 2.15.0
:_template-generated: 2024-2-21
:_mod-docs-content-type: PROCEDURE

[id="creating-source-platform_{context}"]
= Creating a source platform in {ProductShortName} {WebName}

[role="_abstract"]
Create a source platform instance to retrieve platform and runtime configurations for one or more applications. 

A platform engineer, who has administrator privileges to access Cloud Foundry (CF), can configure one or more CF platform instances in the {ProductShortName} user interface. 

.Prerequisites
//should the users be logged in to the CF instance for application discovery?

* The {ProductShortName} administrator created a *Source Control* credential of the CF platform in the *Administration* mode.

.Procedure

. In the {ProductShortName} user interface, select the *Administration* working mode.
. Click *Source platform* in the left menu bar to go to the *Source platforms* page.
. Click *Create new platform*. The *Create new platform* dialog appears.
. In the form, enter the following information:
.. *Name*: A unique name for the CF instance.
.. *Type*: Select *Cloud Foundry* from the drop down menu.
.. *URL*: API URL to the source platform.
.. *Credentials*: Select the name of the source platform credentials that you configured.
. Click *Create*.
+
The source platform instance is created. A source platform instance can be linked with one or more applications.