:_newdoc-version: 2.18.3
:_template-generated: 2025-04-29

:_mod-docs-content-type: REFERENCE

[id="known-issues-7-3-2_{context}"]
= Known issues

This section provides highlighted known issues in {ProductFullName} version 7.3.2.

.{ProductShortName} {WebName} connection breaks when you sort dependencies by labels after an analysis

When you sort the dependencies by labels after analyzing an application in the {ProductShortName} {WebName}, the {WebName} displays an error about retrieving data. Currently, there is no workaround available. link:https://issues.redhat.com/browse/MTA-5981[(MTA-5981)]

.Analysis performance may degrade in a disconnected environment or when Maven central is not available
When you run an analysis by using the {ProductShortName} on a host with no access to Maven central and without disabling the Maven search index (`--disable-maven-search=false`), the analysis performance may degrade, as {ProductShortName} tries to access it. 

As a workaround, Maven search can be disabled: you can manually set `--disable-maven-search=true` for CLI analysis and set `disable_maven_search: true` in the Tackle custom resource of the {ProductShortName} operator for an analysis in the {Webname}. link:https://issues.redhat.com/browse/MTA-6045[(MTA-6045)]


.An application analysis lasts longer when Maven credentials are missing

If you do not manually assign Maven credentials to an application that requires them or do not set these credentials as default, an application analysis might last longer. In addition, the Analyzer and Tech Discovery steps complete with the following error:

----
error: 'unable to ask for Konveyor rule entry'
----

To work around this problem, assign Maven credentials to the application or set these credentials as default before running the application analysis.
