:_newdoc-version: 2.18.3
:_template-generated: 2025-02-12

:_mod-docs-content-type: REFERENCE

[id="resolved-issues-7-2-1_{context}"]
= Resolved issues

This section provides highlighted issues that have been resolved in {ProductFullName} 7.2.1.

.OpenRewrite CMD now properly mounts the settings file

The {ProductFullName} CLI not only analyzes source code but also transforms it to adopt a particular technology. To transform the code, {ProductShortName} can use an external settings file, for example, to access the Maven repository. In such cases, this file must be mounted to a running container where the analysis engine will run. 

Previously, this file could not be mounted. As a result, the transformation operation failed. With this update, the issue has been fixed, and the file is now properly mounted to the running container. link:https://issues.redhat.com/browse/MTA-4553[(MTA-4553)]




.The application analysis no longer fails on RHEL 8 

Previously, when you ran the application analysis with the {ProductShortName} 7.2.0 version on RHEL 8 systems, the analysis failed with the `version `GLIBC_2.32' not found` error. With this update, the issue has been resolved, and the application analysis no longer fails for RHEL 8. link:https://issues.redhat.com/browse/MTA-4634[(MTA-4634)]
