:_newdoc-version: 2.18.5
:_template-generated: 2025-09-09
:_mod-docs-content-type: REFERENCE

[id="known-issues-8-0_{context}"]
= Known issues

{ProductFullName} version 8.0.0 is affected by the following newly identified and previously known issues. A known issue is listed in all future release notes until resolved, at which point it is published as a fixed issue.


.Application analysis with {ProductShortName} CLI might fail with the "invalid header line" error

An application analysis by using the {ProductFullName} command-line interface (CLI) might fail with the following error message:

----
level=error msg="initialize failed" error="context canceled" provider=java
error="invalid header line "An error has occurred. See the log file"
----

To work around this problem, clean up metadata and cache:

. Clear the `.metadata` subdirectory under the directory from which you ran the `mta-cli analyze` command.
. Clear the Maven cache.

(link:https://issues.redhat.com/browse/MTA-6125[MTA-6125])

.{ProductShortName} analysis result does not change based on the addition or removal of a custom rule 

When you use Developer Lightspeed for {ProductShortName}, the analysis results do not change based on the inclusion or removal of a custom rule. If you remove a custom rule after the first analysis, subsequent analysis results detect the incident for the custom rule. Conversely, if you add the custom rule after the first analysis, subsequent analysis does not detect the incident based on the custom rule. link:https://issues.redhat.com/browse/MTA-6128[MTA-6128]
//https://issues.redhat.com/browse/MTA-6126

//TBD by Prabha - Custom rules KI
https://issues.redhat.com/browse/MTA-6129
