:_newdoc-version: 2.18.3
:_template-generated: 2025-05-12

:_mod-docs-content-type: REFERENCE

[id="fixed-issues-7-3-1_{context}"]
= Fixed issues

This section provides the following bug fixes and resolves issues and other problems that have a significant impact on the {ProductFullName} 7.3.1.

.{ProductShortName} now triggers custom rules for application analysis
Previously, {ProductShortName} did not trigger custom rules when analyzing applications. This issue has been resolved in {ProductShortName} 7.3.1. link:https://issues.redhat.com/browse/MTA-4885[(MTA-4885)] 

.{ProductShortName} now analyzes Java applications without false positives
Previously, {ProductShortName} sometimes generated false positive by matching 'line 1' of a Java file. This issue has been resolved in {ProductShortName} 7.3.1. link:https://issues.redhat.com/browse/MTA-4918[(MTA-4918)]

.{ProductShortName} now generates consistent reports after containerized and local analysis of Java applications 
Previously, {ProductShortName} generated reports with different number of issues after analyzing Java applications in containerized and containerless modes. This issue has been resolved in {ProductShortName} 7.3.1. link:https://issues.redhat.com/browse/MTA-5090[(MTA-5090)]

.{ProductShortName} now analyzes non-Java applications in containerized mode
Previously, {ProductShortName} analyzed non-Java applications in containerless mode unless the `--run-local` flag was manually set to `false`. This issue has been resolved in {ProductShortName} 7.3.1. link:https://issues.redhat.com/browse/MTA-5068[(MTA-5068)]

.{ProductShortName} {CLIName} now lists languages for binary applications
Previously, the `--list-languages` flag did not list languages for binary applications in the {ProductShortName} {CLIName}. This issue has been resolved in {ProductShortName} 7.3.1. link:https://issues.redhat.com/browse/MTA-5089[(MTA-5089)]

.Custom rules are now triggered for applications without the `pom` file
Previously, {ProductShortName} {ProductShortName} did not trigger custom rules for applications without the `pom` file. This issue has been resolved in {ProductShortName} 7.3.1. link:https://issues.redhat.com/browse/MTA-5049[MTA-5049]