// Module included in the following assemblies:
//
//docs/release_notes-7.2.0/master.adoc

:_template-generated: 2024-12-04
:_mod-docs-content-type: REFERENCE

[id="resolved-issues-7-2-3_{context}"]
= Fixed issues

This section provides highlighted issues that have been resolved in {ProductFullName} 7.2.3.

.{ProductShortName} creates resources with auto-assigned IDs after creating RESTful resources with specific IDs
Previously in {ProductShortName}, when a resource was created with a specific ID through a REST call, after which another resource was created with an auto-assigned ID, either through a REST call or in the user interface, an `http-409` conflict could occur. This issue has been resolved in {ProductShortName} 7.2.3. link:https://issues.redhat.com/browse/MTA-5288[(MTA-5288)]

.{ProductShortName} now runs Java rules when analyzing Java binaries on Microsoft Windows
Previously, when you performed a containerless analysis of compiled Java applications using Microsoft Windows, {ProductShortName} did not match a Java rule and generated a `Java Model (code 969)` error. As a result, some rules did not trigger issues in the analysis report. This issue has been resolved in {ProductShortName} 7.2.3. link:https://issues.redhat.com/browse/MTA-5370[(MTA-5370)]

.Resources and limits now present on all pods
In {ProductShortName} 7.2.3, all pods created by the `mta-operator`, and the pod for the operator itself, have resource limits and requests set. This way they also work in an environment where resource limits and requests are required, for example, when a project has resource quotas defined. link:https://issues.redhat.com/browse/MTA-5406[(MTA-5406)]
