:_newdoc-version: 2.18.3
:_template-generated: 2025-04-17

:_mod-docs-content-type: REFERENCE

[id="new-features-7-3-0_{context}"]
= New features

This section provides the new features and improvements of the {ProductFullName} 7.3.0. 


.Asset generation is now available in {ProductShortName} CLI

Starting with {ProductShortName} {ProductVersion}, you can run the `discover` and `generate` commands in the {CLIName}: 

* The `discover` command generates the discover manifest that preserves the platform and runtime configurations defined in the Cloud Foundry (CF) application manifest.
* The `generate` command uses the discover manifest to generate the deployment manifest in a Kubernetes-native format to prepare it for {ocp-full} deployments.

(link:https://issues.redhat.com/browse/MTA-4610[MTA-4610])

.{ProductShortName} now uses Red Hat Build of Keycloak for user authentication

{ProductShortName} {ProductVersion} now uses `{rhbk-first}` instance for user authentication and authorization. The {ProductShortName} Operator manages the `{rhbk-short}` instance and configures a dedicated realm with necessary roles and permissions. For `{rhbk-short}`, the secret and the pod name has changed. The pod name for {rhbk-short} is changed to `rhbk-operator`. (link:https://issues.redhat.com/browse/MTA-4540[MTA-4540])

.Listing all languages in an application is now supported

In {ProductShortName} {ProductVersion}, you can list all languages in an application by using the `--list-languages` flag in the {CLIName}. The listed language that has no supported providers requires a custom rule set and the --`override-provider-settings` flag when you analyze the application.