// Module included in the following assemblies:
//
//docs/release_notes-7.2.0/master.adoc


:_mod-docs-content-type: REFERENCE

[id="resolved-issues-7-2-0_{context}"]
= Resolved issues

This section provides highlighted issues that have been resolved in {ProductFullName} 7.2.0.

.{ProductShortName} azure-appservice target is missing

In previous versions of {ProductShortName}, the `azure-appservice` target was not available in the CLI distribution of {ProductFullName}. This issue has been resolved in the {ProductShortName} CLI. link:https:https://issues.redhat.com/browse/MTA-4036[(MTA-4036)]

.Application analysis no longer fails when dependency analysis failures occur

Previously, the application analysis failed due to a dependency analysis issue, even when the source code analysis was successful, resulting in no static report being generated. This issue has been resolved now in the {ProductShortName} CLI. (link:https:https://issues.redhat.com/browse/MTA-3700[MTA-3700])

.Improved container naming

Previously, container names contained random letters, making their identification difficult. The issue has been resolved in {ProductShortName} 7.1.1, where container names now have readable prefixes for easier identification. (link:https:https://issues.redhat.com/browse/MTA-3133[MTA-3133])

// https://issues.redhat.com/issues/?filter=12447517
