// Module included in the following assemblies:
//
//docs/release_notes-7.2.0/master.adoc

:_template-generated: 2024-12-04
:_mod-docs-content-type: REFERENCE

[id="resolved-issues-7-2-0_{context}"]
= Resolved issues

This section provides highlighted issues that have been resolved in {ProductFullName} 7.2.0.

.Tags are not accessible in SVN repositories

In previous versions of {ProductShortName}, when retrieving source code from Subversion (SVN) repositories, addons were automatically adding `/trunk` or `/branches/<target_branch>` to the repository URL, making it impossible to check out anything under tags. This issue has been resolved in the {ProductShortName} 7.2.0. link:https://issues.redhat.com/browse/MTA-4236[(MTA-4236)]

.Application import fails when Business Services exist already

In previous versions of {ProductShortName}, importing applications using a CSV after a previous import that created Business Services led to the newly created applications having the incorrect Business Services assigned. This issue has been resolved in the {ProductShortName} 7.2.0. link:https://issues.redhat.com/browse/MTA-4257[(MTA-4257)]

.{ProductShortName} CLI fails to handle `--bulk` properly on Windows platform

In previous versions of {ProductShortName}, the bulk analysis on Windows systems could not be performed. This issue has been resolved now in the {ProductShortName} CLI. link:https://issues.redhat.com/browse/MTA-3624[(MTA-3624)]

.IntelliJ IDEA target list showed unusable targets

In previous versions of {ProductShortName}, selecting `cloud` as a target resulted in an _unknown target_ error. This issue has been resolved in the {ProductShortName} 7.2.0. link:https://issues.redhat.com/browse/MTA-4035[(MTA-4035)]

.Maven insecure setting not functioning as expected

In previous versions of {ProductShortName}, the _global_ Maven setting to *Consume insecure repositories* was no longer passed to Maven. As a result, Maven failed when using Hyper Text Transfer Protocol (HTTP) repositories. This failure was a regression bug introduced when the Maven functionality was moved to the Java provider. This issue has been resolved in the {ProductShortName} 7.2.0. link:https://issues.redhat.com/browse/MTA-4418[(MTA-4418)]

.SVN Checkout fails when filenames have special characters

In previous versions of {ProductShortName}, the Subversion (SVN) client failed when attempting a checkout operation in a repository that contained files with special characters, accents, in their filenames. This issue has been resolved in the {ProductShortName} 7.2.0. link:https://issues.redhat.com/browse/MTA-4309[(MTA-4309)]

For a complete list of all resolved issues, see the list of link:https://issues.redhat.com/issues/?filter=12447875[{ProductShortName} 7.2.0 resolved issues] in Jira.
