// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: REFERENCE
[id="yaml-rule-structure-syntax_{context}"]
= YAML rule structure and syntax

{ProductShortName} rules are written in YAML. Each rule consists of metadata, conditions and actions, which instruct the analyzer to take specified actions when given conditions match.

A YAML rule file in {ProductShortName} contains one or more YAML rules.

[id="yaml-rule-metadata_{context}"]
== Rule metadata

Rule metadata contains general information about the rule. The structure of metadata is as follows:

[source,terminal]
----
ruleId: "unique_id" <1>
labels: <2>
  # key=value pair
  - "label1=val1"
  # valid label with value omitted
  - "label2"
  # valid label with empty value
  - "label3="
  # subdomain prefixed key
  - "konveyor.io/label1=val1"
effort: 1 <3>
category: mandatory <4>
----
<1> The ID must be unique within the ruleset to which the rule belongs.
<2> See below for a description of the label format.
<3> `effort` is an integer value that indicates the level of effort needed to fix this issue.
<4> `category` describes the severity of the issue for migration. The value can be either `mandatory`, `optional` or `potential`. For a description of these categories, see xref:yaml-rule-categories_{context}[Rule categories].

[id="yaml-rule-labels_{context}"]
=== Rule labels

Labels are `key=val` pairs specified for rules or rulesets as well as dependencies. For dependencies, a provider adds the labels to the dependencies when retrieving them. Labels on a ruleset are automatically inherited by all the rules that belong to it.

.Label format

Labels are specified under the `labels` field as a list of strings in `key=val` format as follows:

[source,terminal]
----
labels:
- "key1=val1"
- "key2=val2"
----

The key of a label can be subdomain-prefixed:

[source,terminal]
----
labels:
- "konveyor.io/key1=val1"
----

The value of a label can be empty:

[source,terminal]
----
labels:
- "konveyor.io/key="
----

The value of a label can be omitted. In that case, it is treated as an empty value:

[source,terminal]
----
labels:
- "konveyor.io/key"
----

.Reserved labels

The analyzer defines some labels that have special meaning as follows:

* `konveyor.io/source`: Identifies the source technology to which a rule or a ruleset applies

* `konveyor.io/target`: Identifies the target technology to which a rule or a ruleset applies

.Label selector

The analyzer CLI takes the `--label-selector` field as an option. It is a string expression that supports logical AND, OR and NOT operations. You can use it to filter-in or filter-out rules by their labels.

_Examples:_

* To filter-in all rules that have a label with the key `konveyor.io/source` and value `eap6`:
+
`--label-selector="konveyor.io/source=eap6"`

* To filter-in all rules that have a label with the key `konveyor.io/source` and any value:
+
`--label-selector="konveyor.io/source"`

* To perform logical AND operations on matches of multiple rules using the `&&` operator:
+
`--label-selector="key1=val1 && key2"`

* To perform logical OR operations on matches of multiple rules using the `||` operator:
+
`--label-selector="key1=val1 || key2"`

* To perform a NOT operation to filter-out rules that have `key1=val1` label set using the `!` operator:
+
`--label-selector="!key1=val1"`

* To group sub-expressions and control precedence using AND:
+
`--label-selector="(key1=val1 || key2=val2) && !val3"`

.Dependency labels

The analyzer engine adds labels to dependencies. These labels provide additional information about a dependency, such as its programming language and whether the dependency is open source or internal.

Currently, the analyzer adds the following labels to dependencies:

[source,terminal]
----
labels:
- konveyor.io/dep-source=internal
- konveyor.io/language=java
----

.Dependency label selector

The analyzer CLI accepts the `--dep-label-selector` option, which allows filtering-in or filtering-out incidents generated from a dependency by their labels.

For example, the analyzer adds a `konveyor.io/dep-source` label to dependencies with a value that indicates whether the dependency is a known open source dependency.

To exclude incidents for all such open source dependencies, you can use `--dep-label-selector` as follows:

`konveyor-analyzer ... --dep-label-selector !konveyor.io/dep-source=open-source`

The Java provider in the analyzer can also add an exclude label to a list of packages. To exclude all such packages, you can use `--dep-label-selector` and the `!` operator as follows:

`konveyor-analyzer ... --dep-label-selector !konveyor.io/exclude`

[id="yaml-rule-categories_{context}"]
=== Rule categories

* `mandatory`
** You must resolve the issue for a successful migration, otherwise, the resulting application is not expected to build or run successfully. An example of such an issue is proprietary APIs that are not supported on the target platform.
* `optional`
** If you do not resolve the issue, the application is expected to work, but the results might not be optimal. If you do not make the change at the time of migration, you need to put it on the schedule soon after your migration is completed. An example of such an issue is EJB 2.x code not upgraded to EJB 3.
* `potential`
** You need to examine the issue during the migration process, but there is not enough information to determine whether resolving the issue is mandatory for the migration to succeed. An example of such an issue is migrating a third-party proprietary type when there is no directly compatible type on the target platform.


[id="yaml-rule-actions_{context}"]
=== Rule Actions

Rules can include 2 types of actions: _message_ and _tag_. Each rule includes one of them or both.

.Message actions

A message action creates an issue with a message when the rule matches. The custom data exported by providers can also be used in the message.

`message: "helpful message about the issue"`

_Example:_

[source,terminal]
----
- ruleID: test-rule
  when:
    <CONDITION>
  message: Test rule matched. Please resolve this migration issue.
----

Optionally, a message can include hyperlinks to external URLs that provide relevant information about the issue or a quick fix.

[source,terminal]
----
links:
  - url: "konveyor.io"
    title: "Short title for the link"
----

A message can also be a template to include information about the match interpolated through custom variables on the rule.

.Tag actions

A tag action instructs the analyzer to generate one or more tags for the application when a match is found. Each string in the `tag` field can be a comma-separated list of tags. Optionally, you can assign categories to tags.

[source,terminal]
----
tag:
  - "tag1,tag2,tag3"
  - "Category=tag4,tag5"
----

_Example_

[source,terminal]
----
- ruleID: test-rule
  when:
    <CONDITION>
  tag:
  - Language=Golang
  - Env=production
  - Source Code
----

A tag can be a string or a `key=val` pair, where the key is treated as a tag category in {ProductShortName}. Any rule that has a tag action is referred to as a “tagging rule” in this document.

Note that issues are not created for rules that contain only tag actions.


[id="yaml-rule-conditions_{context}"]
=== Rule conditions

Each rule has a `when` block, which specifies a condition that needs to be met for {ProductShortName} to perform a certain action.

The `when` block contains one condition, but that condition can have multiple conditions nested under it.

[source,terminal]
----
when:
  <condition>
    <nested-condition>
----

{ProductShortName} supports three types of conditions: `provider`, `and`, and `or`.

[id="yaml-provider-conditions_{context}"]
== Provider conditions

The Application Analyzer detects the programming languages, frameworks, and tools used to build an application, and it generates default rulesets for each supported provider using the Language Server Protocol (LSP) accordingly.
Each supported provider has a ruleset defined by default and is run independently in a separate container.

{ProductShortName} supports multi-language source code analysis. Searching for a specific language in the source code is enabled using the `provider` condition. This condition defines a search query for a specific language provider. The `provider` condition also specifies which of the provider's "capabilities" to use for analyzing the code.

The `provider` condition has the form `<provider_name>.<capability>`:

[source,terminal]
----
when:
  <provider_name>.<capability>
    <input_fields>
----

The analyzer currently supports the following `provider` conditions:

* `builtin`
* `java`
* `go`
* `dotnet`
+
:FeatureName: dotnet provider
include::technology-preview.adoc[]

[[table-Supported-providers-and-rule-conditions]]
[options="header"][cols="99,99,99,99"][%autowidth]
|===

|Provider rule conditions |Provider name

| Providers that are fully supported and included in the product
| Java

| Providers that have rules already defined in the product
| .NET

|Providers that require custom rulesets for analysis
a|
* Go
* Python
* Node.js
|===

[id="yaml-builtin-provider_{context}"]
=== `builtin` provider

`builtin` is an internal provider that can analyze various files and internal metadata generated by the engine.

This provider has the following capabilities:

* `file`
* `filecontent`
* `xml`
* `json`
* `hasTags`

.`file`

The `file` capability enables the provider to search for files in the source code that match a given pattern.

[source,terminal]
----
when:
  builtin.file:
    pattern: "<regex_to_match_filenames>"
----

.`filecontent`

The `filecontent` capability enables the provider to search for content that matches a given pattern.

[source,terminal]
----
when:
  builtin.filecontent:
    filePattern: "<regex_to_match_filenames_to_scope_search>"
    pattern: "<regex_to_match_content_in_the_matching_files>"
----

.`xml`

The `xml` capability enables the provider to query XPath expressions on a list of provided XML files. This capability takes 2 input parameters, `xpath` and `filepaths`.

[source,terminal]
----
when:
  builtin.xml:
    xpath: "<xpath_expressions>" <1>
    filepaths: <2>
      - "/src/file1.xml"
      - "/src/file2.xml"
----
<1> `xpath` must be a valid XPath expression.
<2> `filepaths` is a list of files to apply the XPath query to.

.`json`

The `json` capability enables the provider to query XPath expressions on a list of provided JSON files. Currently, `json` only takes XPath as input and performs the search on all JSON files in the codebase.

[source,terminal]
----
when:
  builtin.json:
    xpath: "<xpath_expressions>" <1>
----
<1> `xpath` must be a valid XPath expression.

.`hasTags`

The `hasTags` capability enables the provider to query application tags. It queries the internal data structure to check whether the application has the given tags.

[source,terminal]
----
when:
  # when more than one tag is given, a logical AND is implied
  hasTags: <1>
    - "tag1"
    - "tag2"
----
<1> When more than one tag is given, a logical AND is implied.

[id="yaml-java-provider_{context}"]
=== `java` provider

The Language Server used by the Java provider is Eclipse’s JDT Language Server (JDTLS). Internally, the JDTLS uses the Eclipse Java Development Toolkit, which includes utilities for searching code in projects.

This provider has the following capabilities:

* `referenced`
* `dependency`

In the `pattern` element of a `java.referenced` condition, you can search through application code by using these utilities. For more details, see link:https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fsearch%2FSearchPattern.html&anchor=createPattern[Class SearchPattern], which  contains all the information for building these patterns for `createPattern(String, int, int, int)`.


.`referenced`

The `referenced` capability enables the provider to find references in the source code. This capability takes three input parameters: `pattern`, `location`, and `annotated`.

[source,terminal]
----
when:
  java.referenced:
    pattern: "<pattern>" <1>
    location: "<location>" <2>
    annotated: "<annotated>" <3>
----
<1> A regular expression pattern to match, for example, `org.kubernetes*`.
<2> Specifies the exact location where the pattern needs to be matched, for example, `IMPORT`.
<3> Checks for specific annotations and their elements, such as name and value in the Java code using a query. For example, the following query matches the Bean(url = “http://www.example.com”) annotation in the method.


.Examples

* Search for any class under the `javax.xml` package, occurring in any
location:
+
[source,yaml]
----
java.referenced:
  pattern: javax.xml*
----
+
[WARNING]
====
If you want to match using an asterisk `*` wildcard for a wider range of results, it is recommended to place it directly after the package, not after the dot:

For example:

* `pattern: javax.xml*`
+
and not:

* `pattern: javax.xml.*`
====

* Search for method declarations that return `java.lang.String`:
+
[source,yaml]
----
java.referenced:
  location: METHOD
  pattern: '* java.lang.String'
----

* Search for a method named "`method`" declared on `org.konveyor.MyClass`
that returns a `List` of a type that extends `java.lang.String`:
+
[source,yaml]
----
java.referenced:
  location: METHOD
  pattern: 'org.konveyor.Myclass.method(*) java.util.List<? extends java.lang.String>'
----

* Search for a class that implements `java.util.List`:
+
[source,yaml]
----
java.referenced:
  location: IMPLEMENTS_TYPE
  pattern: java.util.List
----

[id="yaml-java-locations_{context}"]
==== `java` locations

The Java provider allows scoping down the search to certain source code locations. You can scope down Java searches from any one of the following search locations:

* *IMPORT*: IMPORT allows for searches on class imports. It can either be used with a fully qualified domain name (FQDN) or an asterisk as a wildcard to allow for wider matches:
+
For example:
+
[source,yaml]
----
java.referenced:
  pattern: org.apache.lucene.search*
  location: IMPORT
----

+
This scope would match on each of these imports:
+
[source,java]
----
import org.apache.lucene.search.Query;
import org.apache.lucene.search.Sort;
import org.apache.lucene.search.SortField;
----
+
If you want to match using an asterisk `*` wildcard for a wider range of results, it is recommended to place it directly after the package, not after the dot:

** Use: `org.apache.lucene.search*`

** Do not use: `org.apache.lucene.search.*`


* *PACKAGE*: PACKAGE allows for searches on any usage of a package, be it in an import or used as part of a FQDN in the code:
+
[source,yaml]
----
java.referenced:
  pattern: org.apache.lucene.search*
  location: PACKAGE
----
+
This scope would match on both the import and the fully qualified usage:
+
[source,java]
----
import org.apache.lucene.search.*;
----
+
[source,java]
----
public class Test {
  private org.apache.lucene.search.Query query;
}
----
+
If you want to match using an asterisk `*` wildcard for a wider range of results, it is recommended to place it directly after the package, not after the dot.


* *CONSTRUCTOR_CALL* and *METHOD_CALL*: for matching constructors and methods, respectively. The pattern possibilities are varied, and it is possible to match against specific return types, arguments, and so on.
+
For instance, looking for a method named `method` declared in the `org.konveyor.MyClass` that returns a `List` of a type that extends `java.lang.String` and accepts a single parameter:
+
[source,yaml]
----
java.referenced:
  location: METHOD
  pattern: 'org.konveyor.Myclass.method(*) java.util.List<? extends java.lang.String>'
----

More information about the possibilities of these patterns can be found in the link:[Class SearchPattern section] of the Eclipse documentation, which contain all the required information for building these patterns.

[WARNING]
====
In the current release of {ProductShortName}, fully qualified static method matching does not function as expected.
====

* *TYPE*: matches against types in general, appearing anywhere.
* *INHERITANCE*: matches against a class inheriting from a given type.
* *ANNOTATION*: matches against annotations.
* *IMPLEMENTS_TYPE*: matches against any type implementing the given type.
* *ENUM_CONSTANT*: matches against `enum` constants.
* *RETURN_TYPE*: matches against a type being returned by a method.
* *VARIABLE_DECLARATION*: matches against a type being declared as a variable.
* *FIELD* (declaration): matches against a type appearing in a field declaration. It can be coupled with an annotation match, this being an annotation happening on the field.
* *METHOD*: matches against a given method declaration. It can be coupled with an annotation match.
* *CLASS* (declaration): matches against a given method declaration. It can be coupled with an annotation match.


===== `go` provider

The `go` provider analyzes Go source code. This provider's capabilities are `referenced` and `dependency`.

.`referenced`

The `referenced` capability enables the provider to find references in the source code.

[source,terminal]
----
when:
  go.referenced: "<regex_to_find_reference>"
----

.`dependency`

The `dependency` capability  enables the provider to find dependencies for an application.

[source,terminal]
----
when:
  go.dependency:
    name: "<dependency_name>" <1>
    upperbound: "<version_string>" <2>
    lowerbound: "<version_string>" <3>
----
<1> Name of the dependency to search for.
<2> Upper bound on the version of the dependency.
<3> Lower bound on the version of the dependency.

===== `dotnet` provider

The `dotnet` is an external provider used to analyze .NET and C# source code. Currently, the provider supports the `referenced` capability.

.`referenced`

The `referenced` capability enables the provider to find references in the source code.

[source,terminal]
----
when:
  dotnet.referenced:
    pattern: "<pattern>" <1>
    namespace: "<namespace>" <2>
----
<1> `pattern`: A regex pattern to match the desired reference. For example, HttpNotFound.
<2> `namespace`: Specifies the namespace to search within. For example, System.Web.Mvc.

==== Custom variables

Provider conditions can have associated custom variables. You can use custom variables to capture relevant information from the matched line in the source code. The values of these variables are interpolated with data matched in the source code. These values can be used to generate detailed templated messages in a rule's action (see xref:yaml-rule-actions_{context}[Message actions]). They can be added to a rule in the `customVariables` field:

[source,terminal]
----
- ruleID: lang-ref-004
   customVariables:
   - pattern: '([A-z]+)\.get\(\)' <1>
      name: VariableName <2>
    message: "Found generic call - {{ VariableName }}" <3>
  when:
      java.referenced:
          location: METHOD_CALL
          pattern: com.example.apps.GenericClass.get

----
<1> `pattern`: A regular expression pattern that is matched on the source code line when a match is found.
<2> `name`: The name of the variable that can be used in templates.
<3> `message`: A template for a message using a custom variable.


=== Logical conditions

The analyzer provides two basic logical conditions, `and` and `or`, which enable you to aggregate results of other conditions and create more complex queries.

==== `and` condition

The `and` condition performs a logical AND operation on the results of an array of conditions. An `and` condition matches when _all_ of its child conditions match.


[source,terminal]
----
when:
  and:
    - <condition1>
    - <condition2>
----

_Example_

[source,terminal]
----
when:
  and:
    - java.dependency:
        name: junit.junit
        upperbound: 4.12.2
        lowerbound: 4.4.0
    - java.referenced:
        location: IMPORT
        pattern: junit.junit
----

Conditions can also be nested within other conditions.

_Example_

[source,terminal]
----
when:
  and:
  - and:
    - go.referenced: "*CustomResourceDefinition*"
    - java.referenced:
        pattern: "*CustomResourceDefinition*"
  - go.referenced: "*CustomResourceDefinition*"
----

==== `or` condition

The `or` condition performs a logical OR operation on the results of an array of conditions. An `or` condition matches when _any_ of its child conditions matches.

[source,terminal]
----
when:
  or:
    - <condition1>
    - <condition2>
----

_Example_

[source,terminal]
----
when:
  or:
  - java.dependency:
      name: junit.junit
      upperbound: 4.12.2
      lowerbound: 4.4.0
  - java.referenced:
      location: IMPORT
      pattern: junit.junit
----

== Rulesets

A set of rules forms a ruleset. {ProductShortName} does not require every rule file to belong to a ruleset, but you can use rulesets to group multiple rules that achieve a common goal and to pass the rules to the rules engine.

You can create a ruleset by placing one or more YAML rules in a directory and creating a `ruleset.yaml` file at the directory root. When you pass this directory as input to the {ProductShortName} {CLIName} using the `--rules` option, all rules in this directory are treated as a part of the ruleset defined by `ruleset.yaml` file.

The `ruleset.yaml` file stores the metadata of the ruleset.

[source,terminal]
----
name: "Name of the ruleset" <1>
description: "Description of the ruleset"
labels: <2>
  - key=val
----
<1> The name must be unique within the provided rulesets.
<2> Ruleset labels are inherited by all rules that belong to the ruleset.

To execute any application analysis, run the following command. Replace <application_to_analyze> with your application, <output_dir> with the directory of your choice, and <custom_rule_dir> with the custom rulesets file.
----
$ mta-cli analyze --input=<application_to_analyze> --output=<output_dir> --rules=<custom_rule_dir> --enable-default-rulesets=false
----

On initiation, the mta-cli tool determines the type of application and the corresponding provider needed for analysis. It then starts the provider in a container that has the required dependencies and tools. Finally, the provider uses the analyzer to execute a series of rulesets to analyze the source code.
