// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_mod-docs-content-type: REFERENCE

[id="yaml-java-locations_{context}"]
= Java locations

The `java` provider allows scoping the search down to certain source code locations.

The supported locations are the following:

* `CONSTRUCTOR_CALL`
* `TYPE`
* `INHERITANCE`
* `METHOD_CALL`
* `ANNOTATION`
* `IMPLEMENTS_TYPE`
* `ENUM_CONSTANT`
* `RETURN_TYPE`
* `IMPORT`
* `VARIABLE_DECLARATION`
* `FIELD`
* `METHOD`

.`dependency`

By using the `dependency` capability, the provider finds dependencies for a given application. {ProductShortName} generates a list of the application's dependencies, and you can use this capability to query the list and check whether a certain dependency exists for the application within a given range of the dependency's versions.

[source,yaml]
----
when:
  java.dependency:
    name: "<dependency_name>" # <1>
    upperbound: "<version_string>" # <2>
    lowerbound: "<version_string>" # <3>
----
<1> Name of the dependency to search for.
<2> Upper bound on the version of the dependency.
<3> Lower bound on the version of the dependency.
