:_newdoc-version: 2.18.7
:_template-generated: 2026-07-07
:_mod-docs-content-type: PROCEDURE

[id="exporting-manifests-from-the-source-cluster_{context}"]
= Exporting manifests from the source cluster

[role="_abstract"]
To capture your application’s deployment configuration, export the manifests to a local directory. You can use role impersonation if you do not have direct access.

.Prerequisites
* You have installed the `mta-ops` CLI on your system.
* You have active `kubeconfig` access to the source Red{nbsp}Hat OpenShift cluster.
* Optional: You have `cluster-admin` privileges to export all cluster-scoped dependencies.
+
WARNING: If you lack `cluster-admin` privileges, the export process generates warnings and extracts only the resources you have permission to access.


.Procedure
. Export manifests and cluster-level dependencies:
+
[subs="+quotes"]
----
$ *mta-ops export --context _<source_cluster_context>_ -n _<namespace>_ -e _<export_dir>_*
----

. Optional: To perform a partial namespace export based on resource labels, append the `-l` selector flag:
+
[subs="+quotes"]
----
$ *mta-ops export --context _<source_cluster_context>_ -n <namespace> -e _<export_dir>_ -l <label_key>=_<label_value>_*
----

. Optional: To perform service account-based migrations by using role impersonation, append the `--as` and `--as-group` flags:
+
[subs="+quotes"]
----
$ *mta-ops export --context _<source_cluster_context>_ -n _<namespace>_ -e _<export_dir>_ --as _<service_account_name>_ --as-group _<group_name>_*
----


.Verification
. Inspect the `export/resources/my-app/` directory to confirm raw resource files were created.
. If you lack `cluster-admin` privileges, inspect the `failures/` directory to identify any skipped resources.