:_newdoc-version: 2.18.5
:_template-generated: 2025-08-07
:_mod-docs-content-type: REFERENCE

[id="fixed-issues-8-0_{context}"]
= Fixed issues

[role="_abstract"]
{ProductFullName} version 8.0.0 provides the following fixed issues and other problems that have a significant impact. 

.The default `values.yaml` file is merged with the discover `values.yaml` file when generating a deployment manifest

Before this update, when you generated a deployment manifest by using the Helm template, the default values in the`values.yaml` file, packaged with the Helm chart, were ignored. Consequently, only the values from the `values.yaml` file created after running the `mta-cli discover` command were used. With this update, the default `values.yaml` file is merged with the discover `values.yaml` file.

(link:https://issues.redhat.com/browse/MTA-5793[MTA-5793])


.{ProductShortName} CLI no longer fails to detect dependencies for Gradle projects

Before this update, when you ran an application analysis for Gradle projects in containerless mode, {ProductFullName} command-line interface (CLI) did not detect Gradle dependencies. As a consequence, the analysis report did not list the dependencies and displayed an error message in the analysis logs instead. With this update, the issue is fixed. As a result, {ProductShortName} CLI detects Gradle dependencies after the analysis is complete.

(link:https://issues.redhat.com/browse/MTA-4033[MTA-5793])


.{ProductShortName} UI no longer fails to analyze projects built with Gradle version 7 and later

Before this update, when you analyzed an application built with Gradle in `Source code + dependencies` mode in the {ProductFullName} user interface (UI), the analysis  failed if you had Gradle version 7 or later installed. With this update, the issue is fixed.

(link:https://issues.redhat.com/browse/MTA-5907[MTA-5907])


.The discovery manifest lists all defined web processes in the application

Before this update, the `mta-cli discover` command only moved an application-level process with the process type explicitly defined to the `processes` block in the discovery manifest. Consequently, the discovery manifest did not list implicit application-level processes in the `processes` block. This resulted in the violation of the recommended clarity and proper configuration practices, especially if multiple process types were planned. With this update, `mta-cli discover` moves both implicit and explicit application-level process types to the `processes` block in the discovery manifest.


(link:https://issues.redhat.com/browse/MTA-6030[MTA-6030])

