:_newdoc-version: 2.18.7
:_template-generated: 2026-08-11
:_mod-docs-content-type: REFERENCE

[id="fixed-issues-8-2-1_{context}"]
= Fixed issues

[role="_abstract"]
Review issues that have been fixed in {ProductFullName} version 8.2.1.

`mta-ops transform` uses the `--overwrite` flag for consistent behavior::
Before this update, the `mta-ops transform` command used a `--force` flag. This flag functioned only with the `--instructions-file` option. Without an instructions file, plugin stage directories were silently overwritten. Additionally, custom stage directories blocked the pipeline with no way to proceed. With this release, the `--force` flag was replaced with `--overwrite`. This change aligns the `transform` command with other `mta-ops` subcommands. As a result, all stage directories require the `--overwrite` flag to replace existing content. This gives you explicit control over data replacement during a pipeline re-run.
+
link:https://redhat.atlassian.net/browse/MTA-7234[MTA-7234]


The {ProductShortName} Operator delegates authentication to the external Keycloak instance after an upgrade::
Before this update, an `IdentityProvider` custom resource (CR) that was not created by the Operator could specify the `primary: true` parameter. When this parameter was `true`, authentication was completely delegated to the external identity provider (IdP). As a result, only the external IdP login page was presented. However, the `IdentityProvider` CR created by the Operator during an upgrade did not specify `primary: true`. With this release, the Operator sets `primary: true` by default in the managed `IdentityProvider`. Additionally, the Tackle CR supports the `idp_primary` field that is propagated to the Operator-managed `IdentityProvider`.
+
link:https://redhat.atlassian.net/browse/MTA-7496[MTA-7496]