:_newdoc-version: 2.18.5
:_template-generated: 2026-02-13
:_mod-docs-content-type: REFERENCE

[id="new-features-and-enhancements-8-1-0_{context}"]
= New features and enhancements

[role="_abstract"]
{ProductFirstRef} ({ProductShortName}) version 8.1.0 provides the following major new features and enhancements.


Centralized configuration management across components for standardizing analysis configuration and custom rules::
You can use the centralized configuration management to standardize analysis configurations and custom rules for the following {ProductFullName} components:

* User interface (UI)
* Command-line interface (CLI)
* The Visual Studio Code {ProductShortName} extension.

+
--
Profiles contain analysis configuration that allows organizations to standardize configuration and simplify configuration management by adopting a platform engineering approach. The architect can create, update, and delete profiles and custom rules. Migrators can sync with the {ProductShortName} Hub to download available configuration bundles and use them to run an analysis in the UI, CLI, and by using the Visual Studio Code plugin.

(link:https://issues.redhat.com/browse/MTA-6491[MTA-6491])
--



C# provider for analyzing .NET and C# applications across {ProductShortName} components::
You can use the external `csharp` provider to analyze .NET and C# source code in the {ProductFullName} command-line interface (CLI), user interface, and the {ProductShortName} Visual Studio Code extension. `csharp` uses a gRPC interface to parse using tree-sitter and uses stack graph to perform a semantic analysis of your codebases to identify violations before you migrate your code. 
The `csharp` provider supports referenced capability in rules used to perform the {ProductShortName} analysis. Configure fields such as `pattern`, `location`, and `file_path` in the rules based on which the provider searches the code for type, classes, methods, and fields in the source code.
+
(link:https://issues.redhat.com/browse/MTA-6492[MTA-6492])


The {ProductShortName} Visual Studio Code extension pack and the Core extension with language-specific extension are available::
The {ProductFullName} Visual Studio Code extension consists of an analyzer RPC binary that runs an analysis for the following applications:

* Java
* Go
* Python
* Node.js
* C#
* .NET

+
--
You can download the {ProductShortName} version 8.1.0 Visual Studio Code extension as an extension pack that bundles the Core extension along with all the supported language-specific extensions. You can also use this extension when you want to analyze a project in a specific programming language. Alternatively, you can download the {ProductShortName} Core extension with one language-specific extension to analyze a project coded in the programming language supported by the extension.
--


(Placeholder) Support for LLM Proxying with MTA


