:_newdoc-version: 2.18.5
:_template-generated: 2025-08-07
:_mod-docs-content-type: REFERENCE

[id="fixed-issues-8-0-1_{context}"]
= Fixed issues

[role="_abstract"]
Review issues that have been fixed in {ProductFullName} version 8.0.1.  

Improved the performance of Java binary analysis::
Before this update, when you analyzed Java binary applications, {ProductShortName} incorrectly classified some open source dependencies as internal dependencies. As a consequence, {ProductShortName} decompiled and analyzed these dependencies, which increased the analysis time. With this update, {ProductShortName} passes the location of the Maven index file to the Java provider. As a result, {ProductShortName} correctly determines whether an embedded dependency is open source or internal.

Analysis of binary applications classifies open source dependencies correctly::
Before this update, when you analyzed Java binary applications, {ProductShortName} incorrectly classified some open source dependencies as internal dependencies. With this update, {ProductShortName} classifies embedded open source dependencies correctly after a `source+dependency` binary analysis. 
+
link:https://issues.redhat.com/browse/MTA-6357[MTA-6357]

You can specify an organization when importing applications from Cloud Foundry::
Before this update, when you imported applications from Cloud Foundry (CF), {ProductShortName} did not have a provision for you to mention the CF organizations. With this update, you can configure one or more organizations, spaces, and applications for the discovery process. The spaces can belong to different organizations and the applications can belong to different spaces. You must specify at least one organization for application discovery. 
+
link:https://issues.redhat.com/browse/MTA-6271[MTA-6271]

{ProductShortName} {CLIName} correctly processes Cloud Foundry applications with service binding::
Before this update, the discovery process of Cloud Foundry (CF) applications with service bindings by using live connection failed in {ProductShortName} {CLIName}. The {ProductShortName} {CLIName} did not parse the `VCAP_SERVICES` environment variables correctly to handle service binding information for an array of services, for example, `cf bind-service _<application_name>_ postgres01`. With this update, {ProductShortName} {CLIName} successfully completes the discovery of CF applications with service bindings. 
+
link:https://issues.redhat.com/browse/MTA-6399[MTA-6399]

{ProductShortName} automatically tags imported Cloud Foundry applications::
Before this update, when you imported applications from a Cloud Foundry (CF) instance, they lacked the `Cloud Foundry` tag. As a consequence, you had to manually add this tag to link an application to an archetype. With this update, {ProductShortName} automatically applies the tag. As a result, you no longer have to add it manually.
+
link:https://issues.redhat.com/browse/MTA-6282[MTA-6282]

You can import Cloud Foundry applications from the application inventory in the {ProductShortName} web console:: 
Before this update, an {ProductShortName} Architect could not discover or import applications from the Cloud Foundry (CF) source platform on the application inventory page. As a consequence, only an {ProductShortName} Administrator could import the applications on the *Source platforms* page in the Administrator mode. With this update, Architects can import CF applications in the *Application Inventory*. 
+
link:https://issues.redhat.com/browse/MTA-6120[MTA-6120]

Concurrent usage of {mta-dl-plugin} for code resolution at scale no longer causes race conditions::
Before this update, concurrent usage of the Solution Server through the {mta-dl-plugin} in Visual Studio Code for code resolution at scale caused race conditions for duplicate incidents. With this update, the plugin generates resolutions for the incidents identified when many users use it concurrently. 
+
link:https://issues.redhat.com/browse/MTA-6230[MTA-6230]

{ProductShortName} uses FQNs in Java rules to match annotations in source code:: 
Before this update, the annotation rules for Java applications did not use Fully Qualified Names (FQNs) to match with the annotation location in source code. As a consequence, the rule triggered incorrect matches or false positives for issues. For example, a rule that looked for the `javax.enterprise.inject.Produces` incorrectly matched with occurrences of `javax.ws.rs.Produces`. With this update, {ProductShortName} uses the FQN in the `ANNOTATION` field in rules to match annotations in the source code.
+
link:https://issues.redhat.com/browse/MTA-6195[MTA-6195]

{ProductShortName} triggers rules to match import statements with a wildcard in Java applications analysis::
Before this update, when analyzing a Java application, {ProductShortName} did not trigger rules to match import statements that contained a wildcard. As a consequence, {ProductShortName} did not detect specific incidents in the report. With this update, {ProductShortName} triggers the rules to match these statements. As a result, it successfully detects the incidents.
+
link:https://issues.redhat.com/browse/MTA-4027[MTA-4027]

You can edit secure SVN application without an error in {ProductShortName} {WebName}::
Before this update, editing an application stored in a Subversion (SVN) repository caused issues if you disabled the `Allow insecure connection` setting. As a consequence, the {WebName} displayed a blank page with the `TypeError` `cannot read properties of undefined (reading 'kind')` error. With this update, {ProductShortName} correctly handles secure SVN applications. As a result, you can successfully edit these applications in the {WebName}.
+
link:https://issues.redhat.com/browse/MTA-6263[MTA-6263]

{ProductShortName} no longer fails language and tech discovery for Java application in SVN repositories::
Before this update, for a Java application source code stored in an Subversion (SVN) repository, {ProductShortName} produced an error when trying to checkout the repository by using the SVN credential. As a consequence, the language and tech discovery of the application failed. With this update, you can analyze an application stored in SVN repository without any error.
+
link:https://issues.redhat.com/browse/MTA-6141[MTA-6141]

{ProductShortName} displays source repository URL when you skip configuring the repository type field::
Before this update, {ProductShortName} did not show the source repository URL in the application details view if you did not select between the `Git` or `Subversion` repository type. As a consequence, you could not run an analysis on the application source code. With this update, you can use {ProductShortName} to run an analysis on the source code even if you do not configure the repository type field.
+
link:https://issues.redhat.com/browse/MTA-6105[MTA-6105]

You can complete an assessment by using a custom questionnaire in the {ProductShortName} {WebName}:: 
Before this update, you could not proceed to the final step after filling in the responses to the custom questionnaire because {ProductShortName} disabled the *Next* button in the web console. With this update, you can complete the questionnaire in {ProductShortName} {WebName}.
+
link:https://issues.redhat.com/browse/MTA-6143[MTA-6143]

{ProductShortName} web console detects custom rules when you upload multiple rules at once::
Before this update, when you uploaded more than one custom rule at a time in the web console, {ProductShortName} did not detect the rules. With this update, you can upload one or more custom rules at once.
+
link:https://issues.redhat.com/browse/MTA-6029[MTA-6029]