:_newdoc-version: 2.18.5
:_template-generated: 2025-09-09
:_mod-docs-content-type: REFERENCE

[id="known-issues-8-0_{context}"]
= Known issues

[role="_abstract"]
{ProductFirstRef} ({ProductShortName}) version 8.0.0 is affected by the following newly identified and previously known issues. A known issue is listed in all future release notes until resolved, at which point it is published as a fixed issue.


Application analysis with {ProductShortName} CLI might fail with the "invalid header line" error::
An application analysis by using the {ProductFullName} command-line interface (CLI) might fail with the following error message:
+
----
level=error msg="initialize failed" error="context canceled" provider=java
error="invalid header line "An error has occurred. See the log file"
----
+
To work around this problem, clean up metadata and cache:

. Clear the `.metadata` subdirectory under the directory from which you ran the `mta-cli analyze` command.
. Clear the Maven cache.

+
(link:https://issues.redhat.com/browse/MTA-6125[MTA-6125])



{ProductShortName} analysis result does not change if you add or remove a custom rule::
When you use Red Hat Developer Lightspeed for {ProductShortName}, the analysis results do not change if you include or remove a custom rule but do not restart the analyzer process. 
+
To work around this problem, restart the analyzer process by clicking the *Start or Stop* button after making a configuration change.
+
(link:https://issues.redhat.com/browse/MTA-6129[MTA-6129])


`ANNOTATION` location rules do not match on FQNs::
The `ANNOTATION` search location does not properly use Fully Qualified Names (FQNs) to match annotations. This leads to incorrect matches and false positives in analysis issues. For example, a rule that searches for annotations by using the `javax.enterprise.inject.Produces` pattern might incorrectly match the occurrences of the `javax.ws.rs.Produces` annotation in the source code.
+
No known workaround exists.
+
(link:https://issues.redhat.com/browse/MTA-6195[MTA-6195])


Red Hat Developer Lightspeed for {ProductShortName} database throws a connection error::
The Solution Server throws a connection error when concurrent connections increase in a short span of time. To work around this problem, enter the following command to allow the Red Hat Developer Lightspeed for {ProductShortName} database to expire idle connections:
+
----
oc -n openshift-mta exec deploy/kai-db – psql -U postgres -d postgres -c "ALTER ROLE kai SET idle_session_timeout = '1min'; ALTER ROLE kai SET idle_in_transaction_session_timeout = '1min';" 
----
+
(link:https://issues.redhat.com/browse/MTA-6204[MTA-6204])
