:_newdoc-version: 2.18.7
:_template-generated: 2026-08-11
:_mod-docs-content-type: REFERENCE

[id="fixed-issues-8-2-1_{context}"]
= Fixed issues

[role="_abstract"]
Review issues that have been fixed in {ProductFullName} version 8.2.1.

`mta-ops transform` uses the `--overwrite` flag for consistent behavior::
Before this update, the `mta-ops transform` command used a `--force` flag. This flag functioned only with the `--instructions-file` option. Without an instructions file, plugin stage directories were silently overwritten. Additionally, custom stage directories blocked the pipeline with no way to proceed. With this release, the `--force` flag was replaced with `--overwrite`. This change aligns the `transform` command with other `mta-ops` subcommands. As a result, all stage directories require the `--overwrite` flag to replace existing content. This gives you explicit control over data replacement during a pipeline re-run.
+
link:https://redhat.atlassian.net/browse/MTA-7234[MTA-7234]


The {ProductShortName} Operator delegates authentication to the external Keycloak instance after an upgrade::
Before this update, you could set the `idp_primary` parameter to `true` in the {ProductShortName} Operator custom resource (CR). However, during an upgrade, the Operator did not delegate authentication to the external Keycloak instance. As a consequence, the system continued to use the internal Keycloak instance. This caused incorrect authentication when you attempted to log in. With this release, the Operator processes the `idp_primary` parameter during an upgrade. As a result, the system delegates authentication to the external Keycloak instance when the parameter is `true`.
+
link:https://redhat.atlassian.net/browse/MTA-7496[MTA-7496]