:_newdoc-version: 2.18.5
:_template-generated: 2025-09-09
:_mod-docs-content-type: REFERENCE

[id="known-issues-8-0-1_{context}"]
= Known issues

[role="_abstract"]
{ProductFullName} version 8.0.1 is affected by the following newly identified and previously known issues. A known issue is listed in all future release notes until resolved, at which point it is published as a fixed issue.

.{ProductShortName} {WebName} displays errors when you edit an SVN application that requires a secure connection

In the {ProductShortName} {WebName}, if you disable the `Allow insecure connection` for an application stored in the SVN repository and edit the application, the {WebName} displays a blank page some times with the `TypeError` `cannot read properties of undefined (reading 'kind')`.

No known workaround exists. link:https://issues.redhat.com/browse/MTA-6263([MTA-6263])

.{ProductShortName} assessment form malfunctions when you use it with a custom questinnaire 

In the {ProductShortName} {WebName}, selecting an answer to a question in the assessment form generated from a custom questionnaire causes the form to select an option available for another question.

No known workaround exists. link:https://issues.redhat.com/browse/MTA-6262([MTA-6262])