:_newdoc-version: 2.18.7
:_template-generated: 2026-03-16
:_mod-docs-content-type: REFERENCE

[id="dev-preview_{context}"]
= Developer Preview features

[role="_abstract"]
This section provides a list of all Developer Preview features available in {ProductFullName} ({ProductShortName}) 8.1.0.

For more information about the support scope of Red{nbsp}Hat Developer Preview software, see link:https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope].
 

C# provider for analyzing C# applications in `source-only` mode across {ProductShortName} components (Technology Preview)::
You can use the external `csharp` provider to run an analysis in `source-only` mode for C# source code in the {ProductFullName} command-line interface (CLI), user interface, and the {ProductShortName} Visual Studio Code extension. `csharp` parses the source code by using tree-sitter and uses stack graph for the analysis to find references to types, methods, classes, and fields. Based on the `C#` rule definition, the analyzer identifies violations in your code that you must resolve before the application migration.
+
(link:https://issues.redhat.com/browse/MTA-6492[MTA-6492])