:_newdoc-version: 2.18.3
:_template-generated: 2025-03-14

ifdef::context[:parent-context-of-installing-mta-cli: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="installing-mta-cli"]
endif::[]
ifdef::context[]
[id="installing-mta-cli_{context}"]
endif::[]
= Installing the {ProductName} command-line interface

:context: installing-mta-cli
 
[role="_abstract"]
You can use the {ProductFullName} command-line interface (CLI) to assess and prioritize migration and modernization efforts for applications. You can use different command options to adapt the CLI behavior to your needs. You can tune the {ProductShortName} analysis options or integrate with external automation tools.

You can install the {ProductShortName} command-line interface (CLI) on Linux, Windows, or macOS operating systems. You can also install the CLI for use with Docker on Windows. Note, however, that this is a Developer Preview feature only.

include::topics/mta-install/proc_installing-cli-zip.adoc[leveloffset=+1]

include::topics/mta-install/proc_installing-mta-disconnected-environment.adoc[leveloffset=+1]

include::topics/mta-install/proc_installing-cli-for-docker.adoc[leveloffset=+1]


ifdef::parent-context-of-installing-mta-cli[:context: {parent-context-of-installing-mta-cli}]
ifndef::parent-context-of-installing-mta-cli[:!context:]

