:_newdoc-version: 2.18.3
:_template-generated: 2025-04-10

ifdef::context[:parent-context-of-installing-mta-ui: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="installing-mta-ui"]
endif::[]
ifdef::context[]
[id="installing-mta-ui_{context}"]
endif::[]
= Installing the {ProductName} user interface
:context: installing-mta-ui

[role="_abstract"]
By using the {ProductFullName} user interface (UI), you can assess the risks involved in containerizing an application for hybrid cloud environments on Red Hat OpenShift. You can also analyze the changes that you must apply to the application's code to containerize the application. You can install the {ProductName} UI on all Red Hat OpenShift cloud services and Red Hat OpenShift self-managed editions.			

To create {ProductShortName} instances, you must install the {ProductShortName} Operator first. The {ProductShortName} Operator is a structural layer that manages resources deployed on Red Hat OpenShift, such as database, front end, and back end, to automatically create an {ProductShortName} instance. 
	
include::topics/mta-install/ref_persistent-volume-requirements.adoc[leveloffset=+1]

include::assembly_red-hat-build-of-keycloak.adoc[leveloffset=+1]

include::topics/mta-install/proc_installing-mta-operator.adoc[leveloffset=+1]

include::topics/mta-install/proc_creating-mta-instance.adoc[leveloffset=+1]

include::topics/mta-install/ref_custom-resource-settings.adoc[leveloffset=+1]


ifdef::parent-context-of-installing-mta-ui[:context: {parent-context-of-installing-mta-ui}]
ifndef::parent-context-of-installing-mta-ui[:!context:]

