:_newdoc-version: 2.18.5
:_template-generated: 2025-07-31
:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context-of-intro-to-mta: {context}]

ifndef::context[]
[id="intro-to-mta"]
endif::[]
ifdef::context[]
[id="intro-to-mta_{context}"]
endif::[]
= Introduction to the {ProductName}

:context: intro-to-mta

[role="_abstract"]
The {ProductFullName} is a set of tools that you can use to accelerate large-scale application modernization efforts across hybrid cloud environments on Red Hat OpenShift. {ProductShortName} looks for common resources and problematic spots when migrating applications. It gives a high-level view of the technologies used by the application. {ProductShortName} also generates a detailed report that evaluates a migration or modernization path. By using this report, you can estimate the effort needed for large-scale projects and reduce the workload involved in the process. 

By using {ProductShortName}, you can perform the following tasks: 		

* Use the {ProductShortName} extensive default questionnaire to assess your applications, or create your own custom questionnaire to estimate the difficulty, time, and other resources needed to prepare an application for containerization. You can use the results of an assessment to determine applications suitable for containerization.

* Analyze applications by applying sets of rules to each application. You can use these rules to determine which specific lines of the application you must modify before modernizing the application. 				

* Examine application artifacts, including project source directories and application archives, and produce an HTML report that highlights areas that require changes. 

include::topics/mta-install/con_mta-features.adoc[leveloffset=+1]

include::topics/mta-install/con_mta-rules.adoc[leveloffset=+1]

include::topics/mta-install/con_mta-tools.adoc[leveloffset=+1]

ifdef::parent-context-of-intro-to-mta[:context: {parent-context-of-intro-to-mta}]
ifndef::parent-context-of-intro-to-mta[:!context:]

