:_newdoc-version: 2.18.5
:_template-generated: 2025-07-31
:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context-of-red-hat-build-of-keycloak: {context}]

ifndef::context[]
[id="red-hat-build-of-keycloak"]
endif::[]
ifdef::context[]
[id="red-hat-build-of-keycloak_{context}"]
endif::[]
= Red Hat Build of Keycloak

:context: red-hat-build-of-keycloak

[role="_abstract"]
{ProductFullName} uses the Red Hat Build of Keycloak (RHBK) instance for user authentication and authorization. The RHBK instance is installed during the installation of the {ProductShortName} user interface. The {ProductShortName} Operator manages the RHBK instance and configures a dedicated realm with necessary roles and permissions.

You can use the {ProductShortName}-managed RHBK instance to perform advanced RHBK configurations, such as adding a provider for User Federation or integrating identity providers. 

include::topics/mta-install/proc_accessing-rhbk-admin-console.adoc[leveloffset=+1]

include::topics/mta-install/con_roles-personas-users-permissions.adoc[leveloffset=+1]



ifdef::parent-context-of-red-hat-build-of-keycloak[:context: {parent-context-of-red-hat-build-of-keycloak}]
ifndef::parent-context-of-red-hat-build-of-keycloak[:!context:]

